/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  LoginRequest,
  LoginResponse,
  LogoutResponse,
  RegisterRequest,
  RegisterResponse,
} from "../models";

/**
 * Login user.
 * @summary Login user.
 */
export const login = <TData = AxiosResponse<LoginResponse>>(
  loginRequest: LoginRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/api/login`, loginRequest, options);
};
/**
 * Logout user.
 * @summary Logout user.
 */
export const logout = <TData = AxiosResponse<LogoutResponse>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.delete(`/api/logout`, options);
};
/**
 * Register user.
 * @summary Register user.
 */
export const register = <TData = AxiosResponse<RegisterResponse>>(
  registerRequest: RegisterRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/api/register`, registerRequest, options);
};
export type LoginResult = AxiosResponse<LoginResponse>;
export type LogoutResult = AxiosResponse<LogoutResponse>;
export type RegisterResult = AxiosResponse<RegisterResponse>;
