/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  LoginRequest,
  LoginResponse,
  LogoutResponse,
  RegisterRequest,
  RegisterResponse,
} from "../models";

/**
 * Login user.
 * @summary Login user.
 */
export const login = (
  loginRequest: LoginRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<LoginResponse>> => {
  return axios.post(`/api/login`, loginRequest, options);
};
export const getLoginUrl = () => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/login`,
      baseURL: "",
    });
};
/**
 * Logout user.
 * @summary Logout user.
 */
export const logout = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<LogoutResponse>> => {
  return axios.delete(`/api/logout`, options);
};
export const getLogoutUrl = () => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/logout`,
      baseURL: "",
    });
};
/**
 * Register user.
 * @summary Register user.
 */
export const register = (
  registerRequest: RegisterRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<RegisterResponse>> => {
  return axios.post(`/api/register`, registerRequest, options);
};
export const getRegisterUrl = () => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/register`,
      baseURL: "",
    });
};
export type LoginResult = AxiosResponse<LoginResponse>;
export type LogoutResult = AxiosResponse<LogoutResponse>;
export type RegisterResult = AxiosResponse<RegisterResponse>;
