/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  IndexCategoriesParams,
  IndexCategoryResponse,
  ShowCategoryParams,
  ShowCategoryResponse,
} from "../models";

/**
 * @summary Index categories.
 */
export const indexCategories = (
  params?: IndexCategoriesParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<IndexCategoryResponse>> => {
  return axios.get(`/api/categories`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getIndexCategoriesUrl = (params?: IndexCategoriesParams) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/categories`,
      baseURL: "",
      params,
    });
};
/**
 * @summary Show category by id.
 */
export const showCategory = (
  id: number,
  params?: ShowCategoryParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ShowCategoryResponse>> => {
  return axios.get(`/api/categories/${id}`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getShowCategoryUrl = (id: number, params?: ShowCategoryParams) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/categories/${id}`,
      baseURL: "",
      params,
    });
};
export type IndexCategoriesResult = AxiosResponse<IndexCategoryResponse>;
export type ShowCategoryResult = AxiosResponse<ShowCategoryResponse>;
