/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  IndexCategoriesParams,
  IndexCategoryResponse,
  ShowCategoryParams,
  ShowCategoryResponse,
} from "../models";

/**
 * @summary Index categories.
 */
export const indexCategories = <TData = AxiosResponse<IndexCategoryResponse>>(
  params?: IndexCategoriesParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/categories`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
/**
 * @summary Show category by id.
 */
export const showCategory = <TData = AxiosResponse<ShowCategoryResponse>>(
  id: number,
  params?: ShowCategoryParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/categories/${id}`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export type IndexCategoriesResult = AxiosResponse<IndexCategoryResponse>;
export type ShowCategoryResult = AxiosResponse<ShowCategoryResponse>;
