/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  DestroyCommentResponse,
  IndexCommentResponse,
  IndexCommentsParams,
  ShowCommentResponse,
  StoreCommentRequest,
  StoreCommentResponse,
  UpdateCommentRequest,
  UpdateCommentResponse,
} from "../models";

/**
 * @summary Index comments.
 */
export const indexComments = <TData = AxiosResponse<IndexCommentResponse>>(
  params: IndexCommentsParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/comments`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
/**
 * @summary Store comment.
 */
export const storeComment = <TData = AxiosResponse<StoreCommentResponse>>(
  storeCommentRequest: StoreCommentRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/api/comments`, storeCommentRequest, options);
};
/**
 * @summary Show comment by id.
 */
export const showComment = <TData = AxiosResponse<ShowCommentResponse>>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/comments/${id}`, options);
};
/**
 * @summary Delete comment.
 */
export const destroyComment = <TData = AxiosResponse<DestroyCommentResponse>>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.delete(`/api/comments/${id}`, options);
};
/**
 * @summary Update comment.
 */
export const updateComment = <TData = AxiosResponse<UpdateCommentResponse>>(
  id: number,
  updateCommentRequest: UpdateCommentRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.patch(`/api/comments/${id}`, updateCommentRequest, options);
};
export type IndexCommentsResult = AxiosResponse<IndexCommentResponse>;
export type StoreCommentResult = AxiosResponse<StoreCommentResponse>;
export type ShowCommentResult = AxiosResponse<ShowCommentResponse>;
export type DestroyCommentResult = AxiosResponse<DestroyCommentResponse>;
export type UpdateCommentResult = AxiosResponse<UpdateCommentResponse>;
