/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  DestroyCommentResponse,
  IndexCommentResponse,
  IndexCommentsParams,
  ShowCommentResponse,
  StoreCommentRequest,
  StoreCommentResponse,
  UpdateCommentRequest,
  UpdateCommentResponse,
} from "../models";

/**
 * @summary Index comments.
 */
export const indexComments = (
  params: IndexCommentsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<IndexCommentResponse>> => {
  return axios.get(`/api/comments`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getIndexCommentsUrl = (params: IndexCommentsParams) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/comments`,
      baseURL: "",
      params,
    });
};
/**
 * @summary Store comment.
 */
export const storeComment = (
  storeCommentRequest: StoreCommentRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<StoreCommentResponse>> => {
  return axios.post(`/api/comments`, storeCommentRequest, options);
};
export const getStoreCommentUrl = () => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/comments`,
      baseURL: "",
    });
};
/**
 * @summary Show comment by id.
 */
export const showComment = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ShowCommentResponse>> => {
  return axios.get(`/api/comments/${id}`, options);
};
export const getShowCommentUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/comments/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Delete comment.
 */
export const destroyComment = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<DestroyCommentResponse>> => {
  return axios.delete(`/api/comments/${id}`, options);
};
export const getDestroyCommentUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/comments/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Update comment.
 */
export const updateComment = (
  id: number,
  updateCommentRequest: UpdateCommentRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<UpdateCommentResponse>> => {
  return axios.patch(`/api/comments/${id}`, updateCommentRequest, options);
};
export const getUpdateCommentUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/comments/${id}`,
      baseURL: "",
    });
};
export type IndexCommentsResult = AxiosResponse<IndexCommentResponse>;
export type StoreCommentResult = AxiosResponse<StoreCommentResponse>;
export type ShowCommentResult = AxiosResponse<ShowCommentResponse>;
export type DestroyCommentResult = AxiosResponse<DestroyCommentResponse>;
export type UpdateCommentResult = AxiosResponse<UpdateCommentResponse>;
