/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  IndexDiscountResponse,
  IndexDiscountsParams,
  ShowDiscountResponse,
} from "../models";

/**
 * @summary Index discounts.
 */
export const indexDiscounts = <TData = AxiosResponse<IndexDiscountResponse>>(
  params?: IndexDiscountsParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/discounts`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
/**
 * @summary Show discount by id.
 */
export const showDiscount = <TData = AxiosResponse<ShowDiscountResponse>>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/discounts/${id}`, options);
};
export type IndexDiscountsResult = AxiosResponse<IndexDiscountResponse>;
export type ShowDiscountResult = AxiosResponse<ShowDiscountResponse>;
