/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  IndexDishMenuResponse,
  IndexDishMenusParams,
  ShowDishMenuParams,
  ShowDishMenuResponse,
} from "../models";

/**
 * @summary Index dish menus.
 */
export const indexDishMenus = (
  params?: IndexDishMenusParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<IndexDishMenuResponse>> => {
  return axios.get(`/api/dishes/menus`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getIndexDishMenusUrl = (params?: IndexDishMenusParams) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/dishes/menus`,
      baseURL: "",
      params,
    });
};
/**
 * @summary Show dish menu by id.
 */
export const showDishMenu = (
  id: number,
  params?: ShowDishMenuParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ShowDishMenuResponse>> => {
  return axios.get(`/api/dishes/menus/${id}`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getShowDishMenuUrl = (id: number, params?: ShowDishMenuParams) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/dishes/menus/${id}`,
      baseURL: "",
      params,
    });
};
export type IndexDishMenusResult = AxiosResponse<IndexDishMenuResponse>;
export type ShowDishMenuResult = AxiosResponse<ShowDishMenuResponse>;
