/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  IndexDishCategoriesParams,
  IndexDishCategoryResponse,
  ShowDishCategoryParams,
  ShowDishCategoryResponse,
} from "../models";

/**
 * @summary Index dish categories.
 */
export const indexDishCategories = (
  params?: IndexDishCategoriesParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<IndexDishCategoryResponse>> => {
  return axios.get(`/api/dishes/categories`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getIndexDishCategoriesUrl = (
  params?: IndexDishCategoriesParams,
) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/dishes/categories`,
      baseURL: "",
      params,
    });
};
/**
 * @summary Show dish category by id.
 */
export const showDishCategory = (
  id: number,
  params?: ShowDishCategoryParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ShowDishCategoryResponse>> => {
  return axios.get(`/api/dishes/categories/${id}`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getShowDishCategoryUrl = (
  id: number,
  params?: ShowDishCategoryParams,
) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/dishes/categories/${id}`,
      baseURL: "",
      params,
    });
};
export type IndexDishCategoriesResult =
  AxiosResponse<IndexDishCategoryResponse>;
export type ShowDishCategoryResult = AxiosResponse<ShowDishCategoryResponse>;
