/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  IndexDishVariantResponse,
  IndexDishVariantsParams,
  ShowDishVariantParams,
  ShowDishVariantResponse,
} from "../models";

/**
 * @summary Index dish variants.
 */
export const indexDishVariants = <
  TData = AxiosResponse<IndexDishVariantResponse>,
>(
  params?: IndexDishVariantsParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/dishes/variants`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
/**
 * @summary Show dish variant by id.
 */
export const showDishVariant = <TData = AxiosResponse<ShowDishVariantResponse>>(
  id: number,
  params?: ShowDishVariantParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/dishes/variants/${id}`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export type IndexDishVariantsResult = AxiosResponse<IndexDishVariantResponse>;
export type ShowDishVariantResult = AxiosResponse<ShowDishVariantResponse>;
