/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  IndexDishMenuResponse,
  IndexDishMenusParams,
  ShowDishMenuParams,
  ShowDishMenuResponse,
} from "../models";

/**
 * @summary Index dish menus.
 */
export const indexDishMenus = <TData = AxiosResponse<IndexDishMenuResponse>>(
  params?: IndexDishMenusParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/dishes/menus`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
/**
 * @summary Show dish menu by id.
 */
export const showDishMenu = <TData = AxiosResponse<ShowDishMenuResponse>>(
  id: number,
  params?: ShowDishMenuParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/dishes/menus/${id}`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export type IndexDishMenusResult = AxiosResponse<IndexDishMenuResponse>;
export type ShowDishMenuResult = AxiosResponse<ShowDishMenuResponse>;
