/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  IndexDishCategoriesParams,
  IndexDishCategoryResponse,
  ShowDishCategoryParams,
  ShowDishCategoryResponse,
} from "../models";

/**
 * @summary Index dish categories.
 */
export const indexDishCategories = <
  TData = AxiosResponse<IndexDishCategoryResponse>,
>(
  params?: IndexDishCategoriesParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/dishes/categories`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
/**
 * @summary Show dish category by id.
 */
export const showDishCategory = <
  TData = AxiosResponse<ShowDishCategoryResponse>,
>(
  id: number,
  params?: ShowDishCategoryParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/dishes/categories/${id}`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export type IndexDishCategoriesResult =
  AxiosResponse<IndexDishCategoryResponse>;
export type ShowDishCategoryResult = AxiosResponse<ShowDishCategoryResponse>;
