/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  IndexDishVariantResponse,
  IndexDishVariantsParams,
  ShowDishVariantParams,
  ShowDishVariantResponse,
} from "../models";

/**
 * @summary Index dish variants.
 */
export const indexDishVariants = (
  params?: IndexDishVariantsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<IndexDishVariantResponse>> => {
  return axios.get(`/api/dishes/variants`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getIndexDishVariantsUrl = (params?: IndexDishVariantsParams) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/dishes/variants`,
      baseURL: "",
      params,
    });
};
/**
 * @summary Show dish variant by id.
 */
export const showDishVariant = (
  id: number,
  params?: ShowDishVariantParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ShowDishVariantResponse>> => {
  return axios.get(`/api/dishes/variants/${id}`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getShowDishVariantUrl = (
  id: number,
  params?: ShowDishVariantParams,
) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/dishes/variants/${id}`,
      baseURL: "",
      params,
    });
};
export type IndexDishVariantsResult = AxiosResponse<IndexDishVariantResponse>;
export type ShowDishVariantResult = AxiosResponse<ShowDishVariantResponse>;
