/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  DestroyDishResponse,
  DestroyRequest,
  GetRestaurantDishes200,
  GetRestaurantDishesParams,
  IndexDishResponse,
  IndexDishesParams,
  RestoreDishResponse,
  ShowDishParams,
  ShowDishResponse,
  StoreDishRequest,
  StoreDishResponse,
  UpdateDishRequest,
  UpdateDishResponse,
} from "../models";

/**
 * @summary Index dishes.
 */
export const indexDishes = (
  params?: IndexDishesParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<IndexDishResponse>> => {
  return axios.get(`/api/dishes`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getIndexDishesUrl = (params?: IndexDishesParams) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/dishes`,
      baseURL: "",
      params,
    });
};
/**
 * @summary Store dish.
 */
export const storeDish = (
  storeDishRequest: StoreDishRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<StoreDishResponse>> => {
  return axios.post(`/api/dishes`, storeDishRequest, options);
};
export const getStoreDishUrl = () => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/dishes`,
      baseURL: "",
    });
};
/**
 * @summary Show dish by id.
 */
export const showDish = (
  id: number,
  params?: ShowDishParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ShowDishResponse>> => {
  return axios.get(`/api/dishes/${id}`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getShowDishUrl = (id: number, params?: ShowDishParams) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/dishes/${id}`,
      baseURL: "",
      params,
    });
};
/**
 * @summary Delete dish.
 */
export const destroyDish = (
  id: number,
  destroyRequest?: DestroyRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<DestroyDishResponse>> => {
  return axios.delete(`/api/dishes/${id}`, {
    data: destroyRequest,
    ...options,
  });
};
export const getDestroyDishUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/dishes/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Update dish.
 */
export const updateDish = (
  id: number,
  updateDishRequest: UpdateDishRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<UpdateDishResponse>> => {
  return axios.patch(`/api/dishes/${id}`, updateDishRequest, options);
};
export const getUpdateDishUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/dishes/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Restore dish.
 */
export const restoreDish = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<RestoreDishResponse>> => {
  return axios.post(`/api/dishes/${id}/restore`, undefined, options);
};
export const getRestoreDishUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/dishes/${id}/restore`,
      baseURL: "",
    });
};
/**
 * @summary All dishes guests see on the restaurant's pages, in the language (gzipped JSON).
 */
export const getRestaurantDishes = (
  id: string,
  params: GetRestaurantDishesParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetRestaurantDishes200>> => {
  return axios.get(`/api/restaurants/${id}/dishes`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getGetRestaurantDishesUrl = (
  id: string,
  params: GetRestaurantDishesParams,
) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/restaurants/${id}/dishes`,
      baseURL: "",
      params,
    });
};
export type IndexDishesResult = AxiosResponse<IndexDishResponse>;
export type StoreDishResult = AxiosResponse<StoreDishResponse>;
export type ShowDishResult = AxiosResponse<ShowDishResponse>;
export type DestroyDishResult = AxiosResponse<DestroyDishResponse>;
export type UpdateDishResult = AxiosResponse<UpdateDishResponse>;
export type RestoreDishResult = AxiosResponse<RestoreDishResponse>;
export type GetRestaurantDishesResult = AxiosResponse<GetRestaurantDishes200>;
