/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  EditorCategoryResponse,
  EditorDishResponse,
  EditorMenuResponse,
  EditorMoveCategoryRequest,
  EditorMoveDishRequest,
  EditorOrderMenusRequest,
  EditorRestaurantResponse,
  EditorRestaurantsResponse,
  EditorStoreCategoryRequest,
  EditorStoreDishRequest,
  EditorStoreMenuRequest,
  EditorUpdateCategoryRequest,
  EditorUpdateDishRequest,
  EditorUpdateMenuRequest,
  EditorUpdateRestaurantHoursRequest,
  EditorUpdateRestaurantNotesRequest,
  EditorUpdateRestaurantPhotosRequest,
  EditorUpdateRestaurantRequest,
  EditorUploadPhotoRequest,
  StoreMediaResponse,
  SuccessResponse,
} from "../models";

/**
 * @summary Create a category at the end of the menu.
 */
export const storeEditorCategory = (
  id: number,
  editorStoreCategoryRequest: EditorStoreCategoryRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorCategoryResponse>> => {
  return axios.post(
    `/api/editor/menus/${id}/categories`,
    editorStoreCategoryRequest,
    options,
  );
};
export const getStoreEditorCategoryUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/menus/${id}/categories`,
      baseURL: "",
    });
};
/**
 * @summary Delete the category with its dishes (only from the archive).
 */
export const destroyEditorCategory = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<SuccessResponse>> => {
  return axios.delete(`/api/editor/categories/${id}`, options);
};
export const getDestroyEditorCategoryUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/categories/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Update texts and visibility of the category, and the order of its dishes.
 */
export const updateEditorCategory = (
  id: number,
  editorUpdateCategoryRequest: EditorUpdateCategoryRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorCategoryResponse>> => {
  return axios.patch(
    `/api/editor/categories/${id}`,
    editorUpdateCategoryRequest,
    options,
  );
};
export const getUpdateEditorCategoryUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/categories/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Move the category with its dishes to another menu.
 */
export const moveEditorCategory = (
  id: number,
  editorMoveCategoryRequest: EditorMoveCategoryRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorCategoryResponse>> => {
  return axios.post(
    `/api/editor/categories/${id}/move`,
    editorMoveCategoryRequest,
    options,
  );
};
export const getMoveEditorCategoryUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/categories/${id}/move`,
      baseURL: "",
    });
};
/**
 * @summary Move the category to the archive.
 */
export const archiveEditorCategory = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorCategoryResponse>> => {
  return axios.post(`/api/editor/categories/${id}/archive`, undefined, options);
};
export const getArchiveEditorCategoryUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/categories/${id}/archive`,
      baseURL: "",
    });
};
/**
 * @summary Restore the category from the archive.
 */
export const unarchiveEditorCategory = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorCategoryResponse>> => {
  return axios.post(
    `/api/editor/categories/${id}/unarchive`,
    undefined,
    options,
  );
};
export const getUnarchiveEditorCategoryUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/categories/${id}/unarchive`,
      baseURL: "",
    });
};
/**
 * @summary Copy the category with its dishes (the copy is hidden).
 */
export const duplicateEditorCategory = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorCategoryResponse>> => {
  return axios.post(
    `/api/editor/categories/${id}/duplicate`,
    undefined,
    options,
  );
};
export const getDuplicateEditorCategoryUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/categories/${id}/duplicate`,
      baseURL: "",
    });
};
/**
 * @summary Create a dish at the end of the category.
 */
export const storeEditorDish = (
  id: number,
  editorStoreDishRequest: EditorStoreDishRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorDishResponse>> => {
  return axios.post(
    `/api/editor/categories/${id}/dishes`,
    editorStoreDishRequest,
    options,
  );
};
export const getStoreEditorDishUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/categories/${id}/dishes`,
      baseURL: "",
    });
};
/**
 * @summary Delete the dish (only from the archive).
 */
export const destroyEditorDish = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<SuccessResponse>> => {
  return axios.delete(`/api/editor/dishes/${id}`, options);
};
export const getDestroyEditorDishUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/dishes/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Update the dish.
 */
export const updateEditorDish = (
  id: number,
  editorUpdateDishRequest: EditorUpdateDishRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorDishResponse>> => {
  return axios.patch(
    `/api/editor/dishes/${id}`,
    editorUpdateDishRequest,
    options,
  );
};
export const getUpdateEditorDishUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/dishes/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Move the dish to another category.
 */
export const moveEditorDish = (
  id: number,
  editorMoveDishRequest: EditorMoveDishRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorDishResponse>> => {
  return axios.post(
    `/api/editor/dishes/${id}/move`,
    editorMoveDishRequest,
    options,
  );
};
export const getMoveEditorDishUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/dishes/${id}/move`,
      baseURL: "",
    });
};
/**
 * @summary Move the dish to the archive.
 */
export const archiveEditorDish = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorDishResponse>> => {
  return axios.post(`/api/editor/dishes/${id}/archive`, undefined, options);
};
export const getArchiveEditorDishUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/dishes/${id}/archive`,
      baseURL: "",
    });
};
/**
 * @summary Restore the dish from the archive.
 */
export const unarchiveEditorDish = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorDishResponse>> => {
  return axios.post(`/api/editor/dishes/${id}/unarchive`, undefined, options);
};
export const getUnarchiveEditorDishUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/dishes/${id}/unarchive`,
      baseURL: "",
    });
};
/**
 * @summary Copy the dish with its sizes and photos (the copy is hidden).
 */
export const duplicateEditorDish = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorDishResponse>> => {
  return axios.post(`/api/editor/dishes/${id}/duplicate`, undefined, options);
};
export const getDuplicateEditorDishUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/dishes/${id}/duplicate`,
      baseURL: "",
    });
};
/**
 * @summary Create a menu at the end of the restaurant's menus.
 */
export const storeEditorMenu = (
  id: number,
  editorStoreMenuRequest: EditorStoreMenuRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorMenuResponse>> => {
  return axios.post(
    `/api/editor/restaurants/${id}/menus`,
    editorStoreMenuRequest,
    options,
  );
};
export const getStoreEditorMenuUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/restaurants/${id}/menus`,
      baseURL: "",
    });
};
/**
 * @summary Order menus and their categories.
 */
export const orderEditorMenus = (
  id: number,
  editorOrderMenusRequest: EditorOrderMenusRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorRestaurantResponse>> => {
  return axios.put(
    `/api/editor/restaurants/${id}/menus/order`,
    editorOrderMenusRequest,
    options,
  );
};
export const getOrderEditorMenusUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/restaurants/${id}/menus/order`,
      baseURL: "",
    });
};
/**
 * @summary Delete the menu with everything inside it (only from the archive).
 */
export const destroyEditorMenu = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<SuccessResponse>> => {
  return axios.delete(`/api/editor/menus/${id}`, options);
};
export const getDestroyEditorMenuUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/menus/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Update texts and visibility of the menu.
 */
export const updateEditorMenu = (
  id: number,
  editorUpdateMenuRequest: EditorUpdateMenuRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorMenuResponse>> => {
  return axios.patch(
    `/api/editor/menus/${id}`,
    editorUpdateMenuRequest,
    options,
  );
};
export const getUpdateEditorMenuUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/menus/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Move the menu to the archive.
 */
export const archiveEditorMenu = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorMenuResponse>> => {
  return axios.post(`/api/editor/menus/${id}/archive`, undefined, options);
};
export const getArchiveEditorMenuUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/menus/${id}/archive`,
      baseURL: "",
    });
};
/**
 * @summary Restore the menu from the archive.
 */
export const unarchiveEditorMenu = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorMenuResponse>> => {
  return axios.post(`/api/editor/menus/${id}/unarchive`, undefined, options);
};
export const getUnarchiveEditorMenuUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/menus/${id}/unarchive`,
      baseURL: "",
    });
};
/**
 * @summary Copy the menu with everything inside it (the copy is hidden).
 */
export const duplicateEditorMenu = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorMenuResponse>> => {
  return axios.post(`/api/editor/menus/${id}/duplicate`, undefined, options);
};
export const getDuplicateEditorMenuUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/menus/${id}/duplicate`,
      baseURL: "",
    });
};
/**
 * @summary Restaurants the user can edit.
 */
export const getEditorRestaurants = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorRestaurantsResponse>> => {
  return axios.get(`/api/editor/restaurants`, options);
};
export const getGetEditorRestaurantsUrl = () => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/restaurants`,
      baseURL: "",
    });
};
/**
 * @summary Everything of the restaurant, in all languages.
 */
export const getEditorRestaurant = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorRestaurantResponse>> => {
  return axios.get(`/api/editor/restaurants/${id}`, options);
};
export const getGetEditorRestaurantUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/restaurants/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Update details and brand colors of the restaurant.
 */
export const updateEditorRestaurant = (
  id: number,
  editorUpdateRestaurantRequest: EditorUpdateRestaurantRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorRestaurantResponse>> => {
  return axios.patch(
    `/api/editor/restaurants/${id}`,
    editorUpdateRestaurantRequest,
    options,
  );
};
export const getUpdateEditorRestaurantUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/restaurants/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Replace notes of the restaurant.
 */
export const updateEditorRestaurantNotes = (
  id: number,
  editorUpdateRestaurantNotesRequest: EditorUpdateRestaurantNotesRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorRestaurantResponse>> => {
  return axios.put(
    `/api/editor/restaurants/${id}/notes`,
    editorUpdateRestaurantNotesRequest,
    options,
  );
};
export const getUpdateEditorRestaurantNotesUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/restaurants/${id}/notes`,
      baseURL: "",
    });
};
/**
 * @summary Set photos of the restaurant.
 */
export const updateEditorRestaurantPhotos = (
  id: number,
  editorUpdateRestaurantPhotosRequest: EditorUpdateRestaurantPhotosRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorRestaurantResponse>> => {
  return axios.put(
    `/api/editor/restaurants/${id}/photos`,
    editorUpdateRestaurantPhotosRequest,
    options,
  );
};
export const getUpdateEditorRestaurantPhotosUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/restaurants/${id}/photos`,
      baseURL: "",
    });
};
/**
 * @summary Upload a photo of the restaurant, to be set as one of its or its dishes' photos.
 */
export const uploadEditorRestaurantPhoto = (
  id: number,
  editorUploadPhotoRequest: EditorUploadPhotoRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<StoreMediaResponse>> => {
  const formData = new FormData();
  formData.append(`file`, editorUploadPhotoRequest.file);

  return axios.post(`/api/editor/restaurants/${id}/media`, formData, options);
};
export const getUploadEditorRestaurantPhotoUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/restaurants/${id}/media`,
      baseURL: "",
    });
};
/**
 * @summary Replace hours, special days and closure of the restaurant.
 */
export const updateEditorRestaurantHours = (
  id: number,
  editorUpdateRestaurantHoursRequest: EditorUpdateRestaurantHoursRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorRestaurantResponse>> => {
  return axios.put(
    `/api/editor/restaurants/${id}/hours`,
    editorUpdateRestaurantHoursRequest,
    options,
  );
};
export const getUpdateEditorRestaurantHoursUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/restaurants/${id}/hours`,
      baseURL: "",
    });
};
export type StoreEditorCategoryResult = AxiosResponse<EditorCategoryResponse>;
export type DestroyEditorCategoryResult = AxiosResponse<SuccessResponse>;
export type UpdateEditorCategoryResult = AxiosResponse<EditorCategoryResponse>;
export type MoveEditorCategoryResult = AxiosResponse<EditorCategoryResponse>;
export type ArchiveEditorCategoryResult = AxiosResponse<EditorCategoryResponse>;
export type UnarchiveEditorCategoryResult =
  AxiosResponse<EditorCategoryResponse>;
export type DuplicateEditorCategoryResult =
  AxiosResponse<EditorCategoryResponse>;
export type StoreEditorDishResult = AxiosResponse<EditorDishResponse>;
export type DestroyEditorDishResult = AxiosResponse<SuccessResponse>;
export type UpdateEditorDishResult = AxiosResponse<EditorDishResponse>;
export type MoveEditorDishResult = AxiosResponse<EditorDishResponse>;
export type ArchiveEditorDishResult = AxiosResponse<EditorDishResponse>;
export type UnarchiveEditorDishResult = AxiosResponse<EditorDishResponse>;
export type DuplicateEditorDishResult = AxiosResponse<EditorDishResponse>;
export type StoreEditorMenuResult = AxiosResponse<EditorMenuResponse>;
export type OrderEditorMenusResult = AxiosResponse<EditorRestaurantResponse>;
export type DestroyEditorMenuResult = AxiosResponse<SuccessResponse>;
export type UpdateEditorMenuResult = AxiosResponse<EditorMenuResponse>;
export type ArchiveEditorMenuResult = AxiosResponse<EditorMenuResponse>;
export type UnarchiveEditorMenuResult = AxiosResponse<EditorMenuResponse>;
export type DuplicateEditorMenuResult = AxiosResponse<EditorMenuResponse>;
export type GetEditorRestaurantsResult =
  AxiosResponse<EditorRestaurantsResponse>;
export type GetEditorRestaurantResult = AxiosResponse<EditorRestaurantResponse>;
export type UpdateEditorRestaurantResult =
  AxiosResponse<EditorRestaurantResponse>;
export type UpdateEditorRestaurantNotesResult =
  AxiosResponse<EditorRestaurantResponse>;
export type UpdateEditorRestaurantPhotosResult =
  AxiosResponse<EditorRestaurantResponse>;
export type UploadEditorRestaurantPhotoResult =
  AxiosResponse<StoreMediaResponse>;
export type UpdateEditorRestaurantHoursResult =
  AxiosResponse<EditorRestaurantResponse>;
