/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  EditorCategoryResponse,
  EditorDashboardResponse,
  EditorDishResponse,
  EditorMenuResponse,
  EditorMoveCategoryRequest,
  EditorMoveDishRequest,
  EditorOrderMenusRequest,
  EditorPutVersionChangeRequest,
  EditorRestaurantResponse,
  EditorRestaurantsResponse,
  EditorReviewResponse,
  EditorReviewsResponse,
  EditorStoreCategoryRequest,
  EditorStoreDishRequest,
  EditorStoreMenuRequest,
  EditorStoreVersionRequest,
  EditorUpdateCategoryRequest,
  EditorUpdateDishRequest,
  EditorUpdateMenuRequest,
  EditorUpdateRestaurantHoursRequest,
  EditorUpdateRestaurantNotesRequest,
  EditorUpdateRestaurantPhotosRequest,
  EditorUpdateRestaurantRequest,
  EditorUpdateVersionRequest,
  EditorUploadPhotoRequest,
  EditorVersionResponse,
  EditorVersionsResponse,
  GetEditorReviewsParams,
  GetEditorVersionsParams,
  StoreMediaResponse,
  SuccessResponse,
} from "../models";

/**
 * @summary Create a category at the end of the menu.
 */
export const storeEditorCategory = (
  id: number,
  editorStoreCategoryRequest: EditorStoreCategoryRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorCategoryResponse>> => {
  return axios.post(
    `/api/editor/menus/${id}/categories`,
    editorStoreCategoryRequest,
    options,
  );
};
export const getStoreEditorCategoryUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/menus/${id}/categories`,
      baseURL: "",
    });
};
/**
 * @summary Delete the category with its dishes (only from the archive).
 */
export const destroyEditorCategory = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<SuccessResponse>> => {
  return axios.delete(`/api/editor/categories/${id}`, options);
};
export const getDestroyEditorCategoryUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/categories/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Update texts and visibility of the category, and the order of its dishes.
 */
export const updateEditorCategory = (
  id: number,
  editorUpdateCategoryRequest: EditorUpdateCategoryRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorCategoryResponse>> => {
  return axios.patch(
    `/api/editor/categories/${id}`,
    editorUpdateCategoryRequest,
    options,
  );
};
export const getUpdateEditorCategoryUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/categories/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Move the category with its dishes to another menu.
 */
export const moveEditorCategory = (
  id: number,
  editorMoveCategoryRequest: EditorMoveCategoryRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorCategoryResponse>> => {
  return axios.post(
    `/api/editor/categories/${id}/move`,
    editorMoveCategoryRequest,
    options,
  );
};
export const getMoveEditorCategoryUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/categories/${id}/move`,
      baseURL: "",
    });
};
/**
 * @summary Move the category to the archive.
 */
export const archiveEditorCategory = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorCategoryResponse>> => {
  return axios.post(`/api/editor/categories/${id}/archive`, undefined, options);
};
export const getArchiveEditorCategoryUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/categories/${id}/archive`,
      baseURL: "",
    });
};
/**
 * @summary Restore the category from the archive.
 */
export const unarchiveEditorCategory = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorCategoryResponse>> => {
  return axios.post(
    `/api/editor/categories/${id}/unarchive`,
    undefined,
    options,
  );
};
export const getUnarchiveEditorCategoryUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/categories/${id}/unarchive`,
      baseURL: "",
    });
};
/**
 * @summary Copy the category with its dishes (the copy is hidden).
 */
export const duplicateEditorCategory = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorCategoryResponse>> => {
  return axios.post(
    `/api/editor/categories/${id}/duplicate`,
    undefined,
    options,
  );
};
export const getDuplicateEditorCategoryUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/categories/${id}/duplicate`,
      baseURL: "",
    });
};
/**
 * @summary Create a dish at the end of the category.
 */
export const storeEditorDish = (
  id: number,
  editorStoreDishRequest: EditorStoreDishRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorDishResponse>> => {
  return axios.post(
    `/api/editor/categories/${id}/dishes`,
    editorStoreDishRequest,
    options,
  );
};
export const getStoreEditorDishUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/categories/${id}/dishes`,
      baseURL: "",
    });
};
/**
 * @summary Delete the dish (only from the archive).
 */
export const destroyEditorDish = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<SuccessResponse>> => {
  return axios.delete(`/api/editor/dishes/${id}`, options);
};
export const getDestroyEditorDishUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/dishes/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Update the dish.
 */
export const updateEditorDish = (
  id: number,
  editorUpdateDishRequest: EditorUpdateDishRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorDishResponse>> => {
  return axios.patch(
    `/api/editor/dishes/${id}`,
    editorUpdateDishRequest,
    options,
  );
};
export const getUpdateEditorDishUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/dishes/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Move the dish to another category.
 */
export const moveEditorDish = (
  id: number,
  editorMoveDishRequest: EditorMoveDishRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorDishResponse>> => {
  return axios.post(
    `/api/editor/dishes/${id}/move`,
    editorMoveDishRequest,
    options,
  );
};
export const getMoveEditorDishUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/dishes/${id}/move`,
      baseURL: "",
    });
};
/**
 * @summary Move the dish to the archive.
 */
export const archiveEditorDish = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorDishResponse>> => {
  return axios.post(`/api/editor/dishes/${id}/archive`, undefined, options);
};
export const getArchiveEditorDishUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/dishes/${id}/archive`,
      baseURL: "",
    });
};
/**
 * @summary Restore the dish from the archive.
 */
export const unarchiveEditorDish = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorDishResponse>> => {
  return axios.post(`/api/editor/dishes/${id}/unarchive`, undefined, options);
};
export const getUnarchiveEditorDishUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/dishes/${id}/unarchive`,
      baseURL: "",
    });
};
/**
 * @summary Copy the dish with its sizes and photos (the copy is hidden).
 */
export const duplicateEditorDish = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorDishResponse>> => {
  return axios.post(`/api/editor/dishes/${id}/duplicate`, undefined, options);
};
export const getDuplicateEditorDishUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/dishes/${id}/duplicate`,
      baseURL: "",
    });
};
/**
 * @summary Create a menu at the end of the restaurant's menus.
 */
export const storeEditorMenu = (
  id: number,
  editorStoreMenuRequest: EditorStoreMenuRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorMenuResponse>> => {
  return axios.post(
    `/api/editor/restaurants/${id}/menus`,
    editorStoreMenuRequest,
    options,
  );
};
export const getStoreEditorMenuUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/restaurants/${id}/menus`,
      baseURL: "",
    });
};
/**
 * @summary Order menus and their categories.
 */
export const orderEditorMenus = (
  id: number,
  editorOrderMenusRequest: EditorOrderMenusRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorRestaurantResponse>> => {
  return axios.put(
    `/api/editor/restaurants/${id}/menus/order`,
    editorOrderMenusRequest,
    options,
  );
};
export const getOrderEditorMenusUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/restaurants/${id}/menus/order`,
      baseURL: "",
    });
};
/**
 * @summary Delete the menu with everything inside it (only from the archive).
 */
export const destroyEditorMenu = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<SuccessResponse>> => {
  return axios.delete(`/api/editor/menus/${id}`, options);
};
export const getDestroyEditorMenuUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/menus/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Update texts and visibility of the menu.
 */
export const updateEditorMenu = (
  id: number,
  editorUpdateMenuRequest: EditorUpdateMenuRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorMenuResponse>> => {
  return axios.patch(
    `/api/editor/menus/${id}`,
    editorUpdateMenuRequest,
    options,
  );
};
export const getUpdateEditorMenuUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/menus/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Move the menu to the archive.
 */
export const archiveEditorMenu = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorMenuResponse>> => {
  return axios.post(`/api/editor/menus/${id}/archive`, undefined, options);
};
export const getArchiveEditorMenuUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/menus/${id}/archive`,
      baseURL: "",
    });
};
/**
 * @summary Restore the menu from the archive.
 */
export const unarchiveEditorMenu = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorMenuResponse>> => {
  return axios.post(`/api/editor/menus/${id}/unarchive`, undefined, options);
};
export const getUnarchiveEditorMenuUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/menus/${id}/unarchive`,
      baseURL: "",
    });
};
/**
 * @summary Copy the menu with everything inside it (the copy is hidden).
 */
export const duplicateEditorMenu = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorMenuResponse>> => {
  return axios.post(`/api/editor/menus/${id}/duplicate`, undefined, options);
};
export const getDuplicateEditorMenuUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/menus/${id}/duplicate`,
      baseURL: "",
    });
};
/**
 * @summary Restaurants the user can edit.
 */
export const getEditorRestaurants = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorRestaurantsResponse>> => {
  return axios.get(`/api/editor/restaurants`, options);
};
export const getGetEditorRestaurantsUrl = () => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/restaurants`,
      baseURL: "",
    });
};
/**
 * @summary Everything of the restaurant, in all languages.
 */
export const getEditorRestaurant = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorRestaurantResponse>> => {
  return axios.get(`/api/editor/restaurants/${id}`, options);
};
export const getGetEditorRestaurantUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/restaurants/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Update details and brand colors of the restaurant.
 */
export const updateEditorRestaurant = (
  id: number,
  editorUpdateRestaurantRequest: EditorUpdateRestaurantRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorRestaurantResponse>> => {
  return axios.patch(
    `/api/editor/restaurants/${id}`,
    editorUpdateRestaurantRequest,
    options,
  );
};
export const getUpdateEditorRestaurantUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/restaurants/${id}`,
      baseURL: "",
    });
};
/**
 * @summary What the admin's dashboard shows of the restaurant.
 */
export const getEditorDashboard = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorDashboardResponse>> => {
  return axios.get(`/api/editor/restaurants/${id}/dashboard`, options);
};
export const getGetEditorDashboardUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/restaurants/${id}/dashboard`,
      baseURL: "",
    });
};
/**
 * @summary Replace notes of the restaurant.
 */
export const updateEditorRestaurantNotes = (
  id: number,
  editorUpdateRestaurantNotesRequest: EditorUpdateRestaurantNotesRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorRestaurantResponse>> => {
  return axios.put(
    `/api/editor/restaurants/${id}/notes`,
    editorUpdateRestaurantNotesRequest,
    options,
  );
};
export const getUpdateEditorRestaurantNotesUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/restaurants/${id}/notes`,
      baseURL: "",
    });
};
/**
 * @summary Set photos of the restaurant.
 */
export const updateEditorRestaurantPhotos = (
  id: number,
  editorUpdateRestaurantPhotosRequest: EditorUpdateRestaurantPhotosRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorRestaurantResponse>> => {
  return axios.put(
    `/api/editor/restaurants/${id}/photos`,
    editorUpdateRestaurantPhotosRequest,
    options,
  );
};
export const getUpdateEditorRestaurantPhotosUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/restaurants/${id}/photos`,
      baseURL: "",
    });
};
/**
 * @summary Upload a photo of the restaurant, to be set as one of its or its dishes' photos.
 */
export const uploadEditorRestaurantPhoto = (
  id: number,
  editorUploadPhotoRequest: EditorUploadPhotoRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<StoreMediaResponse>> => {
  const formData = new FormData();
  formData.append(`file`, editorUploadPhotoRequest.file);

  return axios.post(`/api/editor/restaurants/${id}/media`, formData, options);
};
export const getUploadEditorRestaurantPhotoUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/restaurants/${id}/media`,
      baseURL: "",
    });
};
/**
 * @summary Replace hours, special days and closure of the restaurant.
 */
export const updateEditorRestaurantHours = (
  id: number,
  editorUpdateRestaurantHoursRequest: EditorUpdateRestaurantHoursRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorRestaurantResponse>> => {
  return axios.put(
    `/api/editor/restaurants/${id}/hours`,
    editorUpdateRestaurantHoursRequest,
    options,
  );
};
export const getUpdateEditorRestaurantHoursUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/restaurants/${id}/hours`,
      baseURL: "",
    });
};
/**
 * @summary A page of the restaurant's reviews with the status, and how many have each status.
 */
export const getEditorReviews = (
  id: number,
  params?: GetEditorReviewsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorReviewsResponse>> => {
  return axios.get(`/api/editor/restaurants/${id}/reviews`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getGetEditorReviewsUrl = (
  id: number,
  params?: GetEditorReviewsParams,
) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/restaurants/${id}/reviews`,
      baseURL: "",
      params,
    });
};
/**
 * @summary Approve the review: it's public.
 */
export const approveEditorReview = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorReviewResponse>> => {
  return axios.post(`/api/editor/reviews/${id}/approve`, undefined, options);
};
export const getApproveEditorReviewUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/reviews/${id}/approve`,
      baseURL: "",
    });
};
/**
 * @summary Reject the review: it's never public.
 */
export const rejectEditorReview = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorReviewResponse>> => {
  return axios.post(`/api/editor/reviews/${id}/reject`, undefined, options);
};
export const getRejectEditorReviewUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/reviews/${id}/reject`,
      baseURL: "",
    });
};
/**
 * @summary Versions of the restaurant: pending ones by their date, then the ones, which went live.
 */
export const getEditorVersions = (
  id: number,
  params?: GetEditorVersionsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorVersionsResponse>> => {
  return axios.get(`/api/editor/restaurants/${id}/versions`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getGetEditorVersionsUrl = (
  id: number,
  params?: GetEditorVersionsParams,
) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/restaurants/${id}/versions`,
      baseURL: "",
      params,
    });
};
/**
 * @summary Create a version: a draft, or scheduled right away, with its first changes.
 */
export const storeEditorVersion = (
  id: number,
  editorStoreVersionRequest: EditorStoreVersionRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorVersionResponse>> => {
  return axios.post(
    `/api/editor/restaurants/${id}/versions`,
    editorStoreVersionRequest,
    options,
  );
};
export const getStoreEditorVersionUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/restaurants/${id}/versions`,
      baseURL: "",
    });
};
/**
 * @summary The version with its changes, their items and conflicts.
 */
export const getEditorVersion = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorVersionResponse>> => {
  return axios.get(`/api/editor/versions/${id}`, options);
};
export const getGetEditorVersionUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/versions/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Delete the version with its changes.
 */
export const deleteEditorVersion = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.delete(`/api/editor/versions/${id}`, options);
};
export const getDeleteEditorVersionUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/versions/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Rename or reschedule the version.
 */
export const updateEditorVersion = (
  id: number,
  editorUpdateVersionRequest: EditorUpdateVersionRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorVersionResponse>> => {
  return axios.patch(
    `/api/editor/versions/${id}`,
    editorUpdateVersionRequest,
    options,
  );
};
export const getUpdateEditorVersionUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/versions/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Put a change of an item (or a new one) into the version.
 */
export const putEditorVersionChange = (
  id: number,
  editorPutVersionChangeRequest: EditorPutVersionChangeRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorVersionResponse>> => {
  return axios.put(
    `/api/editor/versions/${id}/changes`,
    editorPutVersionChangeRequest,
    options,
  );
};
export const getPutEditorVersionChangeUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/versions/${id}/changes`,
      baseURL: "",
    });
};
/**
 * @summary Remove a change from the version: the item stays as it is.
 */
export const removeEditorVersionChange = (
  id: number,
  change: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorVersionResponse>> => {
  return axios.delete(`/api/editor/versions/${id}/changes/${change}`, options);
};
export const getRemoveEditorVersionChangeUrl = (id: number, change: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/versions/${id}/changes/${change}`,
      baseURL: "",
    });
};
/**
 * @summary Schedule the version at its date, which has to be in the future.
 */
export const scheduleEditorVersion = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorVersionResponse>> => {
  return axios.post(`/api/editor/versions/${id}/schedule`, undefined, options);
};
export const getScheduleEditorVersionUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/versions/${id}/schedule`,
      baseURL: "",
    });
};
/**
 * @summary Deactivate the scheduled version: it keeps its date, but doesn't go live.
 */
export const deactivateEditorVersion = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorVersionResponse>> => {
  return axios.post(
    `/api/editor/versions/${id}/deactivate`,
    undefined,
    options,
  );
};
export const getDeactivateEditorVersionUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/versions/${id}/deactivate`,
      baseURL: "",
    });
};
/**
 * @summary Activate the inactive version: it's scheduled again.
 */
export const activateEditorVersion = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorVersionResponse>> => {
  return axios.post(`/api/editor/versions/${id}/activate`, undefined, options);
};
export const getActivateEditorVersionUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/versions/${id}/activate`,
      baseURL: "",
    });
};
/**
 * @summary Apply the version now: all of its changes, or none (then it's failed, with the reason).
 */
export const applyEditorVersion = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorVersionResponse>> => {
  return axios.post(`/api/editor/versions/${id}/apply`, undefined, options);
};
export const getApplyEditorVersionUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/versions/${id}/apply`,
      baseURL: "",
    });
};
/**
 * @summary Copy the version as a draft with the same date and changes.
 */
export const duplicateEditorVersion = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<EditorVersionResponse>> => {
  return axios.post(`/api/editor/versions/${id}/duplicate`, undefined, options);
};
export const getDuplicateEditorVersionUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/editor/versions/${id}/duplicate`,
      baseURL: "",
    });
};
export type StoreEditorCategoryResult = AxiosResponse<EditorCategoryResponse>;
export type DestroyEditorCategoryResult = AxiosResponse<SuccessResponse>;
export type UpdateEditorCategoryResult = AxiosResponse<EditorCategoryResponse>;
export type MoveEditorCategoryResult = AxiosResponse<EditorCategoryResponse>;
export type ArchiveEditorCategoryResult = AxiosResponse<EditorCategoryResponse>;
export type UnarchiveEditorCategoryResult =
  AxiosResponse<EditorCategoryResponse>;
export type DuplicateEditorCategoryResult =
  AxiosResponse<EditorCategoryResponse>;
export type StoreEditorDishResult = AxiosResponse<EditorDishResponse>;
export type DestroyEditorDishResult = AxiosResponse<SuccessResponse>;
export type UpdateEditorDishResult = AxiosResponse<EditorDishResponse>;
export type MoveEditorDishResult = AxiosResponse<EditorDishResponse>;
export type ArchiveEditorDishResult = AxiosResponse<EditorDishResponse>;
export type UnarchiveEditorDishResult = AxiosResponse<EditorDishResponse>;
export type DuplicateEditorDishResult = AxiosResponse<EditorDishResponse>;
export type StoreEditorMenuResult = AxiosResponse<EditorMenuResponse>;
export type OrderEditorMenusResult = AxiosResponse<EditorRestaurantResponse>;
export type DestroyEditorMenuResult = AxiosResponse<SuccessResponse>;
export type UpdateEditorMenuResult = AxiosResponse<EditorMenuResponse>;
export type ArchiveEditorMenuResult = AxiosResponse<EditorMenuResponse>;
export type UnarchiveEditorMenuResult = AxiosResponse<EditorMenuResponse>;
export type DuplicateEditorMenuResult = AxiosResponse<EditorMenuResponse>;
export type GetEditorRestaurantsResult =
  AxiosResponse<EditorRestaurantsResponse>;
export type GetEditorRestaurantResult = AxiosResponse<EditorRestaurantResponse>;
export type UpdateEditorRestaurantResult =
  AxiosResponse<EditorRestaurantResponse>;
export type GetEditorDashboardResult = AxiosResponse<EditorDashboardResponse>;
export type UpdateEditorRestaurantNotesResult =
  AxiosResponse<EditorRestaurantResponse>;
export type UpdateEditorRestaurantPhotosResult =
  AxiosResponse<EditorRestaurantResponse>;
export type UploadEditorRestaurantPhotoResult =
  AxiosResponse<StoreMediaResponse>;
export type UpdateEditorRestaurantHoursResult =
  AxiosResponse<EditorRestaurantResponse>;
export type GetEditorReviewsResult = AxiosResponse<EditorReviewsResponse>;
export type ApproveEditorReviewResult = AxiosResponse<EditorReviewResponse>;
export type RejectEditorReviewResult = AxiosResponse<EditorReviewResponse>;
export type GetEditorVersionsResult = AxiosResponse<EditorVersionsResponse>;
export type StoreEditorVersionResult = AxiosResponse<EditorVersionResponse>;
export type GetEditorVersionResult = AxiosResponse<EditorVersionResponse>;
export type DeleteEditorVersionResult = AxiosResponse<void>;
export type UpdateEditorVersionResult = AxiosResponse<EditorVersionResponse>;
export type PutEditorVersionChangeResult = AxiosResponse<EditorVersionResponse>;
export type RemoveEditorVersionChangeResult =
  AxiosResponse<EditorVersionResponse>;
export type ScheduleEditorVersionResult = AxiosResponse<EditorVersionResponse>;
export type DeactivateEditorVersionResult =
  AxiosResponse<EditorVersionResponse>;
export type ActivateEditorVersionResult = AxiosResponse<EditorVersionResponse>;
export type ApplyEditorVersionResult = AxiosResponse<EditorVersionResponse>;
export type DuplicateEditorVersionResult = AxiosResponse<EditorVersionResponse>;
