/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  DestroyFamilyMemberResponse,
  IndexFamilyMemberResponse,
  IndexFamilyMembersParams,
  ShowFamilyMemberParams,
  ShowFamilyMemberResponse,
  StoreFamilyMemberRequest,
  StoreFamilyMemberResponse,
  UpdateFamilyMemberRequest,
  UpdateFamilyMemberResponse,
} from "../models";

/**
 * @summary Index family members.
 */
export const indexFamilyMembers = <
  TData = AxiosResponse<IndexFamilyMemberResponse>,
>(
  params?: IndexFamilyMembersParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/family-members`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
/**
 * @summary Store family member.
 */
export const storeFamilyMember = <
  TData = AxiosResponse<StoreFamilyMemberResponse>,
>(
  storeFamilyMemberRequest: StoreFamilyMemberRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/api/family-members`, storeFamilyMemberRequest, options);
};
/**
 * @summary Show family member by id.
 */
export const showFamilyMember = <
  TData = AxiosResponse<ShowFamilyMemberResponse>,
>(
  id: number,
  params?: ShowFamilyMemberParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/family-members/${id}`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
/**
 * @summary Delete family member.
 */
export const destroyFamilyMember = <
  TData = AxiosResponse<DestroyFamilyMemberResponse>,
>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.delete(`/api/family-members/${id}`, options);
};
/**
 * @summary Update family member.
 */
export const updateFamilyMember = <
  TData = AxiosResponse<UpdateFamilyMemberResponse>,
>(
  id: number,
  updateFamilyMemberRequest: UpdateFamilyMemberRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.patch(
    `/api/family-members/${id}`,
    updateFamilyMemberRequest,
    options,
  );
};
export type IndexFamilyMembersResult = AxiosResponse<IndexFamilyMemberResponse>;
export type StoreFamilyMemberResult = AxiosResponse<StoreFamilyMemberResponse>;
export type ShowFamilyMemberResult = AxiosResponse<ShowFamilyMemberResponse>;
export type DestroyFamilyMemberResult =
  AxiosResponse<DestroyFamilyMemberResponse>;
export type UpdateFamilyMemberResult =
  AxiosResponse<UpdateFamilyMemberResponse>;
