/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  DestroyMediaResponse,
  DestroyRequest,
  GetModelMediaParams,
  GetModelMediaResponse,
  IndexMediaParams,
  IndexMediaResponse,
  SetModelMediaRequest,
  SetModelMediaResponse,
  ShowMediaParams,
  ShowMediaResponse,
  StoreMediaBody,
  StoreMediaResponse,
  UpdateMediaRequest,
  UpdateMediaResponse,
} from "../models";

/**
 * @summary Index media.
 */
export const indexMedia = (
  params?: IndexMediaParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<IndexMediaResponse>> => {
  return axios.get(`/api/media`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getIndexMediaUrl = (params?: IndexMediaParams) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/media`,
      baseURL: "",
      params,
    });
};
/**
 * @summary Store media.
 */
export const storeMedia = (
  storeMediaBody: StoreMediaBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<StoreMediaResponse>> => {
  const formData = new FormData();
  formData.append(`file`, storeMediaBody.file);
  formData.append(`name`, storeMediaBody.name);
  if (storeMediaBody.title !== undefined && storeMediaBody.title !== null) {
    formData.append(`title`, storeMediaBody.title);
  }
  if (
    storeMediaBody.description !== undefined &&
    storeMediaBody.description !== null
  ) {
    formData.append(`description`, storeMediaBody.description);
  }
  if (storeMediaBody.disk !== undefined) {
    formData.append(`disk`, storeMediaBody.disk);
  }
  if (storeMediaBody.folder !== undefined) {
    formData.append(`folder`, storeMediaBody.folder);
  }
  if (
    storeMediaBody.metadata !== undefined &&
    storeMediaBody.metadata !== null
  ) {
    formData.append(`metadata`, JSON.stringify(storeMediaBody.metadata));
  }

  if (storeMediaBody.file !== undefined) {
    formData.append(`file`, storeMediaBody.file);
  }

  return axios.post(`/api/media`, formData, options);
};
export const getStoreMediaUrl = () => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/media`,
      baseURL: "",
    });
};
/**
 * @summary Show media by id.
 */
export const showMedia = (
  id: number,
  params?: ShowMediaParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ShowMediaResponse>> => {
  return axios.get(`/api/media/${id}`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getShowMediaUrl = (id: number, params?: ShowMediaParams) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/media/${id}`,
      baseURL: "",
      params,
    });
};
/**
 * @summary Delete media.
 */
export const destroyMedia = (
  id: number,
  destroyRequest?: DestroyRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<DestroyMediaResponse>> => {
  return axios.delete(`/api/media/${id}`, { data: destroyRequest, ...options });
};
export const getDestroyMediaUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/media/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Update media.
 */
export const updateMedia = (
  id: number,
  updateMediaRequest: UpdateMediaRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<UpdateMediaResponse>> => {
  return axios.patch(`/api/media/${id}`, updateMediaRequest, options);
};
export const getUpdateMediaUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/media/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Get model's media.
 */
export const getModelMedia = (
  params: GetModelMediaParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetModelMediaResponse>> => {
  return axios.get(`/api/model-media`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getGetModelMediaUrl = (params: GetModelMediaParams) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/model-media`,
      baseURL: "",
      params,
    });
};
/**
 * @summary Set model's media.
 */
export const setModelMedia = (
  setModelMediaRequest?: SetModelMediaRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<SetModelMediaResponse>> => {
  return axios.post(`/api/model-media`, setModelMediaRequest, options);
};
export const getSetModelMediaUrl = () => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/model-media`,
      baseURL: "",
    });
};
export type IndexMediaResult = AxiosResponse<IndexMediaResponse>;
export type StoreMediaResult = AxiosResponse<StoreMediaResponse>;
export type ShowMediaResult = AxiosResponse<ShowMediaResponse>;
export type DestroyMediaResult = AxiosResponse<DestroyMediaResponse>;
export type UpdateMediaResult = AxiosResponse<UpdateMediaResponse>;
export type GetModelMediaResult = AxiosResponse<GetModelMediaResponse>;
export type SetModelMediaResult = AxiosResponse<SetModelMediaResponse>;
