/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  AttachCategoryToMenuRequest,
  AttachCategoryToMenuResponse,
  AttachProductToMenuRequest,
  AttachProductToMenuResponse,
  DetachCategoryFromMenuRequest,
  DetachCategoryFromMenuResponse,
  DetachProductFromMenuRequest,
  DetachProductFromMenuResponse,
  IndexMenuResponse,
  IndexMenusParams,
  ShowMenuParams,
  ShowMenuResponse,
} from "../models";

/**
 * @summary Index menus.
 */
export const indexMenus = (
  params?: IndexMenusParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<IndexMenuResponse>> => {
  return axios.get(`/api/menus`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getIndexMenusUrl = (params?: IndexMenusParams) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/menus`,
      baseURL: "",
      params,
    });
};
/**
 * @summary Show menus by id.
 */
export const showMenu = (
  id: number,
  params?: ShowMenuParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ShowMenuResponse>> => {
  return axios.get(`/api/menus/${id}`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getShowMenuUrl = (id: number, params?: ShowMenuParams) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/menus/${id}`,
      baseURL: "",
      params,
    });
};
/**
 * @summary Attach category to menu.
 */
export const attachCategoryToMenu = (
  attachCategoryToMenuRequest: AttachCategoryToMenuRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<AttachCategoryToMenuResponse>> => {
  return axios.post(
    `/api/menus/attach-category`,
    attachCategoryToMenuRequest,
    options,
  );
};
export const getAttachCategoryToMenuUrl = () => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/menus/attach-category`,
      baseURL: "",
    });
};
/**
 * @summary Detach category from menu.
 */
export const detachCategoryFromMenu = (
  detachCategoryFromMenuRequest: DetachCategoryFromMenuRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<DetachCategoryFromMenuResponse>> => {
  return axios.delete(`/api/menus/detach-category`, {
    data: detachCategoryFromMenuRequest,
    ...options,
  });
};
export const getDetachCategoryFromMenuUrl = () => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/menus/detach-category`,
      baseURL: "",
    });
};
/**
 * @summary Attach product to menu.
 */
export const attachProductToMenu = (
  attachProductToMenuRequest: AttachProductToMenuRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<AttachProductToMenuResponse>> => {
  return axios.post(
    `/api/menus/attach-product`,
    attachProductToMenuRequest,
    options,
  );
};
export const getAttachProductToMenuUrl = () => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/menus/attach-product`,
      baseURL: "",
    });
};
/**
 * @summary Detach product from menu.
 */
export const detachProductFromMenu = (
  detachProductFromMenuRequest: DetachProductFromMenuRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<DetachProductFromMenuResponse>> => {
  return axios.delete(`/api/menus/detach-product`, {
    data: detachProductFromMenuRequest,
    ...options,
  });
};
export const getDetachProductFromMenuUrl = () => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/menus/detach-product`,
      baseURL: "",
    });
};
export type IndexMenusResult = AxiosResponse<IndexMenuResponse>;
export type ShowMenuResult = AxiosResponse<ShowMenuResponse>;
export type AttachCategoryToMenuResult =
  AxiosResponse<AttachCategoryToMenuResponse>;
export type DetachCategoryFromMenuResult =
  AxiosResponse<DetachCategoryFromMenuResponse>;
export type AttachProductToMenuResult =
  AxiosResponse<AttachProductToMenuResponse>;
export type DetachProductFromMenuResult =
  AxiosResponse<DetachProductFromMenuResponse>;
