/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  AttachCategoryToMenuRequest,
  AttachCategoryToMenuResponse,
  AttachProductToMenuRequest,
  AttachProductToMenuResponse,
  DetachCategoryFromMenuRequest,
  DetachCategoryFromMenuResponse,
  DetachProductFromMenuRequest,
  DetachProductFromMenuResponse,
  IndexMenuResponse,
  IndexMenusParams,
  ShowMenuParams,
  ShowMenuResponse,
} from "../models";

/**
 * @summary Index menus.
 */
export const indexMenus = <TData = AxiosResponse<IndexMenuResponse>>(
  params?: IndexMenusParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/menus`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
/**
 * @summary Show menus by id.
 */
export const showMenu = <TData = AxiosResponse<ShowMenuResponse>>(
  id: number,
  params?: ShowMenuParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/menus/${id}`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
/**
 * @summary Attach category to menu.
 */
export const attachCategoryToMenu = <
  TData = AxiosResponse<AttachCategoryToMenuResponse>,
>(
  attachCategoryToMenuRequest: AttachCategoryToMenuRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(
    `/api/menus/attach-category`,
    attachCategoryToMenuRequest,
    options,
  );
};
/**
 * @summary Detach category from menu.
 */
export const detachCategoryFromMenu = <
  TData = AxiosResponse<DetachCategoryFromMenuResponse>,
>(
  detachCategoryFromMenuRequest: DetachCategoryFromMenuRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.delete(`/api/menus/detach-category`, {
    data: detachCategoryFromMenuRequest,
    ...options,
  });
};
/**
 * @summary Attach product to menu.
 */
export const attachProductToMenu = <
  TData = AxiosResponse<AttachProductToMenuResponse>,
>(
  attachProductToMenuRequest: AttachProductToMenuRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(
    `/api/menus/attach-product`,
    attachProductToMenuRequest,
    options,
  );
};
/**
 * @summary Detach product from menu.
 */
export const detachProductFromMenu = <
  TData = AxiosResponse<DetachProductFromMenuResponse>,
>(
  detachProductFromMenuRequest: DetachProductFromMenuRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.delete(`/api/menus/detach-product`, {
    data: detachProductFromMenuRequest,
    ...options,
  });
};
export type IndexMenusResult = AxiosResponse<IndexMenuResponse>;
export type ShowMenuResult = AxiosResponse<ShowMenuResponse>;
export type AttachCategoryToMenuResult =
  AxiosResponse<AttachCategoryToMenuResponse>;
export type DetachCategoryFromMenuResult =
  AxiosResponse<DetachCategoryFromMenuResponse>;
export type AttachProductToMenuResult =
  AxiosResponse<AttachProductToMenuResponse>;
export type DetachProductFromMenuResult =
  AxiosResponse<DetachProductFromMenuResponse>;
