/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  DestroyNotificationResponse,
  DestroyRequest,
  IndexNotificationResponse,
  IndexNotificationsParams,
  PollNotificationsParams,
  PollNotificationsResponse,
  ShowNotificationResponse,
  StoreNotificationRequest,
  StoreNotificationResponse,
  UpdateNotificationRequest,
  UpdateNotificationResponse,
} from "../models";

/**
 * @summary Index notifications.
 */
export const indexNotifications = (
  params?: IndexNotificationsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<IndexNotificationResponse>> => {
  return axios.get(`/api/notifications`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getIndexNotificationsUrl = (params?: IndexNotificationsParams) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/notifications`,
      baseURL: "",
      params,
    });
};
/**
 * @summary Store notification.
 */
export const storeNotification = (
  storeNotificationRequest: StoreNotificationRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<StoreNotificationResponse>> => {
  return axios.post(`/api/notifications`, storeNotificationRequest, options);
};
export const getStoreNotificationUrl = () => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/notifications`,
      baseURL: "",
    });
};
/**
 * @summary Show notification by id.
 */
export const showNotification = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ShowNotificationResponse>> => {
  return axios.get(`/api/notifications/${id}`, options);
};
export const getShowNotificationUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/notifications/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Delete notification.
 */
export const destroyNotification = (
  id: number,
  destroyRequest?: DestroyRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<DestroyNotificationResponse>> => {
  return axios.delete(`/api/notifications/${id}`, {
    data: destroyRequest,
    ...options,
  });
};
export const getDestroyNotificationUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/notifications/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Update notification.
 */
export const updateNotification = (
  id: number,
  updateNotificationRequest: UpdateNotificationRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<UpdateNotificationResponse>> => {
  return axios.patch(
    `/api/notifications/${id}`,
    updateNotificationRequest,
    options,
  );
};
export const getUpdateNotificationUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/notifications/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Poll notifications.
 */
export const pollNotifications = (
  params?: PollNotificationsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<PollNotificationsResponse>> => {
  return axios.get(`/api/notifications/poll`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getPollNotificationsUrl = (params?: PollNotificationsParams) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/notifications/poll`,
      baseURL: "",
      params,
    });
};
export type IndexNotificationsResult = AxiosResponse<IndexNotificationResponse>;
export type StoreNotificationResult = AxiosResponse<StoreNotificationResponse>;
export type ShowNotificationResult = AxiosResponse<ShowNotificationResponse>;
export type DestroyNotificationResult =
  AxiosResponse<DestroyNotificationResponse>;
export type UpdateNotificationResult =
  AxiosResponse<UpdateNotificationResponse>;
export type PollNotificationsResult = AxiosResponse<PollNotificationsResponse>;
