/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  DestroyProductResponse,
  DestroyRequest,
  IndexProductResponse,
  IndexProductsParams,
  RestoreProductResponse,
  ShowProductParams,
  ShowProductResponse,
  StoreProductRequest,
  StoreProductResponse,
  UpdateProductRequest,
  UpdateProductResponse,
} from "../models";

/**
 * @summary Index products.
 */
export const indexProducts = (
  params?: IndexProductsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<IndexProductResponse>> => {
  return axios.get(`/api/products`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getIndexProductsUrl = (params?: IndexProductsParams) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/products`,
      baseURL: "",
      params,
    });
};
/**
 * @summary Store product.
 */
export const storeProduct = (
  storeProductRequest: StoreProductRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<StoreProductResponse>> => {
  return axios.post(`/api/products`, storeProductRequest, options);
};
export const getStoreProductUrl = () => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/products`,
      baseURL: "",
    });
};
/**
 * @summary Show product by id.
 */
export const showProduct = (
  id: number,
  params?: ShowProductParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ShowProductResponse>> => {
  return axios.get(`/api/products/${id}`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getShowProductUrl = (id: number, params?: ShowProductParams) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/products/${id}`,
      baseURL: "",
      params,
    });
};
/**
 * @summary Delete product.
 */
export const destroyProduct = (
  id: number,
  destroyRequest?: DestroyRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<DestroyProductResponse>> => {
  return axios.delete(`/api/products/${id}`, {
    data: destroyRequest,
    ...options,
  });
};
export const getDestroyProductUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/products/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Update product.
 */
export const updateProduct = (
  id: number,
  updateProductRequest: UpdateProductRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<UpdateProductResponse>> => {
  return axios.patch(`/api/products/${id}`, updateProductRequest, options);
};
export const getUpdateProductUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/products/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Restore product.
 */
export const restoreProduct = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<RestoreProductResponse>> => {
  return axios.post(`/api/products/${id}/restore`, undefined, options);
};
export const getRestoreProductUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/products/${id}/restore`,
      baseURL: "",
    });
};
export type IndexProductsResult = AxiosResponse<IndexProductResponse>;
export type StoreProductResult = AxiosResponse<StoreProductResponse>;
export type ShowProductResult = AxiosResponse<ShowProductResponse>;
export type DestroyProductResult = AxiosResponse<DestroyProductResponse>;
export type UpdateProductResult = AxiosResponse<UpdateProductResponse>;
export type RestoreProductResult = AxiosResponse<RestoreProductResponse>;
