/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  GetHolidaysParams,
  GetHolidaysResponse,
  GetSchedulesResponse,
  IndexRestaurantResponse,
  IndexRestaurantsParams,
  ShowRestaurantParams,
  ShowRestaurantResponse,
  UpdateRestaurantParams,
  UpdateRestaurantRequest,
  UpdateRestaurantResponse,
} from "../models";

/**
 * @summary Index restaurants.
 */
export const indexRestaurants = (
  params?: IndexRestaurantsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<IndexRestaurantResponse>> => {
  return axios.get(`/api/restaurants`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getIndexRestaurantsUrl = (params?: IndexRestaurantsParams) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/restaurants`,
      baseURL: "",
      params,
    });
};
/**
 * @summary Show restaurant by id.
 */
export const showRestaurant = (
  id: number,
  params?: ShowRestaurantParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ShowRestaurantResponse>> => {
  return axios.get(`/api/restaurants/${id}`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getShowRestaurantUrl = (
  id: number,
  params?: ShowRestaurantParams,
) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/restaurants/${id}`,
      baseURL: "",
      params,
    });
};
/**
 * @summary Update restaurant.
 */
export const updateRestaurant = (
  id: number,
  updateRestaurantRequest: UpdateRestaurantRequest,
  params?: UpdateRestaurantParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<UpdateRestaurantResponse>> => {
  return axios.patch(`/api/restaurants/${id}`, updateRestaurantRequest, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getUpdateRestaurantUrl = (
  id: number,
  params?: UpdateRestaurantParams,
) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/restaurants/${id}`,
      baseURL: "",
      params,
    });
};
/**
 * @summary Get restaurant's schedules.
 */
export const getSchedules = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetSchedulesResponse>> => {
  return axios.get(`/api/restaurants/${id}/schedules`, options);
};
export const getGetSchedulesUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/restaurants/${id}/schedules`,
      baseURL: "",
    });
};
/**
 * @summary Get restaurant's holidays.
 */
export const getHolidays = (
  id: number,
  params?: GetHolidaysParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetHolidaysResponse>> => {
  return axios.get(`/api/restaurants/${id}/holidays`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getGetHolidaysUrl = (id: number, params?: GetHolidaysParams) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/restaurants/${id}/holidays`,
      baseURL: "",
      params,
    });
};
export type IndexRestaurantsResult = AxiosResponse<IndexRestaurantResponse>;
export type ShowRestaurantResult = AxiosResponse<ShowRestaurantResponse>;
export type UpdateRestaurantResult = AxiosResponse<UpdateRestaurantResponse>;
export type GetSchedulesResult = AxiosResponse<GetSchedulesResponse>;
export type GetHolidaysResult = AxiosResponse<GetHolidaysResponse>;
