/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  IndexRestaurantReviewResponse,
  IndexRestaurantReviewsParams,
  ShowRestaurantReviewResponse,
  StoreRestaurantReviewRequest,
  StoreRestaurantReviewResponse,
} from "../models";

/**
 * @summary Index restaurant reviews.
 */
export const indexRestaurantReviews = <
  TData = AxiosResponse<IndexRestaurantReviewResponse>,
>(
  params?: IndexRestaurantReviewsParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/restaurant-reviews`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
/**
 * @summary Store banquet.
 */
export const storeRestaurantReview = <
  TData = AxiosResponse<StoreRestaurantReviewResponse>,
>(
  storeRestaurantReviewRequest: StoreRestaurantReviewRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(
    `/api/restaurant-reviews`,
    storeRestaurantReviewRequest,
    options,
  );
};
/**
 * @summary Show restaurant reviews by id.
 */
export const showRestaurantReview = <
  TData = AxiosResponse<ShowRestaurantReviewResponse>,
>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/restaurant-reviews/${id}`, options);
};
export type IndexRestaurantReviewsResult =
  AxiosResponse<IndexRestaurantReviewResponse>;
export type StoreRestaurantReviewResult =
  AxiosResponse<StoreRestaurantReviewResponse>;
export type ShowRestaurantReviewResult =
  AxiosResponse<ShowRestaurantReviewResponse>;
