/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  GetRestaurantReviewsParams,
  MyRestaurantReviewsRequest,
  MyRestaurantReviewsResponse,
  RestaurantReviewResponse,
  RestaurantReviewsResponse,
  StoreRestaurantReviewRequest,
} from "../models";

/**
 * @summary A page of the restaurant's approved reviews, with their summary.
 */
export const getRestaurantReviews = (
  id: string,
  params?: GetRestaurantReviewsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<RestaurantReviewsResponse>> => {
  return axios.get(`/api/restaurants/${id}/reviews`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getGetRestaurantReviewsUrl = (
  id: string,
  params?: GetRestaurantReviewsParams,
) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/restaurants/${id}/reviews`,
      baseURL: "",
      params,
    });
};
/**
 * @summary Leave a review of the restaurant: it waits for the restaurant to approve it.
 */
export const storeRestaurantReview = (
  id: string,
  storeRestaurantReviewRequest: StoreRestaurantReviewRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<RestaurantReviewResponse>> => {
  return axios.post(
    `/api/restaurants/${id}/reviews`,
    storeRestaurantReviewRequest,
    options,
  );
};
export const getStoreRestaurantReviewUrl = (id: string) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/restaurants/${id}/reviews`,
      baseURL: "",
    });
};
/**
 * @summary The device's own reviews of the restaurant, whatever their status.
 */
export const getMyRestaurantReviews = (
  id: string,
  myRestaurantReviewsRequest: MyRestaurantReviewsRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<MyRestaurantReviewsResponse>> => {
  return axios.post(
    `/api/restaurants/${id}/reviews/mine`,
    myRestaurantReviewsRequest,
    options,
  );
};
export const getGetMyRestaurantReviewsUrl = (id: string) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/restaurants/${id}/reviews/mine`,
      baseURL: "",
    });
};
export type GetRestaurantReviewsResult =
  AxiosResponse<RestaurantReviewsResponse>;
export type StoreRestaurantReviewResult =
  AxiosResponse<RestaurantReviewResponse>;
export type GetMyRestaurantReviewsResult =
  AxiosResponse<MyRestaurantReviewsResponse>;
