/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  GetHolidaysParams,
  GetHolidaysResponse,
  GetSchedulesResponse,
  IndexRestaurantResponse,
  IndexRestaurantsParams,
  ShowRestaurantParams,
  ShowRestaurantResponse,
  UpdateRestaurantParams,
  UpdateRestaurantRequest,
  UpdateRestaurantResponse,
} from "../models";

/**
 * @summary Index restaurants.
 */
export const indexRestaurants = <
  TData = AxiosResponse<IndexRestaurantResponse>,
>(
  params?: IndexRestaurantsParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/restaurants`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
/**
 * @summary Show restaurant by id.
 */
export const showRestaurant = <TData = AxiosResponse<ShowRestaurantResponse>>(
  id: number,
  params?: ShowRestaurantParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/restaurants/${id}`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
/**
 * @summary Update restaurant.
 */
export const updateRestaurant = <
  TData = AxiosResponse<UpdateRestaurantResponse>,
>(
  id: number,
  updateRestaurantRequest: UpdateRestaurantRequest,
  params?: UpdateRestaurantParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.patch(`/api/restaurants/${id}`, updateRestaurantRequest, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
/**
 * @summary Get restaurant's schedules.
 */
export const getSchedules = <TData = AxiosResponse<GetSchedulesResponse>>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/restaurants/${id}/schedules`, options);
};
/**
 * @summary Get restaurant's holidays.
 */
export const getHolidays = <TData = AxiosResponse<GetHolidaysResponse>>(
  id: number,
  params?: GetHolidaysParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/restaurants/${id}/holidays`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export type IndexRestaurantsResult = AxiosResponse<IndexRestaurantResponse>;
export type ShowRestaurantResult = AxiosResponse<ShowRestaurantResponse>;
export type UpdateRestaurantResult = AxiosResponse<UpdateRestaurantResponse>;
export type GetSchedulesResult = AxiosResponse<GetSchedulesResponse>;
export type GetHolidaysResult = AxiosResponse<GetHolidaysResponse>;
