/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  IndexRestaurantReviewResponse,
  IndexRestaurantReviewsParams,
  ShowRestaurantReviewResponse,
  StoreRestaurantReviewRequest,
  StoreRestaurantReviewResponse,
} from "../models";

/**
 * @summary Index restaurant reviews.
 */
export const indexRestaurantReviews = (
  params?: IndexRestaurantReviewsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<IndexRestaurantReviewResponse>> => {
  return axios.get(`/api/restaurant-reviews`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getIndexRestaurantReviewsUrl = (
  params?: IndexRestaurantReviewsParams,
) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/restaurant-reviews`,
      baseURL: "",
      params,
    });
};
/**
 * @summary Store restaurant review.
 */
export const storeRestaurantReview = (
  storeRestaurantReviewRequest: StoreRestaurantReviewRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<StoreRestaurantReviewResponse>> => {
  return axios.post(
    `/api/restaurant-reviews`,
    storeRestaurantReviewRequest,
    options,
  );
};
export const getStoreRestaurantReviewUrl = () => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/restaurant-reviews`,
      baseURL: "",
    });
};
/**
 * @summary Show restaurant reviews by id.
 */
export const showRestaurantReview = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ShowRestaurantReviewResponse>> => {
  return axios.get(`/api/restaurant-reviews/${id}`, options);
};
export const getShowRestaurantReviewUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/restaurant-reviews/${id}`,
      baseURL: "",
    });
};
export type IndexRestaurantReviewsResult =
  AxiosResponse<IndexRestaurantReviewResponse>;
export type StoreRestaurantReviewResult =
  AxiosResponse<StoreRestaurantReviewResponse>;
export type ShowRestaurantReviewResult =
  AxiosResponse<ShowRestaurantReviewResponse>;
