/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  IndexServiceResponse,
  IndexServicesParams,
  ShowServiceParams,
  ShowServiceResponse,
} from "../models";

/**
 * @summary Index services.
 */
export const indexServices = <TData = AxiosResponse<IndexServiceResponse>>(
  params?: IndexServicesParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/services`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
/**
 * @summary Show service by id.
 */
export const showService = <TData = AxiosResponse<ShowServiceResponse>>(
  id: number,
  params?: ShowServiceParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/services/${id}`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export type IndexServicesResult = AxiosResponse<IndexServiceResponse>;
export type ShowServiceResult = AxiosResponse<ShowServiceResponse>;
