/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  IndexSpaceReservationsResponse,
  IndexSpaceResponse,
  IndexSpacesParams,
  IndexSpacesReservationsParams,
  ShowSpaceParams,
  ShowSpaceResponse,
} from "../models";

/**
 * @summary Index spaces.
 */
export const indexSpaces = <TData = AxiosResponse<IndexSpaceResponse>>(
  params?: IndexSpacesParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/spaces`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
/**
 * @summary Show space by id.
 */
export const showSpace = <TData = AxiosResponse<ShowSpaceResponse>>(
  id: number,
  params?: ShowSpaceParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/spaces/${id}`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
/**
 * @summary Index spaces reservations.
 */
export const indexSpacesReservations = <
  TData = AxiosResponse<IndexSpaceReservationsResponse>,
>(
  params: IndexSpacesReservationsParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/spaces/reservations`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export type IndexSpacesResult = AxiosResponse<IndexSpaceResponse>;
export type ShowSpaceResult = AxiosResponse<ShowSpaceResponse>;
export type IndexSpacesReservationsResult =
  AxiosResponse<IndexSpaceReservationsResponse>;
