/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  IndexTagResponse,
  IndexTagsParams,
  ShowTagResponse,
} from "../models";

/**
 * @summary Index tags.
 */
export const indexTags = <TData = AxiosResponse<IndexTagResponse>>(
  params?: IndexTagsParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/tags`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
/**
 * @summary Show tag by id.
 */
export const showTag = <TData = AxiosResponse<ShowTagResponse>>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/tags/${id}`, options);
};
export type IndexTagsResult = AxiosResponse<IndexTagResponse>;
export type ShowTagResult = AxiosResponse<ShowTagResponse>;
