/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  IndexTagResponse,
  IndexTagsParams,
  ShowTagResponse,
} from "../models";

/**
 * @summary Index tags.
 */
export const indexTags = (
  params?: IndexTagsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<IndexTagResponse>> => {
  return axios.get(`/api/tags`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getIndexTagsUrl = (params?: IndexTagsParams) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/tags`,
      baseURL: "",
      params,
    });
};
/**
 * @summary Show tag by id.
 */
export const showTag = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ShowTagResponse>> => {
  return axios.get(`/api/tags/${id}`, options);
};
export const getShowTagUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/tags/${id}`,
      baseURL: "",
    });
};
export type IndexTagsResult = AxiosResponse<IndexTagResponse>;
export type ShowTagResult = AxiosResponse<ShowTagResponse>;
