/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  IndexTicketResponse,
  IndexTicketsParams,
  ShowTicketParams,
  ShowTicketResponse,
} from "../models";

/**
 * @summary Index tickets.
 */
export const indexTickets = <TData = AxiosResponse<IndexTicketResponse>>(
  params?: IndexTicketsParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/tickets`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
/**
 * @summary Show ticket by id.
 */
export const showTicket = <TData = AxiosResponse<ShowTicketResponse>>(
  id: number,
  params?: ShowTicketParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/tickets/${id}`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export type IndexTicketsResult = AxiosResponse<IndexTicketResponse>;
export type ShowTicketResult = AxiosResponse<ShowTicketResponse>;
