/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  IndexUserResponse,
  IndexUsersParams,
  MeParams,
  MeResponse,
  ShowUserResponse,
  UpdateUserRequest,
  UpdateUserResponse,
} from "../models";

/**
 * @summary Get currently logged user.
 */
export const me = (
  params?: MeParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<MeResponse>> => {
  return axios.get(`/api/users/me`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getMeUrl = (params?: MeParams) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/users/me`,
      baseURL: "",
      params,
    });
};
/**
 * @summary Index users.
 */
export const indexUsers = (
  params?: IndexUsersParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<IndexUserResponse>> => {
  return axios.get(`/api/users`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getIndexUsersUrl = (params?: IndexUsersParams) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/users`,
      baseURL: "",
      params,
    });
};
/**
 * @summary Show user by id.
 */
export const showUser = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ShowUserResponse>> => {
  return axios.get(`/api/users/${id}`, options);
};
export const getShowUserUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/users/${id}`,
      baseURL: "",
    });
};
/**
 * @summary Update user.
 */
export const updateUser = (
  id: number,
  updateUserRequest: UpdateUserRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<UpdateUserResponse>> => {
  return axios.patch(`/api/user/${id}`, updateUserRequest, options);
};
export const getUpdateUserUrl = (id: number) => {
  return axios
    .create({
      baseURL: "",
      params: null,
    })
    .getUri({
      url: `/api/user/${id}`,
      baseURL: "",
    });
};
export type MeResult = AxiosResponse<MeResponse>;
export type IndexUsersResult = AxiosResponse<IndexUserResponse>;
export type ShowUserResult = AxiosResponse<ShowUserResponse>;
export type UpdateUserResult = AxiosResponse<UpdateUserResponse>;
