/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  DestroyRequest,
  DestroyWaiterResponse,
  IndexWaiterResponse,
  IndexWaitersParams,
  RestoreWaiterResponse,
  ShowWaiterResponse,
  StoreWaiterRequest,
  StoreWaiterResponse,
  UpdateWaiterRequest,
  UpdateWaiterResponse,
} from "../models";

/**
 * @summary Index waiters.
 */
export const indexWaiters = <TData = AxiosResponse<IndexWaiterResponse>>(
  params?: IndexWaitersParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/waiters`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
/**
 * @summary Store waiter.
 */
export const storeWaiter = <TData = AxiosResponse<StoreWaiterResponse>>(
  storeWaiterRequest: StoreWaiterRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/api/waiters`, storeWaiterRequest, options);
};
/**
 * @summary Show waiter by id.
 */
export const showWaiter = <TData = AxiosResponse<ShowWaiterResponse>>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/waiters/${id}`, options);
};
/**
 * @summary Delete waiter.
 */
export const destroyWaiter = <TData = AxiosResponse<DestroyWaiterResponse>>(
  id: number,
  destroyRequest?: DestroyRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.delete(`/api/waiters/${id}`, {
    data: destroyRequest,
    ...options,
  });
};
/**
 * @summary Update waiter.
 */
export const updateWaiter = <TData = AxiosResponse<UpdateWaiterResponse>>(
  id: number,
  updateWaiterRequest: UpdateWaiterRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.patch(`/api/waiters/${id}`, updateWaiterRequest, options);
};
/**
 * @summary Restore waiter.
 */
export const restoreWaiter = <TData = AxiosResponse<RestoreWaiterResponse>>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/api/waiters/${id}/restore`, undefined, options);
};
export type IndexWaitersResult = AxiosResponse<IndexWaiterResponse>;
export type StoreWaiterResult = AxiosResponse<StoreWaiterResponse>;
export type ShowWaiterResult = AxiosResponse<ShowWaiterResponse>;
export type DestroyWaiterResult = AxiosResponse<DestroyWaiterResponse>;
export type UpdateWaiterResult = AxiosResponse<UpdateWaiterResponse>;
export type RestoreWaiterResult = AxiosResponse<RestoreWaiterResponse>;
