/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { AlternationMetadata } from "./alternationMetadata";
import type { Product } from "./product";
import type { ProductVariant } from "./productVariant";

/**
 * Alternation resource object
 */
export interface Alternation {
  id: number;
  type: string;
  /** @nullable */
  metadata: AlternationMetadata;
  alterable_id: number;
  alterable_type: string;
  /** @nullable */
  perform_at: string | null;
  /** @nullable */
  performed_at: string | null;
  alterable?: Product | ProductVariant;
}
