/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { AlternationMetadata } from "./alternationMetadata";
import type { AlternationAlterable } from "./alternationAlterable";

/**
 * Alternation resource object
 */
export interface Alternation {
  id: number;
  type: string;
  /** @nullable */
  metadata: AlternationMetadata;
  alterable_id: number;
  alterable_type: string;
  /** @nullable */
  perform_at: string | null;
  /** @nullable */
  performed_at: string | null;
  alterable?: AlternationAlterable;
}
