/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Query parameter, which determines if archived records should be
    fetched from database. Available relations: `only`, `with` and `without`, which is a default one.
 */
export type ArchivedParameter =
  (typeof ArchivedParameter)[keyof typeof ArchivedParameter];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ArchivedParameter = {
  only: "only",
  with: "with",
  without: "without",
} as const;
