/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Attaching discount
 */
export interface AttachingDiscount {
  id?: number;
  discount_id: number;
  discountable_id?: number;
  discountable_type?: string;
}
