/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Attach category to menu response object.
 */
export interface AttachProductToMenuResponse {
  message: string;
}
