/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Attach product to menu request.
 */
export interface AttachProductToMenuRequest {
  menu_id: number;
  product_id: number;
}
