/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Attach category to menu request.
 */
export interface AttachCategoryToMenuRequest {
  menu_id: number;
  category_id: number;
}
