/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Attaching comment
 */
export interface AttachingComment {
  id?: number;
  commentable_id?: number;
  commentable_type?: string;
  text: string;
}
