/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type BanquetInvoiceUrlRequestEndpoint =
  (typeof BanquetInvoiceUrlRequestEndpoint)[keyof typeof BanquetInvoiceUrlRequestEndpoint];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BanquetInvoiceUrlRequestEndpoint = {
  pdfThroughBanquet: "pdfThroughBanquet",
  viewThroughBanquet: "viewThroughBanquet",
} as const;
