/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { BanquetInvoiceUrlRequestEndpoint } from "./banquetInvoiceUrlRequestEndpoint";

/**
 * Generate url for accessing banquet's invoice request
 */
export interface BanquetInvoiceUrlRequest {
  endpoint?: BanquetInvoiceUrlRequestEndpoint;
}
