/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { OrderTotals } from "./orderTotals";

/**
 * @nullable
 */
export type BanquetTotals = OrderTotals | null;
