/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Generate url for accessing invoice for multiple banquets response.
 */
export interface BanquetMultipleInvoiceUrlResponse {
  url: string;
  message: string;
}
