/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { BanquetState } from "./banquetState";
import type { BanquetAvailableStatesItem } from "./banquetAvailableStatesItem";
import type { BanquetTotals } from "./banquetTotals";
import type { Order } from "./order";
import type { User } from "./user";
import type { Customer } from "./customer";
import type { Comment } from "./comment";
import type { Discount } from "./discount";

/**
 * Banquet resource object
 */
export interface Banquet {
  id: number;
  type: string;
  state: BanquetState;
  /** List of states, to which banquet may be transferred. */
  available_states: BanquetAvailableStatesItem[];
  /** Determines if banquet can be edited. */
  is_editable: boolean;
  /** Determines if logged in user can edit this banquet. */
  can_edit: boolean;
  title: string;
  /** @nullable */
  description: string | null;
  start_at: string;
  end_at: string;
  /** @nullable */
  paid_at: string | null;
  advance_amount: number;
  /** @nullable */
  advance_amount_payment_method: string | null;
  /** @nullable */
  actual_total: number | null;
  /** @nullable */
  is_birthday_club: boolean | null;
  /** @nullable */
  with_photographer: boolean | null;
  /** @nullable */
  children_amount: number | null;
  /** @nullable */
  child_ticket_price: number | null;
  children_amounts?: number[];
  child_ticket_prices?: unknown[];
  /** @nullable */
  adults_amount: number | null;
  /** @nullable */
  adult_ticket_price: number | null;
  /** @nullable */
  totals: BanquetTotals;
  /** @nullable */
  invoice_url: string | null;
  /** @nullable */
  order_id: number | null;
  creator_id: number;
  customer_id: number;
  /** @nullable */
  restaurant_id: number | null;
  order?: Order;
  creator?: User;
  customer?: Customer;
  comments?: Comment[];
  discounts?: Discount[];
}
