/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type BanquetAvailableStatesItem =
  (typeof BanquetAvailableStatesItem)[keyof typeof BanquetAvailableStatesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BanquetAvailableStatesItem = {
  draft: "draft",
  new: "new",
  processing: "processing",
  completed: "completed",
  cancelled: "cancelled",
} as const;
