/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type BanquetState = (typeof BanquetState)[keyof typeof BanquetState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BanquetState = {
  new: "new",
  confirmed: "confirmed",
  postponed: "postponed",
  cancelled: "cancelled",
  completed: "completed",
} as const;
