/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Generate url for accessing banquet's invoice response.
 */
export interface BanquetInvoiceUrlResponse {
  url: string;
  message: string;
}
