/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Media } from "./media";
import type { Tag } from "./tag";

/**
 * Category resource object
 */
export interface Category {
  id: number;
  slug: string;
  type: string;
  /** @nullable */
  target: string | null;
  title: string;
  /** @nullable */
  description: string | null;
  tags?: Tag[];
  media: Media[];
}
