/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { CategoryDescription } from "./categoryDescription";
import type { Tag } from "./tag";
import type { Media } from "./media";

/**
 * Category resource object
 */
export interface Category {
  id: number;
  slug: string;
  type: string;
  /** @nullable */
  target: string | null;
  title: string;
  /** @nullable */
  description: CategoryDescription;
  tags?: Tag[];
  media: Media[];
}
