/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Comment resource object
 */
export interface Comment {
  id: number;
  type: string;
  text: string;
  commentable_id: number;
  commentable_type: string;
}
