/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Restaurant } from "./restaurant";
import type { FamilyMember } from "./familyMember";
import type { Comment } from "./comment";

/**
 * Customer resource object
 */
export interface Customer {
  id: number;
  /** @nullable */
  restaurant_id: number | null;
  type: string;
  name: string;
  surname: string;
  phone: string;
  /** @nullable */
  email: string | null;
  /** @nullable */
  birthdate: string | null;
  restaurant?: Restaurant;
  family_members?: FamilyMember[];
  comments?: Comment[];
}
