/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Query parameter, which determines if soft-deleted records should be
 *     fetched from database. Available relations: `only`, `with` and `without`, which is a default one.
 */
export type DeletedParameter =
  (typeof DeletedParameter)[keyof typeof DeletedParameter];

export const DeletedParameter = {
  only: "only",
  with: "with",
  without: "without",
} as const;
