/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Query parameter, which determines if soft-deleted records should be
    fetched from database. Available relations: `only`, `with` and `without`, which is a default one.
 */
export type DeletedParameter =
  (typeof DeletedParameter)[keyof typeof DeletedParameter];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeletedParameter = {
  only: "only",
  with: "with",
  without: "without",
} as const;
