/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Delete product response object.
 */
export interface DestroyProductResponse {
  message: string;
}
