/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Delete comment response object.
 */
export interface DestroyCommentResponse {
  message: string;
}
