/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Destroy request
 */
export interface DestroyRequest {
  /** Determines whether resource should be deleted without chance of restoring. */
  force?: boolean;
}
