/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Delete banquet response object.
 */
export interface DestroyBanquetResponse {
  message: string;
}
