/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Detach product from menu request.
 */
export interface DetachProductFromMenuRequest {
  menu_id: number;
  product_id: number;
}
