/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Detach category from menu request.
 */
export interface DetachCategoryFromMenuRequest {
  menu_id: number;
  category_id: number;
}
