/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Detach product from menu response object.
 */
export interface DetachProductFromMenuResponse {
  message: string;
}
