/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Discount resource object
 */
export interface Discount {
  id: number;
  type: string;
  /** @nullable */
  target: string | null;
  title: string;
  /** @nullable */
  description: string | null;
  /** @nullable */
  amount: number | null;
  /** @nullable */
  percent: number | null;
}
