/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { DishCategoryMetadata } from "./dishCategoryMetadata";
import type { DishMenu } from "./dishMenu";
import type { Media } from "./media";

/**
 * Dish category resource object
 */
export interface DishCategory {
  id: number;
  menu_id: number;
  type: string;
  /** @nullable */
  slug: string | null;
  /** @nullable */
  target: string | null;
  title: string;
  /** @nullable */
  description: string | null;
  archived: boolean;
  /** @nullable */
  popularity: number | null;
  /** @nullable */
  metadata: DishCategoryMetadata;
  menu?: DishMenu;
  media?: Media[];
}
