/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { DishVariant } from "./dishVariant";
import type { DishMenu } from "./dishMenu";
import type { DishCategory } from "./dishCategory";
import type { Media } from "./media";

/**
 * Dish resource object
 */
export interface Dish {
  id: number;
  menu_id: number;
  /** @nullable */
  category_id: number | null;
  type: string;
  /** @nullable */
  slug: string | null;
  title: string;
  /** @nullable */
  description: string | null;
  /** @nullable */
  badge: string | null;
  price: number;
  /** @nullable */
  weight: string | null;
  /** @nullable */
  weight_unit: string | null;
  /** @nullable */
  calories: number | null;
  /** @nullable */
  preparation_time: number | null;
  archived: boolean;
  /** @nullable */
  popularity: number | null;
  /** @nullable */
  flags: string[] | null;
  variants: DishVariant[];
  menu?: DishMenu;
  category?: DishCategory;
  media?: Media[];
}
