/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Dish } from "./dish";
import type { DishCategory } from "./dishCategory";
import type { DishMenuMetadata } from "./dishMenuMetadata";
import type { Media } from "./media";
import type { Restaurant } from "./restaurant";

/**
 * Dish menu resource object
 */
export interface DishMenu {
  id: number;
  restaurant_id: number;
  type: string;
  /** @nullable */
  slug: string | null;
  title: string;
  /** @nullable */
  description: string | null;
  archived: boolean;
  /** @nullable */
  popularity: number | null;
  /** @nullable */
  metadata: DishMenuMetadata;
  dishes?: Dish[];
  categories?: DishCategory[];
  restaurant?: Restaurant;
  media?: Media[];
}
