/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type EditorVersionChangeFields = {
  [key: string]: {
    live: unknown;
    new: unknown;
  };
};
