/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorReviewModeratedBy } from "./editorReviewModeratedBy";
import type { EditorReviewStatus } from "./editorReviewStatus";

/**
 * A guest's review of the restaurant, for its moderation.
 */
export interface EditorReview {
  id: number;
  restaurant_id: number;
  /**
   * @minimum 1
   * @maximum 5
   */
  rating: number;
  /** @nullable */
  name: string | null;
  /** @nullable */
  text: string | null;
  /** @nullable */
  locale: string | null;
  status: EditorReviewStatus;
  /** @nullable */
  created_at: string | null;
  /** @nullable */
  moderated_at: string | null;
  /** @nullable */
  moderated_by: EditorReviewModeratedBy;
}
