/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorTranslations } from "./editorTranslations";
import type { EditorUpdateRestaurantRequestEstablishment } from "./editorUpdateRestaurantRequestEstablishment";

/**
 * Details and brand colors of a restaurant. Fields, which are left out, stay as they are.
 */
export interface EditorUpdateRestaurantRequest {
  name?: EditorTranslations;
  establishment?: EditorUpdateRestaurantRequestEstablishment;
  /** @nullable */
  phone?: string | null;
  address?: EditorTranslations;
  /**
   * Both colors or neither. Text on the color's tints needs 4.5 : 1 contrast.
   * @nullable
   */
  brand_primary?: string | null;
  /** @nullable */
  brand_primary_content?: string | null;
}
