/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorDashboard } from "./editorDashboard";

/**
 * What the dashboard shows of the restaurant.
 */
export interface EditorDashboardResponse {
  data: EditorDashboard;
  message: string;
}
