/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type EditorReviewStatus =
  (typeof EditorReviewStatus)[keyof typeof EditorReviewStatus];

export const EditorReviewStatus = {
  pending: "pending",
  approved: "approved",
  rejected: "rejected",
} as const;
