/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorTranslations } from "./editorTranslations";

/**
 * Special day (or days). Hours are required, unless it's closed.
 */
export interface EditorScheduleExceptionInput {
  /** @nullable */
  id?: number | null;
  starts_on: string;
  /** @nullable */
  ends_on?: string | null;
  is_closed: boolean;
  /** @nullable */
  beg_hour?: number | null;
  /** @nullable */
  beg_minute?: number | null;
  /** @nullable */
  end_hour?: number | null;
  /** @nullable */
  end_minute?: number | null;
  reason?: EditorTranslations;
}
