/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorReview } from "./editorReview";
import type { EditorReviewsResponseCounts } from "./editorReviewsResponseCounts";
import type { EditorReviewsResponseMeta } from "./editorReviewsResponseMeta";

/**
 * A page of the restaurant's reviews with the status, and how many have each status.
 */
export interface EditorReviewsResponse {
  data: EditorReview[];
  meta: EditorReviewsResponseMeta;
  counts: EditorReviewsResponseCounts;
  message: string;
}
