/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type EditorUpdateRestaurantRequestEstablishment =
  (typeof EditorUpdateRestaurantRequestEstablishment)[keyof typeof EditorUpdateRestaurantRequestEstablishment];

export const EditorUpdateRestaurantRequestEstablishment = {
  restaurant: "restaurant",
  cafe: "cafe",
  bakery: "bakery",
  bistro: "bistro",
  pizzeria: "pizzeria",
  bar: "bar",
} as const;
