/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorUpdateDishRequestSizesItemWeightUnit } from "./editorUpdateDishRequestSizesItemWeightUnit";

export type EditorUpdateDishRequestSizesItem = {
  /**
   * Variant to keep (only when updating).
   * @nullable
   */
  id?: number | null;
  price: number;
  /** @nullable */
  weight?: number | null;
  /** @nullable */
  weight_unit?: EditorUpdateDishRequestSizesItemWeightUnit;
  /** @nullable */
  calories?: number | null;
  /** @nullable */
  preparation_time?: number | null;
};
