/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * A photo in a gallery: hidden ones are kept, but guests don't see them.
 */
export interface EditorPhoto {
  id: number;
  is_hidden?: boolean;
}
