/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorMenu } from "./editorMenu";
import type { EditorNote } from "./editorNote";
import type { EditorRestaurantEstablishment } from "./editorRestaurantEstablishment";
import type { EditorScheduleException } from "./editorScheduleException";
import type { EditorTranslations } from "./editorTranslations";
import type { EditorWeekdays } from "./editorWeekdays";
import type { Media } from "./media";

/**
 * Everything of a restaurant the editor shows, in all languages.
 */
export interface EditorRestaurant {
  id: number;
  slug: string;
  /** Public page of the restaurant. */
  url: string;
  /** Language, which required texts have to be written in. */
  default_locale: string;
  supported_locales: string[];
  name: EditorTranslations;
  /** @nullable */
  establishment: EditorRestaurantEstablishment;
  /** @nullable */
  phone: string | null;
  address: EditorTranslations;
  timezone: string;
  /** @nullable */
  currency: string | null;
  /** @nullable */
  brand_primary: string | null;
  /** @nullable */
  brand_primary_content: string | null;
  /**
   * Temporarily closed till this day.
   * @nullable
   */
  closed_until: string | null;
  closed_reason: EditorTranslations;
  notes: EditorNote[];
  photos: Media[];
  weekdays: EditorWeekdays;
  exceptions: EditorScheduleException[];
  menus: EditorMenu[];
}
