/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorReview } from "./editorReview";

/**
 * The review with its new status.
 */
export interface EditorReviewResponse {
  data: EditorReview;
  message: string;
}
