/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Category of the restaurant to move the dish to.
 */
export interface EditorMoveDishRequest {
  category_id: number;
}
