/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * A photo: JPG, PNG or WebP, up to 10 MB.
 */
export interface EditorUploadPhotoRequest {
  file: Blob | File;
}
