/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorStoreDishRequestSizesItem } from "./editorStoreDishRequestSizesItem";
import type { EditorTranslations } from "./editorTranslations";

/**
 * A new dish goes at the end of the category.
 */
export interface EditorStoreDishRequest {
  title: EditorTranslations;
  description?: EditorTranslations;
  badge?: EditorTranslations;
  is_hidden?: boolean;
  flags?: string[];
  /** The first one is the dish itself, 1 to 10 of them. */
  sizes: EditorStoreDishRequestSizesItem[];
  /** Ids of the dish's photos (the restaurant's ones), 5 at most. */
  media?: number[];
}
