/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorVersion } from "./editorVersion";

/**
 * The version with its changes, their items and conflicts.
 */
export interface EditorVersionResponse {
  data: EditorVersion;
  message: string;
}
