/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type EditorVersionStatus =
  (typeof EditorVersionStatus)[keyof typeof EditorVersionStatus];

export const EditorVersionStatus = {
  draft: "draft",
  scheduled: "scheduled",
  inactive: "inactive",
  applied: "applied",
  failed: "failed",
} as const;
