/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorTranslations } from "./editorTranslations";

export type EditorUpdateRestaurantNotesRequestNotesItem = {
  /** @nullable */
  id?: number | null;
  text: EditorTranslations;
  is_hidden?: boolean;
};
