/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Fields, which are left out, stay as they are. A scheduled version stays in the future.
 */
export interface EditorUpdateVersionRequest {
  /** @nullable */
  name?: string | null;
  /**
   * In the restaurant's time zone, unless it has an offset.
   * @nullable
   */
  goes_live_at?: string | null;
}
