/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Ids of the restaurant's photos in their order, the first one is the cover.
 */
export interface EditorUpdateRestaurantPhotosRequest {
  media: number[];
}
