/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Menu of the restaurant to move the category (with its dishes) to.
 */
export interface EditorMoveCategoryRequest {
  menu_id: number;
}
