/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorDish } from "./editorDish";
import type { EditorTranslations } from "./editorTranslations";

/**
 * Category with its dishes, hidden and archived ones included.
 */
export interface EditorCategory {
  id: number;
  menu_id: number;
  /** @nullable */
  slug: string | null;
  title: EditorTranslations;
  description: EditorTranslations;
  is_hidden: boolean;
  archived: boolean;
  /** @nullable */
  archived_at: string | null;
  /**
   * Order of the categories in the menu, from the highest.
   * @nullable
   */
  popularity: number | null;
  dishes?: EditorDish[];
}
