/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorTranslations } from "./editorTranslations";

/**
 * Fields, which are left out, stay as they are.
 */
export interface EditorUpdateMenuRequest {
  title?: EditorTranslations;
  description?: EditorTranslations;
  is_hidden?: boolean;
}
