/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Of a dish's size.
 * @nullable
 */
export type EditorVersionLabelSize = {
  weight: string;
  /** @nullable */
  weight_unit: string | null;
} | null;
