/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorDashboardLastSavedBy } from "./editorDashboardLastSavedBy";
import type { EditorScheduleException } from "./editorScheduleException";
import type { EditorTranslations } from "./editorTranslations";
import type { EditorVersion } from "./editorVersion";
import type { EditorWeekdays } from "./editorWeekdays";

/**
 * What the dashboard shows: what guests see, the hours (open now is worked out from them,
 *      *     in the restaurant's time zone), upcoming special days and the versions, which haven't gone live yet.
 */
export interface EditorDashboard {
  id: number;
  /** @nullable */
  slug: string | null;
  url: string;
  default_locale: string;
  supported_locales: string[];
  name: EditorTranslations;
  /** @nullable */
  establishment: string | null;
  timezone: string;
  /** @nullable */
  currency: string | null;
  /** Menus guests see. */
  menus_count: number;
  /** Dishes guests see. */
  dishes_count: number;
  /** @nullable */
  last_saved_at: string | null;
  /** @nullable */
  last_saved_by: EditorDashboardLastSavedBy;
  /** @nullable */
  closed_until: string | null;
  closed_reason: EditorTranslations;
  weekdays: EditorWeekdays;
  /** Special days, which haven't ended yet, from the nearest. */
  exceptions: EditorScheduleException[];
  versions: EditorVersion[];
}
