/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorUpdateRestaurantNotesRequestNotesItem } from "./editorUpdateRestaurantNotesRequestNotesItem";

/**
 * All notes in their order. Left out ones are deleted, ones without an id are added.
 */
export interface EditorUpdateRestaurantNotesRequest {
  notes: EditorUpdateRestaurantNotesRequestNotesItem[];
}
