/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorOrderMenusRequestMenusItem } from "./editorOrderMenusRequestMenusItem";

/**
 * Menus and their categories in their new order. Categories listed under another menu move there.
 */
export interface EditorOrderMenusRequest {
  menus: EditorOrderMenusRequestMenusItem[];
}
