/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorSizeWeightUnit } from "./editorSizeWeightUnit";

/**
 * Size of a dish (one of its variants).
 */
export interface EditorSize {
  id: number;
  price: number;
  /** @nullable */
  weight: string | null;
  /** @nullable */
  weight_unit: EditorSizeWeightUnit;
  /** @nullable */
  calories: number | null;
  /**
   * In minutes.
   * @nullable
   */
  preparation_time: number | null;
  /** Hidden from guests (a dish has at least one size, which isn't). */
  is_hidden: boolean;
  /**
   * When an archived size was archived.
   * @nullable
   */
  archived_at: string | null;
}
