/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type EditorOrderMenusRequestMenusItem = {
  id: number;
  is_hidden?: boolean;
  categories: number[];
};
