/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorVersionChangeConflictsFields } from "./editorVersionChangeConflictsFields";

/**
 * Only on a version's own page: `missing` when the item (or a new one's parent) is gone,
 *      *       `fields` with live values, which changed since they were planned.
 */
export type EditorVersionChangeConflicts = {
  missing?: boolean;
  fields?: EditorVersionChangeConflictsFields;
};
