/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * New values, as in the editor's requests (a new dish has `sizes`); live ones are no change.
 */
export type EditorPutVersionChangeRequestFields = { [key: string]: unknown };
