/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * @nullable
 */
export type EditorSizeWeightUnit =
  (typeof EditorSizeWeightUnit)[keyof typeof EditorSizeWeightUnit] | null;

export const EditorSizeWeightUnit = {
  g: "g",
  kg: "kg",
  ml: "ml",
  l: "l",
  cm: "cm",
  pc: "pc",
} as const;
