/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type EditorVersionChangeTargetType =
  (typeof EditorVersionChangeTargetType)[keyof typeof EditorVersionChangeTargetType];

export const EditorVersionChangeTargetType = {
  restaurants: "restaurants",
  "restaurant-notes": "restaurant-notes",
  "dish-menus": "dish-menus",
  "dish-categories": "dish-categories",
  dishes: "dishes",
  "dish-variants": "dish-variants",
} as const;
