/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * @nullable
 */
export type EditorStoreDishRequestSizesItemWeightUnit =
  | (typeof EditorStoreDishRequestSizesItemWeightUnit)[keyof typeof EditorStoreDishRequestSizesItemWeightUnit]
  | null;

export const EditorStoreDishRequestSizesItemWeightUnit = {
  g: "g",
  kg: "kg",
  ml: "ml",
  l: "l",
  cm: "cm",
  pc: "pc",
} as const;
