/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Restaurant the user can edit.
 */
export interface EditorRestaurantItem {
  id: number;
  slug: string;
  /** In the current language. */
  name: string;
  default_locale: string;
  /**
   * Its cover.
   * @nullable
   */
  photo: string | null;
}
