/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * @nullable
 */
export type EditorDashboardLastSavedBy = {
  id: number;
  name: string;
} | null;
