/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * @nullable
 */
export type EditorUpdateDishRequestSizesItemWeightUnit =
  | (typeof EditorUpdateDishRequestSizesItemWeightUnit)[keyof typeof EditorUpdateDishRequestSizesItemWeightUnit]
  | null;

export const EditorUpdateDishRequestSizesItemWeightUnit = {
  g: "g",
  kg: "kg",
  ml: "ml",
  l: "l",
  cm: "cm",
  pc: "pc",
} as const;
