/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorVersionChange } from "./editorVersionChange";
import type { EditorVersionCreatedBy } from "./editorVersionCreatedBy";
import type { EditorVersionStatus } from "./editorVersionStatus";
import type { Media } from "./media";

/**
 * Scheduled version: changes, which go live together. Dates are in the restaurant's time zone.
 */
export interface EditorVersion {
  id: number;
  restaurant_id: number;
  /**
   * None for a change scheduled on its own.
   * @nullable
   */
  name: string | null;
  status: EditorVersionStatus;
  /** @nullable */
  goes_live_at: string | null;
  timezone: string;
  /** @nullable */
  created_by: EditorVersionCreatedBy;
  /** @nullable */
  created_at: string | null;
  /** @nullable */
  applied_at: string | null;
  /** @nullable */
  failed_at: string | null;
  /** @nullable */
  failure_reason: string | null;
  /** Changed fields, a new item counts as one. */
  changes_count: number;
  items_count: number;
  changes: EditorVersionChange[];
  /** Photos of the changes. */
  media: Media[];
}
