/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorDish } from "./editorDish";

/**
 * Dish with its sizes and photos.
 */
export interface EditorDishResponse {
  data: EditorDish;
  message: string;
}
