/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorPutVersionChangeRequestFields } from "./editorPutVersionChangeRequestFields";
import type { EditorPutVersionChangeRequestTargetType } from "./editorPutVersionChangeRequestTargetType";

/**
 * A change of an item (or a new one). Its fields are merged into the item's change in the
 *      *     version; a field back at its live value isn't a change anymore. Fields and their values are those of
 *      *     the editor's requests: texts in every language, `media` as photos, `archived` to archive or restore.
 */
export interface EditorPutVersionChangeRequest {
  /**
   * Change of a new item, which is being edited.
   * @nullable
   */
  id?: number | null;
  target_type: EditorPutVersionChangeRequestTargetType;
  /**
   * The changed item, none for a new one.
   * @nullable
   */
  target_id?: number | null;
  /**
   * Where a new item goes: the category of a dish, the dish of a size, the restaurant of a note.
   * @nullable
   */
  parent_id?: number | null;
  /** New values of the fields. A new dish has `sizes` too. */
  fields?: EditorPutVersionChangeRequestFields;
  /** Fields, which aren't changed anymore. */
  revert?: string[];
}
