/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type EditorReviewsResponseCounts = {
  pending: number;
  approved: number;
  rejected: number;
};
