/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorPhoto } from "./editorPhoto";
import type { EditorStoreDishRequestSizesItem } from "./editorStoreDishRequestSizesItem";
import type { EditorTranslations } from "./editorTranslations";

/**
 * A new dish goes at the end of the category.
 */
export interface EditorStoreDishRequest {
  title: EditorTranslations;
  description?: EditorTranslations;
  badge?: EditorTranslations;
  is_hidden?: boolean;
  flags?: string[];
  /** Its variants, 1 to 10 of them, at least one shown to guests. Archived ones stay as they are. */
  sizes: EditorStoreDishRequestSizesItem[];
  /** The dish's photos (the restaurant's ones) in their order, 3 at most, hidden ones included. */
  media?: EditorPhoto[];
}
