/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Translations of a text by language, `null` where there's none.
 */
export interface EditorTranslations {
  /** @nullable */
  en?: string | null;
  /** @nullable */
  uk?: string | null;
}
