/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorStoreDishRequestSizesItemWeightUnit } from "./editorStoreDishRequestSizesItemWeightUnit";

export type EditorStoreDishRequestSizesItem = {
  /**
   * Variant to keep (only when updating).
   * @nullable
   */
  id?: number | null;
  is_hidden?: boolean;
  price: number;
  /** @nullable */
  weight?: number | null;
  /** @nullable */
  weight_unit?: EditorStoreDishRequestSizesItemWeightUnit;
  /** @nullable */
  calories?: number | null;
  /** @nullable */
  preparation_time?: number | null;
};
