/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorSizeWeightUnit } from "./editorSizeWeightUnit";

/**
 * Size of a dish: the dish itself (with no id) or one of its variants.
 */
export interface EditorSize {
  /**
   * Id of the variant, `null` for the dish itself.
   * @nullable
   */
  id: number | null;
  price: number;
  /** @nullable */
  weight: string | null;
  /** @nullable */
  weight_unit: EditorSizeWeightUnit;
  /** @nullable */
  calories: number | null;
  /**
   * In minutes.
   * @nullable
   */
  preparation_time: number | null;
}
