/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorSize } from "./editorSize";
import type { EditorTranslations } from "./editorTranslations";
import type { Media } from "./media";

/**
 * Dish with its sizes (from the cheapest) and photos.
 */
export interface EditorDish {
  id: number;
  menu_id: number;
  /** @nullable */
  category_id: number | null;
  /** @nullable */
  slug: string | null;
  title: EditorTranslations;
  description: EditorTranslations;
  badge: EditorTranslations;
  is_hidden: boolean;
  archived: boolean;
  /** @nullable */
  archived_at: string | null;
  /**
   * Order of the dishes in the category, from the highest.
   * @nullable
   */
  popularity: number | null;
  /** Diet tags and allergens. */
  flags: string[];
  /** Its sizes, hidden ones included, from the cheapest. */
  sizes: EditorSize[];
  /** Its archived sizes: off the menu, they can be restored. */
  archived_sizes: EditorSize[];
  photos?: Media[];
}
