/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorCategory } from "./editorCategory";
import type { EditorTranslations } from "./editorTranslations";

/**
 * Menu with its categories, hidden and archived ones included.
 */
export interface EditorMenu {
  id: number;
  restaurant_id: number;
  /** @nullable */
  slug: string | null;
  title: EditorTranslations;
  description: EditorTranslations;
  is_hidden: boolean;
  archived: boolean;
  /** @nullable */
  archived_at: string | null;
  /**
   * Order of the menus, from the highest.
   * @nullable
   */
  popularity: number | null;
  categories?: EditorCategory[];
}
