/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorPutVersionChangeRequest } from "./editorPutVersionChangeRequest";

/**
 * A new version: a draft, or scheduled right away (then it needs its date).
 */
export interface EditorStoreVersionRequest {
  /**
   * None for a change scheduled on its own: it's named after the change.
   * @nullable
   */
  name?: string | null;
  /**
   * In the restaurant's time zone, unless it has an offset.
   * @nullable
   */
  goes_live_at?: string | null;
  schedule?: boolean;
  changes?: EditorPutVersionChangeRequest[];
}
