/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorPhoto } from "./editorPhoto";

/**
 * The restaurant's photos in their order, the first one shown is the cover.
 */
export interface EditorUpdateRestaurantPhotosRequest {
  /** 20 at most. */
  media: EditorPhoto[];
}
