/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorTranslations } from "./editorTranslations";
import type { EditorUpdateDishRequestSizesItem } from "./editorUpdateDishRequestSizesItem";

/**
 * Fields, which are left out, stay as they are. Sizes are replaced.
 */
export interface EditorUpdateDishRequest {
  title?: EditorTranslations;
  description?: EditorTranslations;
  badge?: EditorTranslations;
  is_hidden?: boolean;
  flags?: string[];
  /** The first one is the dish itself, 1 to 10 of them. */
  sizes?: EditorUpdateDishRequestSizesItem[];
  /** Ids of the dish's photos (the restaurant's ones), 5 at most. */
  media?: number[];
}
