/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * @nullable
 */
export type EditorRestaurantEstablishment =
  | (typeof EditorRestaurantEstablishment)[keyof typeof EditorRestaurantEstablishment]
  | null;

export const EditorRestaurantEstablishment = {
  restaurant: "restaurant",
  cafe: "cafe",
  bakery: "bakery",
  bistro: "bistro",
  pizzeria: "pizzeria",
  bar: "bar",
} as const;
