/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorVersion } from "./editorVersion";

/**
 * Versions of the restaurant.
 */
export interface EditorVersionsResponse {
  data: EditorVersion[];
  message: string;
}
