/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorPutVersionChangeRequestFields } from "./editorPutVersionChangeRequestFields";
import type { EditorPutVersionChangeRequestTargetType } from "./editorPutVersionChangeRequestTargetType";

/**
 * A change of an item (or a new one), merged into the item's change in the version.
 */
export interface EditorPutVersionChangeRequest {
  /**
   * Change of a new item, which is being edited.
   * @nullable
   */
  id?: number | null;
  target_type: EditorPutVersionChangeRequestTargetType;
  /**
   * The changed item, none for a new one.
   * @nullable
   */
  target_id?: number | null;
  /**
   * Where a new item goes: the category of a dish, the dish of a size, the restaurant of a note.
   * @nullable
   */
  parent_id?: number | null;
  /** New values, as in the editor's requests (a new dish has `sizes`); live ones are no change. */
  fields?: EditorPutVersionChangeRequestFields;
  /** Fields, which aren't changed anymore. */
  revert?: string[];
}
