/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorRestaurant } from "./editorRestaurant";

/**
 * Everything of the restaurant.
 */
export interface EditorRestaurantResponse {
  data: EditorRestaurant;
  message: string;
}
