/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * New values of the fields. A new dish has `sizes` too.
 */
export type EditorPutVersionChangeRequestFields = { [key: string]: unknown };
