/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorTranslations } from "./editorTranslations";

/**
 * Note of a restaurant.
 */
export interface EditorNote {
  id: number;
  text: EditorTranslations;
  is_hidden: boolean;
  order: number;
}
