/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorVersionLabelSize } from "./editorVersionLabelSize";

/**
 * The changed item, in the restaurant's default language. None, when it's gone.
 * @nullable
 */
export type EditorVersionLabel = {
  /** @nullable */
  name: string | null;
  /**
   * Of a dish's size.
   * @nullable
   */
  size: EditorVersionLabelSize;
  path: string[];
} | null;
