/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorCategory } from "./editorCategory";

/**
 * Category with its dishes.
 */
export interface EditorCategoryResponse {
  data: EditorCategory;
  message: string;
}
