/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorRestaurantItem } from "./editorRestaurantItem";

/**
 * Restaurants the user can edit.
 */
export interface EditorRestaurantsResponse {
  data: EditorRestaurantItem[];
  message: string;
}
