/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Opening interval of a day. Closing earlier than opening is after midnight.
 */
export interface EditorInterval {
  /** Only in responses. */
  id?: number;
  beg_hour: number;
  beg_minute: number;
  end_hour: number;
  end_minute: number;
}
