/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorVersionChangeConflictsFields } from "./editorVersionChangeConflictsFields";

/**
 * Only on the version's page: the item is gone, or live values, which changed since.
 */
export type EditorVersionChangeConflicts = {
  missing?: boolean;
  fields?: EditorVersionChangeConflictsFields;
};
