/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorVersionChangeConflicts } from "./editorVersionChangeConflicts";
import type { EditorVersionChangeFields } from "./editorVersionChangeFields";
import type { EditorVersionChangeTargetType } from "./editorVersionChangeTargetType";
import type { EditorVersionLabel } from "./editorVersionLabel";

/**
 * Change of an item in a version: for each changed field, its live value from when it was
 *      *     planned and the new one.
 */
export interface EditorVersionChange {
  id: number;
  target_type: EditorVersionChangeTargetType;
  /**
   * None for a new item.
   * @nullable
   */
  target_id: number | null;
  /**
   * Where a new item goes.
   * @nullable
   */
  parent_id: number | null;
  is_new: boolean;
  fields: EditorVersionChangeFields;
  changes_count: number;
  label: EditorVersionLabel | null;
  /**
   * Only on a version's own page: `missing` when the item (or a new one's parent) is gone,
   *      *       `fields` with live values, which changed since they were planned.
   */
  conflicts?: EditorVersionChangeConflicts;
}
