/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorTranslations } from "./editorTranslations";

/**
 * A new one goes at the end of the list.
 */
export interface EditorStoreMenuRequest {
  title: EditorTranslations;
  description?: EditorTranslations;
  is_hidden?: boolean;
}
