/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type EditorReviewsResponseMeta = {
  current_page: number;
  last_page: number;
  per_page: number;
  total: number;
};
