/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorInterval } from "./editorInterval";

/**
 * Opening intervals by weekday, closed days have none.
 */
export interface EditorWeekdays {
  monday?: EditorInterval[];
  tuesday?: EditorInterval[];
  wednesday?: EditorInterval[];
  thursday?: EditorInterval[];
  friday?: EditorInterval[];
  saturday?: EditorInterval[];
  sunday?: EditorInterval[];
}
