/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorScheduleExceptionInput } from "./editorScheduleExceptionInput";
import type { EditorTranslations } from "./editorTranslations";
import type { EditorWeekdays } from "./editorWeekdays";

/**
 * Time zone, weekly hours, special days and the temporary closure. All of it is replaced.
 */
export interface EditorUpdateRestaurantHoursRequest {
  timezone: string;
  weekdays: EditorWeekdays;
  exceptions: EditorScheduleExceptionInput[];
  /** @nullable */
  closed_until?: string | null;
  closed_reason?: EditorTranslations;
}
