/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { EditorTranslations } from "./editorTranslations";

/**
 * Special day (or days), which overrides the weekly hours.
 */
export interface EditorScheduleException {
  id: number;
  starts_on: string;
  ends_on: string;
  is_closed: boolean;
  /** @nullable */
  beg_hour: number | null;
  /** @nullable */
  beg_minute: number | null;
  /** @nullable */
  end_hour: number | null;
  /** @nullable */
  end_minute: number | null;
  reason: EditorTranslations;
}
