/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { FamilyMemberRelation } from "./familyMemberRelation";
import type { Customer } from "./customer";

/**
 * Family member resource object
 */
export interface FamilyMember {
  id: number;
  type: string;
  name: string;
  relation: FamilyMemberRelation;
  birthdate: string;
  relative_id: number;
  relative?: Customer;
}
