/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type FamilyMemberRelation =
  (typeof FamilyMemberRelation)[keyof typeof FamilyMemberRelation];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FamilyMemberRelation = {
  child: "child",
  parent: "parent",
  grandparent: "grandparent",
  partner: "partner",
} as const;
