/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Coma-separated list of inluded relations.
    Available relations: `relative`
 */
export type FamilyMemberIncludes = string;
