/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type GetEditorReviewsStatus =
  (typeof GetEditorReviewsStatus)[keyof typeof GetEditorReviewsStatus];

export const GetEditorReviewsStatus = {
  pending: "pending",
  approved: "approved",
  rejected: "rejected",
} as const;
