/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type GetEditorVersionsParams = {
  /**
   * Only the ones, which haven't gone live.
   */
  pending?: boolean;
};
