/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { GetEditorReviewsStatus } from "./getEditorReviewsStatus";

export type GetEditorReviewsParams = {
  /**
   * The ones, which wait for approval, by default.
   */
  status?: GetEditorReviewsStatus;
  page?: number;
};
