/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type GetHolidaysParams = {
  /**
   * Number of days, for which holidays should be returned.
   */
  days?: string;
  /**
   * Date starting from which holidays should be returned.
   */
  from?: string;
};
