/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Holiday } from "./holiday";

/**
 * Get restaurant's holidays response object.
 */
export interface GetHolidaysResponse {
  data: Holiday[];
  message: string;
}
