/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type GetModelMediaParams = {
  /**
   * Id of the target model.
   */
  model_id: number;
  /**
   * Morph type of the target model.
   */
  model_type: string;
};
