/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Media } from "./media";

/**
 * Get model's media response object.
 */
export interface GetModelMediaResponse {
  data: Media[];
  message: string;
}
