/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { GetRestaurantReviewsSort } from "./getRestaurantReviewsSort";

export type GetRestaurantReviewsParams = {
  sort?: GetRestaurantReviewsSort;
  page?: number;
};
