/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type GetRestaurantReviewsSort =
  (typeof GetRestaurantReviewsSort)[keyof typeof GetRestaurantReviewsSort];

export const GetRestaurantReviewsSort = {
  newest: "newest",
  highest: "highest",
  lowest: "lowest",
} as const;
