/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type GetRestaurantDishesParams = {
  locale: string;
  /**
   * Of the snapshot the page knows: when it's the current one, the answer is cached for long.
   */
  hash?: string;
};
