/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Schedule } from "./schedule";

/**
 * Get restaurant's schedules response object.
 */
export interface GetSchedulesResponse {
  data: Schedule[];
  message: string;
}
