/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Holiday resource object
 */
export interface Holiday {
  id: number;
  type: string;
  name: string;
  /** @nullable */
  description: string | null;
  date: string;
  /** @nullable */
  closest_date?: string | null;
}
