/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { SpaceReservation } from "./spaceReservation";
import type { PaginationMeta } from "./paginationMeta";

/**
 * Index spaces reservations response object.
 */
export interface IndexSpaceReservationsResponse {
  data: SpaceReservation[];
  meta: PaginationMeta;
  message: string;
}
