/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { CategoryIncludes } from "./categoryIncludes";
import type { PageSize } from "./pageSize";
import type { PageNumber } from "./pageNumber";

export type IndexCategoriesParams = {
  include?: CategoryIncludes;
  "page[size]"?: PageSize;
  "page[number]"?: PageNumber;
  /**
   * Available sorts: `popularity` (is default, but in descending order)
   */
  sort?: string;
  /**
 * Coma-separated array of restaurant ids. Limits categories to those
         that are attached at least to one of those restaurants
 */
  "filter[restaurants]"?: string;
  /**
 * Coma-separated array of tag ids. Limits categories to those
         that have at least one of given tags attached to them
 */
  "filter[tags]"?: string;
  /**
   * Target class morph slug. Examples: `products`, `tickets`, `services`, `spaces`
   */
  "filter[target]"?: string;
};
