/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Tag } from "./tag";
import type { PaginationMeta } from "./paginationMeta";

/**
 * Index tags response object.
 */
export interface IndexTagResponse {
  data: Tag[];
  meta: PaginationMeta;
  message: string;
}
