/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { PaginationMeta } from "./paginationMeta";
import type { Restaurant } from "./restaurant";

/**
 * Index restaurant response object.
 */
export interface IndexRestaurantResponse {
  data: Restaurant[];
  meta: PaginationMeta;
  message: string;
}
