/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Notification } from "./notification";
import type { PaginationMeta } from "./paginationMeta";

/**
 * Index notifications response object.
 */
export interface IndexNotificationResponse {
  data: Notification[];
  meta: PaginationMeta;
  message: string;
}
