/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { PageNumber } from "./pageNumber";
import type { PageSize } from "./pageSize";

export type IndexTagsParams = {
  "page[size]"?: PageSize;
  "page[number]"?: PageNumber;
  /**
   * Coma-separated array of restaurant ids. Limits tags to those
   *          that are attached at least to one of those restaurants
   */
  "filter[restaurants]"?: string;
  /**
   * Target class morph slug. Examples: `products`
   */
  "filter[target]"?: string;
};
