/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { OrderIncludes } from "./orderIncludes";
import type { PageSize } from "./pageSize";
import type { PageNumber } from "./pageNumber";

export type IndexOrdersParams = {
  include?: OrderIncludes;
  "page[size]"?: PageSize;
  "page[number]"?: PageNumber;
};
