/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { PageSize } from "./pageSize";
import type { PageNumber } from "./pageNumber";
import type { DeletedParameter } from "./deletedParameter";

export type IndexWaitersParams = {
  /**
 * Coma-separated array of restaurant ids. Limits categories to those
            that are attached at least to one of those restaurants
 */
  "filter[restaurants]"?: string;
  /**
   * Allows to search `uuid`, `name`, `surname`, `phone` and `email` fields at the same time.
   */
  "filter[search]"?: string;
  "filter[uuid]"?: string;
  "filter[name]"?: string;
  "filter[surname]"?: string;
  "filter[phone]"?: string;
  "filter[email]"?: string;
  "page[size]"?: PageSize;
  "page[number]"?: PageNumber;
  deleted?: DeletedParameter;
};
