/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { DishCategoryIncludes } from "./dishCategoryIncludes";
import type { PageSize } from "./pageSize";
import type { PageNumber } from "./pageNumber";

export type IndexDishCategoriesParams = {
  include?: DishCategoryIncludes;
  "page[size]"?: PageSize;
  "page[number]"?: PageNumber;
  /**
   * Available sorts: `popularity` (is default, but in descending order)
   */
  sort?: string;
  /**
   * Menu ID to filter categories by.
   */
  "filter[menu_id]"?: string;
  /**
   * Target class morph slug. Examples: `dishes`
   */
  "filter[target]"?: string;
};
