/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type IndexSpacesReservationsParams = {
  /**
   * Id of current banquet's order (do not specify if order is just creating).
   */
  order_id?: number;
  start_at: string;
  /**
   * Must be after or equal to `start_at`. If not present then `start_at` will be taken.
   */
  end_at?: string;
};
