/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { TicketIncludes } from "./ticketIncludes";
import type { PageSize } from "./pageSize";
import type { PageNumber } from "./pageNumber";
import type { ArchivedParameter } from "./archivedParameter";

export type IndexTicketsParams = {
  include?: TicketIncludes;
  "page[size]"?: PageSize;
  "page[number]"?: PageNumber;
  /**
   * Available sorts: `popularity` (is default, but in descending order)
   */
  sort?: string;
  /**
   * Can be used for searches. Is partial.
   */
  "filter[title]"?: string;
  /**
   * Coma-separated array of category ids. Limits tickets to those
   * that have at least one of given categories attached to them
   */
  "filter[categories]"?: string;
  /**
   * Coma-separated array of restaurant ids. Limits tickets to those
   * that are attached at least to one of those restaurants
   */
  "filter[restaurants]"?: string;
  archived?: ArchivedParameter;
};
