/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Dish } from "./dish";
import type { PaginationMeta } from "./paginationMeta";

/**
 * Index dishes response object.
 */
export interface IndexDishResponse {
  data: Dish[];
  meta: PaginationMeta;
  message: string;
}
