/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Discount } from "./discount";
import type { PaginationMeta } from "./paginationMeta";

/**
 * Index discounts response object.
 */
export interface IndexDiscountResponse {
  data: Discount[];
  meta: PaginationMeta;
  message: string;
}
