/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { MediaIncludes } from "./mediaIncludes";
import type { PageNumber } from "./pageNumber";
import type { PageSize } from "./pageSize";

export type IndexMediaParams = {
  include?: MediaIncludes;
  "page[size]"?: PageSize;
  "page[number]"?: PageNumber;
  /**
   * Can be used for searches.
   */
  "filter[search]"?: string;
  /**
   * Can be used for searches. Is partial.
   */
  "filter[name]"?: string;
  /**
   * Can be used for searches. Is partial.
   */
  "filter[extension]"?: string;
  /**
   * Can be used for searches. Is partial.
   */
  "filter[disk]"?: string;
  /**
   * Can be used for searches. Is partial.
   */
  "filter[folder]"?: string;
};
