/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { FamilyMember } from "./familyMember";
import type { PaginationMeta } from "./paginationMeta";

/**
 * Index family members response object.
 */
export interface IndexFamilyMemberResponse {
  data: FamilyMember[];
  meta: PaginationMeta;
  message: string;
}
