/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Service } from "./service";
import type { PaginationMeta } from "./paginationMeta";

/**
 * Index services response object.
 */
export interface IndexServiceResponse {
  data: Service[];
  meta: PaginationMeta;
  message: string;
}
