/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Customer } from "./customer";
import type { PaginationMeta } from "./paginationMeta";

/**
 * Index customers response object.
 */
export interface IndexCustomerResponse {
  data: Customer[];
  meta: PaginationMeta;
  message: string;
}
