/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { PageNumber } from "./pageNumber";
import type { PageSize } from "./pageSize";

export type IndexRestaurantReviewsParams = {
  "page[size]"?: PageSize;
  "page[number]"?: PageNumber;
  /**
   * Available sorts: `created_at` (is default, but in descending order)
   */
  sort?: string;
  "filter[restaurant_id]"?: string;
  "filter[ip]"?: string;
  is_approved?: boolean;
};
