/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Ticket } from "./ticket";
import type { PaginationMeta } from "./paginationMeta";

/**
 * Index tickets response object.
 */
export interface IndexTicketResponse {
  data: Ticket[];
  meta: PaginationMeta;
  message: string;
}
