/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { PaginationMeta } from "./paginationMeta";
import type { Product } from "./product";

/**
 * Index products response object.
 */
export interface IndexProductResponse {
  data: Product[];
  meta: PaginationMeta;
  message: string;
}
