/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { DishVariant } from "./dishVariant";
import type { PaginationMeta } from "./paginationMeta";

/**
 * Index dish variants response object.
 */
export interface IndexDishVariantResponse {
  data: DishVariant[];
  meta: PaginationMeta;
  message: string;
}
