/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { PageNumber } from "./pageNumber";
import type { PageSize } from "./pageSize";

export type IndexUsersParams = {
  "page[size]"?: PageSize;
  "page[number]"?: PageNumber;
};
