/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { DishIncludes } from "./dishIncludes";
import type { PageSize } from "./pageSize";
import type { PageNumber } from "./pageNumber";
import type { ArchivedParameter } from "./archivedParameter";

export type IndexDishesParams = {
  include?: DishIncludes;
  "page[size]"?: PageSize;
  "page[number]"?: PageNumber;
  /**
   * Available sorts: `popularity` (is default, but in descending order)
   */
  sort?: string;
  /**
   * Coma-separated list of dish ids.
   */
  "filter[ids]"?: string;
  /**
   * Can be used for searches. Is partial.
   */
  "filter[title]"?: string;
  /**
   * Restaurant ID to filter dishes by.
   */
  "filter[restaurant_id]"?: string;
  /**
   * Menu ID to filter dishes by.
   */
  "filter[menu_id]"?: string;
  /**
   * Coma-separated list of menu ids.
   */
  "filter[menu_ids]"?: string;
  /**
   * Category ID to filter dishes by.
   */
  "filter[category_id]"?: string;
  archived?: ArchivedParameter;
};
