/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { PaginationMeta } from "./paginationMeta";
import type { RestaurantReview } from "./restaurantReview";

/**
 * Index restaurant reviews response object.
 */
export interface IndexRestaurantReviewResponse {
  data: RestaurantReview[];
  meta: PaginationMeta;
  message: string;
}
