/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { DishMenuIncludes } from "./dishMenuIncludes";
import type { PageSize } from "./pageSize";
import type { PageNumber } from "./pageNumber";
import type { ArchivedParameter } from "./archivedParameter";

export type IndexDishMenusParams = {
  include?: DishMenuIncludes;
  "page[size]"?: PageSize;
  "page[number]"?: PageNumber;
  /**
   * Available sorts: `popularity` (is default, but in descending order)
   */
  sort?: string;
  /**
   * Coma-separated array of restaurant ids. Limits menus to those
   * that are attached at least to one of those restaurants
   */
  "filter[restaurants]"?: string;
  archived?: ArchivedParameter;
};
