/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { DishMenu } from "./dishMenu";
import type { PaginationMeta } from "./paginationMeta";

/**
 * Index dish menus response object.
 */
export interface IndexDishMenuResponse {
  data: DishMenu[];
  meta: PaginationMeta;
  message: string;
}
