/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Product } from "./product";
import type { PaginationMeta } from "./paginationMeta";

/**
 * Index products response object.
 */
export interface IndexProductResponse {
  data: Product[];
  meta: PaginationMeta;
  message: string;
}
