/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { User } from "./user";
import type { PaginationMeta } from "./paginationMeta";

/**
 * Index users response object.
 */
export interface IndexUserResponse {
  data: User[];
  meta: PaginationMeta;
  message: string;
}
