/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Space } from "./space";
import type { PaginationMeta } from "./paginationMeta";

/**
 * Index spaces response object.
 */
export interface IndexSpaceResponse {
  data: Space[];
  meta: PaginationMeta;
  message: string;
}
