/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { BanquetIncludes } from "./banquetIncludes";
import type { PageSize } from "./pageSize";
import type { PageNumber } from "./pageNumber";
import type { DeletedParameter } from "./deletedParameter";

export type IndexBanquetsParams = {
  include?: BanquetIncludes;
  /**
 * Allows to search by banquet's `title` and customer's `name`, `surname`,
           `phone` and `email` at the same time
 */
  "filter[search]"?: string;
  "filter[restaurant_id]"?: number;
  "filter[state]"?: string;
  "filter[from]"?: string;
  "filter[until]"?: string;
  /**
   * Available fields: `start_at`, `created_at`, `updated_at`.
   */
  sort?: string;
  "page[size]"?: PageSize;
  "page[number]"?: PageNumber;
  deleted?: DeletedParameter;
};
