/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Waiter } from "./waiter";
import type { PaginationMeta } from "./paginationMeta";

/**
 * Index waiters response object.
 */
export interface IndexWaiterResponse {
  data: Waiter[];
  meta: PaginationMeta;
  message: string;
}
