/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { ProductIncludes } from "./productIncludes";
import type { PageSize } from "./pageSize";
import type { PageNumber } from "./pageNumber";
import type { ArchivedParameter } from "./archivedParameter";

export type IndexProductsParams = {
  include?: ProductIncludes;
  "page[size]"?: PageSize;
  "page[number]"?: PageNumber;
  /**
   * Available sorts: `popularity` (is default, but in descending order)
   */
  sort?: string;
  /**
   * Coma-separated list of product ids.
   */
  "filter[ids]"?: string;
  /**
   * Can be used for searches. Is partial.
   */
  "filter[title]"?: string;
  /**
 * Coma-separated array of menu ids. Limits products to those
         that are attached at least to one of given menus
 */
  "filter[menus]"?: string;
  /**
 * Coma-separated array of category ids. Limits products to those
         that have at least one of given categories attached to them
 */
  "filter[categories]"?: string;
  /**
 * Coma-separated array of tag ids. Limits products to those
         that have at least one of given tags attached to them
 */
  "filter[tags]"?: string;
  /**
 * Coma-separated array of restaurant ids. Limits products to those
         that are attached at least to one of those restaurants
 */
  "filter[restaurants]"?: string;
  archived?: ArchivedParameter;
};
