/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { DishCategory } from "./dishCategory";
import type { PaginationMeta } from "./paginationMeta";

/**
 * Index dish categories response object.
 */
export interface IndexDishCategoryResponse {
  data: DishCategory[];
  meta: PaginationMeta;
  message: string;
}
