/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { ArchivedParameter } from "./archivedParameter";
import type { MenuIncludes } from "./menuIncludes";
import type { PageNumber } from "./pageNumber";
import type { PageSize } from "./pageSize";

export type IndexMenusParams = {
  include?: MenuIncludes;
  "page[size]"?: PageSize;
  "page[number]"?: PageNumber;
  /**
   * Available sorts: `popularity` (is default, but in descending order)
   */
  sort?: string;
  /**
   * Coma-separated array of restaurant ids. Limits menus to those
   *      * that are attached at least to one of those restaurants
   */
  "filter[restaurants]"?: string;
  archived?: ArchivedParameter;
};
