/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { DishVariantIncludes } from "./dishVariantIncludes";
import type { PageSize } from "./pageSize";
import type { PageNumber } from "./pageNumber";

export type IndexDishVariantsParams = {
  include?: DishVariantIncludes;
  "page[size]"?: PageSize;
  "page[number]"?: PageNumber;
  /**
   * Available sorts: `price` (is default)
   */
  sort?: string;
  /**
   * Coma-separated list of dish variant ids.
   */
  "filter[ids]"?: string;
  /**
   * Dish ID to filter variants by.
   */
  "filter[dish_id]"?: string;
};
