/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { PageSize } from "./pageSize";
import type { PageNumber } from "./pageNumber";

export type IndexDiscountsParams = {
  "page[size]"?: PageSize;
  "page[number]"?: PageNumber;
  /**
   * Target class morph slug. Examples: `products`, `tickets`, `services`, `spaces`
   */
  "filter[target]"?: string;
};
