/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Restaurant } from "./restaurant";
import type { PaginationMeta } from "./paginationMeta";

/**
 * Index restaurant response object.
 */
export interface IndexRestaurantResponse {
  data: Restaurant[];
  meta: PaginationMeta;
  message: string;
}
