/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { PageNumber } from "./pageNumber";
import type { PageSize } from "./pageSize";

export type IndexCommentsParams = {
  "page[size]"?: PageSize;
  "page[number]"?: PageNumber;
  /**
   * Comment target morph lass id.
   */
  "filter[commentable_id]": number;
  /**
   * Comment target class slug. Examples: `customers`, `banquets`,
   *     `orders`, `product-field-orders`, `service-field-orders`, `space-field-orders`, `ticket-field-orders`
   */
  "filter[commentable_type]": string;
};
