/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Order } from "./order";
import type { PaginationMeta } from "./paginationMeta";

/**
 * Index orders response object.
 */
export interface IndexOrderResponse {
  data: Order[];
  meta: PaginationMeta;
  message: string;
}
