/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { FamilyMemberIncludes } from "./familyMemberIncludes";
import type { PageSize } from "./pageSize";
import type { PageNumber } from "./pageNumber";

export type IndexFamilyMembersParams = {
  include?: FamilyMemberIncludes;
  "page[size]"?: PageSize;
  "page[number]"?: PageNumber;
};
