/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { CustomerIncludes } from "./customerIncludes";
import type { PageSize } from "./pageSize";
import type { PageNumber } from "./pageNumber";
import type { DeletedParameter } from "./deletedParameter";

export type IndexCustomersParams = {
  include?: CustomerIncludes;
  /**
 * Available sorts: `name`, `surname`, `created_at`, `updated_at`
            (is default, but in descending order)
 */
  sort?: string;
  /**
   * Allows to search `name`, `surname`, `phone` and `email` fields at the same time.
   */
  "filter[search]"?: string;
  "filter[name]"?: string;
  "filter[surname]"?: string;
  "filter[phone]"?: string;
  "filter[email]"?: string;
  "page[size]"?: PageSize;
  "page[number]"?: PageNumber;
  deleted?: DeletedParameter;
};
