/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Pagination meta links object.
 */
export interface Links {
  first: string;
  /** @nullable */
  prev: string | null;
  self: string;
  /** @nullable */
  next: string | null;
  /** @nullable */
  last: string | null;
}
