/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { UserAndTokenResponse } from "./userAndTokenResponse";

/**
 * Login response object.
 */
export interface LoginResponse {
  data: UserAndTokenResponse;
  message: string;
}
