/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Supports login by credantials (`email` and `password`) and
    by remember token (`remember_token`).
 */
export interface LoginRequest {
  /** By credentials. Required with `password` */
  email?: string;
  /** By credentials. Required with `email` */
  password?: string;
  /** By remember token */
  remember_token?: string;
}
