/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Media metadata resource object
 */
export interface MediaMetadata {
  [key: string]: unknown;
}
