/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { MediaMetadataProperty } from "./mediaMetadataProperty";

/**
 * Media resource object
 */
export interface Media {
  id: number;
  type: string;
  name: string;
  mime?: string;
  extension: string;
  /** @nullable */
  title: string | null;
  /** @nullable */
  description: string | null;
  /** @nullable */
  disk: string | null;
  /** Must start and end with `/`. */
  folder: string;
  /** @nullable */
  order: number | null;
  url: string;
  /** @nullable */
  metadata: MediaMetadataProperty;
  variants?: Media[];
}
