/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { MediaMetadata } from "./mediaMetadata";

/**
 * Media resource object
 */
export interface Media {
  id: number;
  type: string;
  name: string;
  mime?: string;
  extension: string;
  /** @nullable */
  title: string | null;
  /** @nullable */
  description: string | null;
  /** @nullable */
  disk: string | null;
  /** Must start and end with `/`. */
  folder: string;
  /** @nullable */
  order: number | null;
  /** Hidden from guests (only the admin gets hidden ones). */
  is_hidden?: boolean;
  url: string;
  metadata: MediaMetadata | null;
  variants?: Media[];
}
