/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Category } from "./category";
import type { Media } from "./media";
import type { Product } from "./product";

/**
 * Menu resource object
 */
export interface Menu {
  id: number;
  type: string;
  title: string;
  description: string;
  archived: boolean;
  /** @nullable */
  popularity: number | null;
  products?: Product[];
  /** Categories that are attached directly to the menu. */
  categories: Category[];
  media: Media[];
}
