/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { MeIncludes } from "./meIncludes";

export type MeParams = {
  include?: MeIncludes;
};
