/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type MultipleInvoiceUrlRequestEndpoint =
  (typeof MultipleInvoiceUrlRequestEndpoint)[keyof typeof MultipleInvoiceUrlRequestEndpoint];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MultipleInvoiceUrlRequestEndpoint = {
  pdfMultiple: "pdfMultiple",
  viewMultiple: "viewMultiple",
} as const;
