/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { MultipleInvoiceUrlRequestEndpoint } from "./multipleInvoiceUrlRequestEndpoint";

/**
 * Generate url for accessing invoice for multiple orders request
 */
export interface MultipleInvoiceUrlRequest {
  ids?: string;
  endpoint?: MultipleInvoiceUrlRequestEndpoint;
}
