/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Reviews the device left: their ids and the device's token.
 */
export interface MyRestaurantReviewsRequest {
  client_token: string;
  /** @maxItems 50 */
  ids: number[];
}
