/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { RestaurantReview } from "./restaurantReview";

/**
 * The device's own reviews of the restaurant.
 */
export interface MyRestaurantReviewsResponse {
  data: RestaurantReview[];
  message: string;
}
