/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { NotificationPayload } from "./notificationPayload";

/**
 * Notification resource object
 */
export interface Notification {
  id: number;
  type: string;
  channel: string;
  subject: string;
  /** @nullable */
  body: string | null;
  /** @nullable */
  payload: NotificationPayload;
  /** @nullable */
  sender_id: number | null;
  receiver_id: number;
  send_at: string;
  /** @nullable */
  sent_at: string | null;
  /** @nullable */
  seen_at: string | null;
}
