/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Notifications poll resource object
 */
export interface NotificationsPoll {
  count: number;
}
