/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Coma-separated list of inluded relations. Available relations:
    `comments`, `spaces.comments`, `tickets.comments`, `products.comments`, `services.comments`
 */
export type OrderIncludes = string;
