/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Generate url for accessing order's invoice response.
 */
export interface OrderInvoiceUrlResponse {
  url: string;
  message: string;
}
