/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { OrderKind } from "./orderKind";
import type { OrderState } from "./orderState";
import type { OrderTotals } from "./orderTotals";
import type { SpaceOrderField } from "./spaceOrderField";
import type { TicketOrderField } from "./ticketOrderField";
import type { ProductOrderField } from "./productOrderField";
import type { ServiceOrderField } from "./serviceOrderField";
import type { Comment } from "./comment";
import type { Discount } from "./discount";

/**
 * Order resource object
 */
export interface Order {
  id: number;
  banquet_id: number;
  /** @nullable */
  slug: string | null;
  type: string;
  /** @nullable */
  kind: OrderKind;
  /** @nullable */
  state: OrderState;
  /** @nullable */
  recipient: string | null;
  /** @nullable */
  phone: string | null;
  /** @nullable */
  address: string | null;
  /** @nullable */
  delivery_time: string | null;
  /** @nullable */
  delivery_date: string | null;
  totals: OrderTotals;
  /** @nullable */
  invoice_url?: string | null;
  spaces?: SpaceOrderField[];
  tickets?: TicketOrderField[];
  products?: ProductOrderField[];
  services?: ServiceOrderField[];
  comments?: Comment[];
  discounts?: Discount[];
}
