/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type OrderInvoiceUrlRequestEndpoint =
  (typeof OrderInvoiceUrlRequestEndpoint)[keyof typeof OrderInvoiceUrlRequestEndpoint];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderInvoiceUrlRequestEndpoint = {
  pdf: "pdf",
  view: "view",
} as const;
