/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { OrderInvoiceUrlRequestEndpoint } from "./orderInvoiceUrlRequestEndpoint";

/**
 * Generate url for accessing order's invoice request
 */
export interface OrderInvoiceUrlRequest {
  endpoint?: OrderInvoiceUrlRequestEndpoint;
}
