/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * @nullable
 */
export type OrderState = (typeof OrderState)[keyof typeof OrderState] | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderState = {
  new: "new",
  confirmed: "confirmed",
  postponed: "postponed",
  cancelled: "cancelled",
  completed: "completed",
} as const;
