/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Order totals resource object
 */
export interface OrderTotals {
  all: number;
  spaces: number;
  tickets: number;
  services: number;
  products: number;
}
