/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type PollNotificationsParams = {
  /**
   * Optional, false by default (only unseen notifications).
   */
  seen?: boolean;
  /**
   * Optional, if true, then filters to notifications sent by system.
   */
  system?: boolean;
  sender_id?: number;
};
