/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { NotificationsPoll } from "./notificationsPoll";

/**
 * Poll notifications response object.
 */
export interface PollNotificationsResponse {
  data: NotificationsPoll;
  message: string;
}
