/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * @nullable
 */
export type ProductWeightUnit =
  (typeof ProductWeightUnit)[keyof typeof ProductWeightUnit] | null;

export const ProductWeightUnit = {
  g: "g",
  kg: "kg",
  ml: "ml",
  l: "l",
  cm: "cm",
} as const;
