/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type ProductVariantWeightUnit =
  (typeof ProductVariantWeightUnit)[keyof typeof ProductVariantWeightUnit];

export const ProductVariantWeightUnit = {
  g: "g",
  kg: "kg",
  ml: "ml",
  l: "l",
  cm: "cm",
} as const;
