/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * @nullable
 */
export type ProductHotness =
  (typeof ProductHotness)[keyof typeof ProductHotness] | null;

export const ProductHotness = {
  Unknown: "Unknown",
  Low: "Low",
  Medium: "Medium",
  High: "High",
  Ultra: "Ultra",
} as const;
