/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * @nullable
 */
export type ProductWeightUnit =
  | (typeof ProductWeightUnit)[keyof typeof ProductWeightUnit]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductWeightUnit = {
  g: "g",
  kg: "kg",
  ml: "ml",
  l: "l",
  cm: "cm",
} as const;
