/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { ProductWeightUnit } from "./productWeightUnit";
import type { ProductHotness } from "./productHotness";
import type { ProductVariant } from "./productVariant";
import type { Category } from "./category";
import type { Tag } from "./tag";
import type { Media } from "./media";
import type { Alternation } from "./alternation";

/**
 * Product resource object
 */
export interface Product {
  id: number;
  type: string;
  title: string;
  /** @nullable */
  description: string | null;
  price: number;
  /** @nullable */
  weight: number | null;
  /** @nullable */
  weight_unit: ProductWeightUnit;
  /** @nullable */
  badge: string | null;
  archived: boolean;
  /** @nullable */
  popularity: number | null;
  /** @nullable */
  preparation_time: number | null;
  /** @nullable */
  calories: number | null;
  /** @nullable */
  is_vegan: boolean | null;
  /** @nullable */
  is_vegetarian: boolean | null;
  /** @nullable */
  has_eggs: boolean | null;
  /** @nullable */
  has_nuts: boolean | null;
  /** @nullable */
  hotness: ProductHotness;
  variants: ProductVariant[];
  menu_ids: number[];
  categories: Category[];
  category_ids: number[];
  tags: Tag[];
  media: Media[];
  alterations?: Alternation[];
  pendingAlterations?: Alternation[];
  performedAlterations?: Alternation[];
}
