/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type ProductVariantWeightUnit =
  (typeof ProductVariantWeightUnit)[keyof typeof ProductVariantWeightUnit];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductVariantWeightUnit = {
  g: "g",
  kg: "kg",
  ml: "ml",
  l: "l",
  cm: "cm",
} as const;
