/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Comment } from "./comment";
import type { Discount } from "./discount";

/**
 * Product order field resource object
 */
export interface ProductOrderField {
  id: number;
  type: string;
  order_id: number;
  product_id: number;
  variant_id: number;
  /** @nullable */
  batch: string | null;
  amount: number;
  /**
   * 24-hours format time, HOURS:MINUTES
   * @nullable
   */
  serve_at: string | null;
  total: number;
  discounts_amount: number;
  discounts_percent: number;
  discounted_total: number;
  comments?: Comment[];
  discounts?: Discount[];
}
