/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { User } from "./user";

/**
 * Register user response object.
 */
export interface RegisterResponse {
  data: User;
  message: string;
}
