/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Register user request
 */
export interface RegisterRequest {
  name: string;
  surname?: string;
  email: string;
  /** @nullable */
  phone?: string | null;
  password: string;
  password_confirmation: string;
}
