/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Media } from "./media";
import type { Schedule } from "./schedule";
import type { ScheduleException } from "./scheduleException";

/**
 * Restaurant resource object
 */
export interface Restaurant {
  id: number;
  type: string;
  slug: string;
  name: string;
  country: string;
  city: string;
  place: string;
  full_address?: string;
  /** @nullable */
  phone: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  location: string | null;
  /** @nullable */
  website: string | null;
  timezone: string;
  /** Selected timezone offset in minutes. */
  timezone_offset: number;
  /** @nullable */
  locale: string | null;
  /** @nullable */
  currency: string | null;
  /** @nullable */
  establishment: string | null;
  /** @nullable */
  popularity: number | null;
  /** @nullable */
  notes: string[] | null;
  media: Media[];
  schedules: Schedule[];
  /** Special days from yesterday on. */
  exceptions: ScheduleException[];
  /**
   * Temporarily closed till this day (inclusive).
   * @nullable
   */
  closed_until: string | null;
  /** @nullable */
  closed_reason: string | null;
  /** @nullable */
  brand_primary: string | null;
  /**
   * Color of text on tints of the primary one.
   * @nullable
   */
  brand_primary_content: string | null;
}
