/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { RestaurantReviewStatus } from "./restaurantReviewStatus";

/**
 * A guest's review of a restaurant, in the language it was written in.
 */
export interface RestaurantReview {
  /**
   * None, when the review wasn't kept.
   * @nullable
   */
  id: number | null;
  /**
   * @minimum 1
   * @maximum 5
   */
  rating: number;
  /**
   * None for a guest, who didn't give it.
   * @nullable
   */
  name: string | null;
  /**
   * None for a rating only.
   * @nullable
   */
  text: string | null;
  /** @nullable */
  locale: string | null;
  /** Public reviews are approved; a guest sees the status of their own ones. */
  status: RestaurantReviewStatus;
  /** @nullable */
  created_at: string | null;
}
