/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { RestaurantReviewsSummaryRatingsItem } from "./restaurantReviewsSummaryRatingsItem";

/**
 * The approved reviews of a restaurant: their average, count and counts by rating (5 to 1).
 */
export interface RestaurantReviewsSummary {
  /**
   * To one decimal; none without reviews.
   * @nullable
   */
  average: number | null;
  count: number;
  ratings: RestaurantReviewsSummaryRatingsItem[];
}
