/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Product } from "./product";

/**
 * Restore product response object.
 */
export interface RestoreProductResponse {
  data: Product;
  message: string;
}
