/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Media } from "./media";
import type { Schedule } from "./schedule";

/**
 * Restaurant resource object
 */
export interface Restaurant {
  id: number;
  type: string;
  slug: string;
  name: string;
  country: string;
  city: string;
  place: string;
  full_address?: string;
  /** @nullable */
  phone: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  location: string | null;
  /** @nullable */
  website: string | null;
  timezone: string;
  /** Selected timezone offset in minutes. */
  timezone_offset: number;
  /** @nullable */
  locale: string | null;
  /** @nullable */
  currency: string | null;
  /** @nullable */
  popularity: number | null;
  /** @nullable */
  notes: string[] | null;
  media: Media[];
  schedules: Schedule[];
}
