/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Public reviews are approved; a guest sees the status of their own ones.
 */
export type RestaurantReviewStatus =
  (typeof RestaurantReviewStatus)[keyof typeof RestaurantReviewStatus];

export const RestaurantReviewStatus = {
  pending: "pending",
  approved: "approved",
  rejected: "rejected",
} as const;
