/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Restaurant review resource object
 */
export interface RestaurantReview {
  id: number;
  type: string;
  restaurant_id: number;
  ip: string;
  reviewer: string;
  /** Min value: `0`, max value: `5`. */
  score: number;
  /** @nullable */
  title: string | null;
  /** @nullable */
  description: string | null;
  /** @nullable */
  created_at: string | null;
  /** @nullable */
  updated_at: string | null;
}
