/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Coma-separated list of inluded relations.
 *             Available relations: `schedules`
 */
export type RestaurantIncludes = string;
