/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { RestaurantReview } from "./restaurantReview";
import type { RestaurantReviewsResponseMeta } from "./restaurantReviewsResponseMeta";
import type { RestaurantReviewsSummary } from "./restaurantReviewsSummary";

/**
 * A page of the restaurant's approved reviews, with their summary.
 */
export interface RestaurantReviewsResponse {
  data: RestaurantReview[];
  meta: RestaurantReviewsResponseMeta;
  summary: RestaurantReviewsSummary;
  message: string;
}
