/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { RestaurantReview } from "./restaurantReview";

/**
 * The review, which was left.
 */
export interface RestaurantReviewResponse {
  data: RestaurantReview;
  message: string;
}
