/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Banquet } from "./banquet";

/**
 * Restore banquet response object.
 */
export interface RestoreBanquetResponse {
  data: Banquet;
  message: string;
}
