/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { ScheduleWeekday } from "./scheduleWeekday";

/**
 * Schedule resource object
 */
export interface Schedule {
  id: number;
  type: string;
  weekday: ScheduleWeekday;
  /** Start hour of the day [0 ; 23]. */
  beg_hour: number;
  /** End hour of the day [0 ; 23]. If less then beg_hour it,
   *   then it meens that it's a cross day schedule */
  end_hour: number;
  /** Start minute of the day [0 ; 59]. */
  beg_minute: number;
  /** End minute of the day [0 ; 59]. */
  end_minute: number;
  /** @nullable */
  restaurant_id: number | null;
  /**
   * Number of minutes untill the restaurant starts operating.
     If null then restaurant is already operating on this schedule.
   * @nullable
   */
  begs_in: number | null;
  /**
   * Number of minutes untill the restaurant ends operating.
   * @nullable
   */
  ends_in: number | null;
  is_cross_date: boolean;
  /** @nullable */
  closest_date: string | null;
  /** @nullable */
  timezone: string | null;
  /**
   * Minutes offset from UTC, which is already applied to `closest_date`
   * @nullable
   */
  timezone_offset: number | null;
  archived: boolean;
}
