/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type ScheduleForUpdateRestaurantRequestWeekday =
  (typeof ScheduleForUpdateRestaurantRequestWeekday)[keyof typeof ScheduleForUpdateRestaurantRequestWeekday];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScheduleForUpdateRestaurantRequestWeekday = {
  monday: "monday",
  tuesday: "tuesday",
  wednesday: "wednesday",
  thursday: "thursday",
  friday: "friday",
  saturday: "saturday",
  sunday: "sunday",
} as const;
