/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { ScheduleForUpdateRestaurantRequestWeekday } from "./scheduleForUpdateRestaurantRequestWeekday";

/**
 * Request body for updating restaurant's schedules details
 */
export interface ScheduleForUpdateRestaurantRequest {
  weekday: ScheduleForUpdateRestaurantRequestWeekday;
  /** Start hour of the day [0 ; 23]. */
  beg_hour: number;
  /** End hour of the day [0 ; 23]. If less then beg_hour it,
   *   then it meens that it's a cross day schedule */
  end_hour: number;
  /** Start minute of the day [0 ; 59]. */
  beg_minute: number;
  /** End minute of the day [0 ; 59]. */
  end_minute: number;
  archived: boolean;
}
