/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { DishCategory } from "./dishCategory";

/**
 * Show dish category response object.
 */
export interface ShowDishCategoryResponse {
  data: DishCategory;
  message: string;
}
