/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Notification } from "./notification";

/**
 * Show notification response object.
 */
export interface ShowNotificationResponse {
  data: Notification;
  message: string;
}
