/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Order } from "./order";

/**
 * Show order response object.
 */
export interface ShowOrderResponse {
  data: Order;
  message: string;
}
