/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { TicketIncludes } from "./ticketIncludes";

export type ShowTicketParams = {
  include?: TicketIncludes;
};
