/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Show invoice request
 */
export interface ShowInvoiceRequest {
  /** @nullable */
  tags?: string | null;
  /** @nullable */
  menus?: string | null;
  /**
   * Coma-separated list of invoice sections.
   *     Available sections: `info`, `comments`, `tickets`, `menus`,
   *     `spaces`, `services`
   * @nullable
   */
  sections?: string | null;
}
