/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Space } from "./space";

/**
 * Show spaces response object.
 */
export interface ShowSpaceResponse {
  data: Space;
  message: string;
}
