/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Product } from "./product";

/**
 * Show products response object.
 */
export interface ShowProductResponse {
  data: Product;
  message: string;
}
