/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { DishMenu } from "./dishMenu";

/**
 * Show dish menu response object.
 */
export interface ShowDishMenuResponse {
  data: DishMenu;
  message: string;
}
