/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Dish } from "./dish";

/**
 * Show dish response object.
 */
export interface ShowDishResponse {
  data: Dish;
  message: string;
}
