/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Show invoice for multiple orders request
 */
export interface ShowMultipleInvoiceRequest {
  ids?: string;
  /** @nullable */
  tags?: string | null;
  /** @nullable */
  menus?: string | null;
  /**
   * Coma-separated list of invoice sections.
   *     Available sections: `info`, `comments`, `tickets`, `menus`,
   *     `spaces`, `services`
   * @nullable
   */
  sections?: string | null;
}
