/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { DishCategoryIncludes } from "./dishCategoryIncludes";

export type ShowDishCategoryParams = {
  include?: DishCategoryIncludes;
};
