/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { MenuIncludes } from "./menuIncludes";

export type ShowMenuParams = {
  include?: MenuIncludes;
};
