/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Ticket } from "./ticket";

/**
 * Show tickets response object.
 */
export interface ShowTicketResponse {
  data: Ticket;
  message: string;
}
