/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Tag } from "./tag";

/**
 * Show tag response object.
 */
export interface ShowTagResponse {
  data: Tag;
  message: string;
}
