/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { DishVariant } from "./dishVariant";

/**
 * Show dish variant response object.
 */
export interface ShowDishVariantResponse {
  data: DishVariant;
  message: string;
}
