/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Category } from "./category";

/**
 * Show category response object.
 */
export interface ShowCategoryResponse {
  data: Category;
  message: string;
}
