/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Discount } from "./discount";

/**
 * Show discount response object.
 */
export interface ShowDiscountResponse {
  data: Discount;
  message: string;
}
