/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Customer } from "./customer";

/**
 * Show customer response object.
 */
export interface ShowCustomerResponse {
  data: Customer;
  message: string;
}
