/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { DishIncludes } from "./dishIncludes";

export type ShowDishParams = {
  include?: DishIncludes;
};
