/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { ProductIncludes } from "./productIncludes";

export type ShowProductParams = {
  include?: ProductIncludes;
};
