/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Banquet } from "./banquet";

/**
 * Show banquet response object.
 */
export interface ShowBanquetResponse {
  data: Banquet;
  message: string;
}
