/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { DishVariantIncludes } from "./dishVariantIncludes";

export type ShowDishVariantParams = {
  include?: DishVariantIncludes;
};
