/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Comment } from "./comment";

/**
 * Show comment response object.
 */
export interface ShowCommentResponse {
  data: Comment;
  message: string;
}
