/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { RestaurantReview } from "./restaurantReview";

/**
 * Show restaurant review response object.
 */
export interface ShowRestaurantReviewResponse {
  data: RestaurantReview;
  message: string;
}
