/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Space reservation resource object
 */
export interface SpaceReservation {
  type: string;
  order_id: number;
  space_id: number;
  start_at: string;
  end_at: string;
  duration: number;
}
