/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Category } from "./category";
import type { Media } from "./media";

/**
 * Space resource object
 */
export interface Space {
  id: number;
  type: string;
  title: string;
  description: string;
  floor: number;
  number: number;
  price: number;
  archived: boolean;
  /** @nullable */
  popularity: number | null;
  categories?: Category[];
  category_ids: number[];
  media: Media[];
}
