/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type StoreMediaRequestDisk =
  (typeof StoreMediaRequestDisk)[keyof typeof StoreMediaRequestDisk];

export const StoreMediaRequestDisk = {
  public: "public",
  uploads: "uploads",
} as const;
