/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { StoreProductRequestWeightUnit } from "./storeProductRequestWeightUnit";
import type { StoreProductRequestMetadata } from "./storeProductRequestMetadata";
import type { StoreProductRequestHotness } from "./storeProductRequestHotness";

/**
 * Store product request.
 */
export interface StoreProductRequest {
  restaurant_id: number;
  /**
   * Must be unique within the restaurant.
   * @nullable
   */
  slug?: string | null;
  /** @nullable */
  badge?: string | null;
  title: string;
  /** @nullable */
  description?: string | null;
  price: number;
  weight?: number;
  weight_unit?: StoreProductRequestWeightUnit;
  archived?: boolean;
  popularity?: number;
  /** @nullable */
  metadata?: StoreProductRequestMetadata;
  /** @nullable */
  preparation_time?: number | null;
  /** @nullable */
  calories?: number | null;
  /** @nullable */
  is_vegan?: boolean | null;
  /** @nullable */
  is_vegetarian?: boolean | null;
  /** @nullable */
  has_eggs?: boolean | null;
  /** @nullable */
  has_nuts?: boolean | null;
  /** @nullable */
  hotness?: StoreProductRequestHotness;
}
