/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * @nullable
 */
export type StoreProductRequestHotness =
  | (typeof StoreProductRequestHotness)[keyof typeof StoreProductRequestHotness]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StoreProductRequestHotness = {
  Unknown: "Unknown",
  Low: "Low",
  Medium: "Medium",
  High: "High",
  Ultra: "Ultra",
} as const;
