/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { FamilyMember } from "./familyMember";

/**
 * Store family member response object.
 */
export interface StoreFamilyMemberResponse {
  data: FamilyMember;
  message: string;
}
