/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * @nullable
 */
export type StoreBanquetRequestAdvanceAmountPaymentMethod =
  | (typeof StoreBanquetRequestAdvanceAmountPaymentMethod)[keyof typeof StoreBanquetRequestAdvanceAmountPaymentMethod]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StoreBanquetRequestAdvanceAmountPaymentMethod = {
  card: "card",
  cash: "cash",
} as const;
