/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type StoreProductRequestWeightUnit =
  (typeof StoreProductRequestWeightUnit)[keyof typeof StoreProductRequestWeightUnit];

export const StoreProductRequestWeightUnit = {
  g: "g",
  kg: "kg",
  ml: "ml",
  l: "l",
  cm: "cm",
  pc: "pc",
} as const;
