/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { AttachingComment } from "./attachingComment";
import type { AttachingDiscount } from "./attachingDiscount";

/**
 * Store order request product field
 */
export interface StoreOrderRequestProductField {
  product_id: number;
  variant_id: number;
  /** @nullable */
  batch?: string | null;
  amount: number;
  /**
   * 24-hours format time, HOURS:MINUTES
   * @nullable
   */
  serve_at?: string | null;
  comments?: AttachingComment[];
  discounts?: AttachingDiscount[];
}
