/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type StoreBanquetRequestState =
  (typeof StoreBanquetRequestState)[keyof typeof StoreBanquetRequestState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StoreBanquetRequestState = {
  new: "new",
} as const;
