/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { StoreMediaRequest } from "./storeMediaRequest";

export type StoreMediaBody = StoreMediaRequest & {
  /** File */
  file?: Blob | File;
};
