/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { AttachingComment } from "./attachingComment";
import type { AttachingDiscount } from "./attachingDiscount";

/**
 * Store order request service field
 */
export interface StoreOrderRequestServiceField {
  service_id: number;
  amount: number;
  /** Duration of the service rental in minutes. */
  duration: number;
  comments?: AttachingComment[];
  discounts?: AttachingDiscount[];
}
