/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { StoreMediaRequestDisk } from "./storeMediaRequestDisk";
import type { StoreMediaRequestMetadata } from "./storeMediaRequestMetadata";

/**
 * Store media request
 */
export interface StoreMediaRequest {
  file: Blob;
  name: string;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  disk?: StoreMediaRequestDisk;
  /** Must start and end with the `/`. */
  folder?: string;
  /** @nullable */
  metadata?: StoreMediaRequestMetadata;
}
