/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * @nullable
 */
export type StoreFamilyMemberRequestRelation =
  | (typeof StoreFamilyMemberRequestRelation)[keyof typeof StoreFamilyMemberRequestRelation]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StoreFamilyMemberRequestRelation = {
  child: "child",
  parent: "parent",
  grandparent: "grandparent",
  partner: "partner",
} as const;
