/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * @nullable
 */
export type StoreOrderRequestKind =
  | (typeof StoreOrderRequestKind)[keyof typeof StoreOrderRequestKind]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StoreOrderRequestKind = {
  delivery: "delivery",
  banquet: "banquet",
} as const;
