/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Media } from "./media";

/**
 * Store media response object.
 */
export interface StoreMediaResponse {
  data: Media;
  message: string;
}
