/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type StoreNotificationRequestChannel =
  (typeof StoreNotificationRequestChannel)[keyof typeof StoreNotificationRequestChannel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StoreNotificationRequestChannel = {
  default: "default",
} as const;
