/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { AttachingComment } from "./attachingComment";
import type { AttachingDiscount } from "./attachingDiscount";

/**
 * Store order request space field
 */
export interface StoreOrderRequestSpaceField {
  space_id: number;
  comments?: AttachingComment[];
  discounts?: AttachingDiscount[];
}
