/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * A guest's review: it waits for the restaurant to approve it.
 */
export interface StoreRestaurantReviewRequest {
  /**
   * @minimum 1
   * @maximum 5
   */
  rating: number;
  /**
   * None posts it as a guest.
   * @maxLength 40
   * @nullable
   */
  name?: string | null;
  /**
   * @maxLength 1000
   * @nullable
   */
  text?: string | null;
  /** The language it's written in. */
  locale: string;
  /**
   * A random token of the guest's device: it asks for the status of its reviews with it.
   * @minLength 16
   * @maxLength 100
   */
  client_token: string;
  /**
   * A field guests don't see: when it's filled in, the review isn't kept.
   * @nullable
   */
  website?: string | null;
}
