/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Dish } from "./dish";

/**
 * Store dish response object.
 */
export interface StoreDishResponse {
  data: Dish;
  message: string;
}
