/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { StoreNotificationRequestPayload } from "./storeNotificationRequestPayload";
import type { StoreNotificationRequestChannel } from "./storeNotificationRequestChannel";

/**
 * Store notification request
 */
export interface StoreNotificationRequest {
  subject: string;
  body: string;
  /** @nullable */
  payload: StoreNotificationRequestPayload;
  receiver_id: number;
  channel?: StoreNotificationRequestChannel;
  /** Date and time when notification should be sent. Only future values are acceptable. */
  send_at?: string;
}
