/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { StoreOrderRequestKind } from "./storeOrderRequestKind";
import type { StoreOrderRequestState } from "./storeOrderRequestState";
import type { StoreOrderRequestSpaceField } from "./storeOrderRequestSpaceField";
import type { StoreOrderRequestTicketField } from "./storeOrderRequestTicketField";
import type { StoreOrderRequestServiceField } from "./storeOrderRequestServiceField";
import type { StoreOrderRequestProductField } from "./storeOrderRequestProductField";
import type { AttachingComment } from "./attachingComment";
import type { AttachingDiscount } from "./attachingDiscount";

/**
 * Store order request
 */
export interface StoreOrderRequest {
  banquet_id?: number;
  /** @nullable */
  slug?: string | null;
  /** @nullable */
  kind?: StoreOrderRequestKind;
  /** @nullable */
  state?: StoreOrderRequestState;
  /** @nullable */
  recipient?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  address?: string | null;
  /** @nullable */
  delivery_time?: string | null;
  /** @nullable */
  delivery_date?: string | null;
  spaces?: StoreOrderRequestSpaceField[];
  tickets?: StoreOrderRequestTicketField[];
  services?: StoreOrderRequestServiceField[];
  products?: StoreOrderRequestProductField[];
  comments?: AttachingComment[];
  discounts?: AttachingDiscount[];
}
