/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type StoreProductRequestWeightUnit =
  (typeof StoreProductRequestWeightUnit)[keyof typeof StoreProductRequestWeightUnit];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StoreProductRequestWeightUnit = {
  g: "g",
  kg: "kg",
  ml: "ml",
  l: "l",
  cm: "cm",
  pc: "pc",
} as const;
