/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { RestaurantReview } from "./restaurantReview";

/**
 * Store restaurant review response object.
 */
export interface StoreRestaurantReviewResponse {
  data: RestaurantReview;
  message: string;
}
