/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Store restaurant review request
 */
export interface StoreRestaurantReviewRequest {
  restaurant_id: number;
  ip: string;
  reviewer: string;
  /** Min value: `0`, max value: `5`. */
  score: number;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
}
