/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type StoreNotificationRequestChannel =
  (typeof StoreNotificationRequestChannel)[keyof typeof StoreNotificationRequestChannel];

export const StoreNotificationRequestChannel = {
  default: "default",
} as const;
