/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Store comment request
 */
export interface StoreCommentRequest {
  text: string;
  commentable_id: number;
  /** Value for it must be obrained from the target resource's type property. */
  commentable_type: string;
}
