/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Store customer request. `email` or `phone`
           must be specified.
 */
export interface StoreCustomerRequest {
  /** @nullable */
  restaurant_id: number | null;
  name: string;
  surname: string;
  /** @nullable */
  email: string | null;
  /**
   * Phone number may start with a plus and must contain only digits 0-9.
   * @nullable
   */
  phone: string | null;
  /** @nullable */
  birthdate: string | null;
}
