/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type StoreMediaRequestDisk =
  (typeof StoreMediaRequestDisk)[keyof typeof StoreMediaRequestDisk];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StoreMediaRequestDisk = {
  public: "public",
  uploads: "uploads",
} as const;
