/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Notification } from "./notification";

/**
 * Store notification response object.
 */
export interface StoreNotificationResponse {
  data: Notification;
  message: string;
}
