/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { StoreFamilyMemberRequestRelation } from "./storeFamilyMemberRequestRelation";

/**
 * Store family member request
 */
export interface StoreFamilyMemberRequest {
  name: string;
  /** @nullable */
  relation: StoreFamilyMemberRequestRelation;
  birthdate: string;
  /** The id of the customer, who is related to this family member. */
  relative_id: number;
}
