/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Comment } from "./comment";

/**
 * Store comment response object.
 */
export interface StoreCommentResponse {
  data: Comment;
  message: string;
}
