/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { StoreMediaRequest } from "./storeMediaRequest";
import type { StoreMediaBodyAllOf } from "./storeMediaBodyAllOf";

export type StoreMediaBody = StoreMediaRequest & StoreMediaBodyAllOf;
