/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Tag resource object
 */
export interface Tag {
  id: number;
  type: string;
  /** @nullable */
  target: string | null;
  title: string;
  description: unknown;
}
