/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { TagDescription } from "./tagDescription";

/**
 * Tag resource object
 */
export interface Tag {
  id: number;
  type: string;
  /** @nullable */
  target: string | null;
  title: string;
  /** @nullable */
  description: TagDescription;
}
