/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Comment } from "./comment";
import type { Discount } from "./discount";

/**
 * Ticket order field resource object
 */
export interface TicketOrderField {
  id: number;
  type: string;
  order_id: number;
  ticket_id: number;
  amount: number;
  total: number;
  discounts_amount: number;
  discounts_percent: number;
  discounted_total: number;
  comments?: Comment[];
  discounts?: Discount[];
}
