/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Coma-separated list of inluded relations.
    Available relations: `categories`
 */
export type TicketIncludes = string;
