/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Restaurant } from "./restaurant";

/**
 * Tip resource object
 */
export interface Tip {
  id: number;
  /** @nullable */
  restaurant_id: number | null;
  type: string;
  amount: number;
  /** @nullable */
  commission: number | null;
  /** @nullable */
  about: string | null;
  restaurant?: Restaurant;
}
