/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type UpdateProductRequestWeightUnit =
  (typeof UpdateProductRequestWeightUnit)[keyof typeof UpdateProductRequestWeightUnit];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateProductRequestWeightUnit = {
  g: "g",
  kg: "kg",
  ml: "ml",
  l: "l",
  cm: "cm",
  pc: "pc",
} as const;
