/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { UpdateProductRequestWeightUnit } from "./updateProductRequestWeightUnit";
import type { UpdateProductRequestMetadata } from "./updateProductRequestMetadata";
import type { UpdateProductRequestHotness } from "./updateProductRequestHotness";

/**
 * Update product request.
 */
export interface UpdateProductRequest {
  restaurant_id?: number;
  /**
   * Must be unique within the restaurant.
   * @nullable
   */
  slug?: string | null;
  /** @nullable */
  badge?: string | null;
  title?: string;
  /** @nullable */
  description?: string | null;
  price?: number;
  weight?: number;
  weight_unit?: UpdateProductRequestWeightUnit;
  archived?: boolean;
  popularity?: number;
  /** @nullable */
  metadata?: UpdateProductRequestMetadata;
  /** @nullable */
  preparation_time?: number | null;
  /** @nullable */
  calories?: number | null;
  /** @nullable */
  is_vegan?: boolean | null;
  /** @nullable */
  is_vegetarian?: boolean | null;
  /** @nullable */
  is_low_calorie?: boolean | null;
  /** @nullable */
  has_eggs?: boolean | null;
  /** @nullable */
  has_nuts?: boolean | null;
  /** @nullable */
  hotness?: UpdateProductRequestHotness;
}
