/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { RestaurantIncludes } from "./restaurantIncludes";

export type UpdateRestaurantParams = {
  include?: RestaurantIncludes;
};
