/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Update customer request
 */
export interface UpdateCustomerRequest {
  /** @nullable */
  restaurant_id?: number | null;
  name?: string;
  surname?: string;
  email?: string;
  /** Phone number may start with a plus and must contain only digits 0-9. */
  phone?: string;
  birthdate?: string;
}
