/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Update comment request
 */
export interface UpdateCommentRequest {
  text: string;
}
