/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Update user request
 */
export interface UpdateUserRequest {
  name?: string;
  email?: string;
  /** This is a new password. It must be different than the current one. */
  password?: string;
  /** This is a current password. It is needed in order to perform
     authorization. Required with `password`. */
  current_password?: string;
}
