/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Product } from "./product";

/**
 * Update product response object.
 */
export interface UpdateProductResponse {
  data: Product;
  message: string;
}
