/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Restaurant } from "./restaurant";

/**
 * Update restaurant response object.
 */
export interface UpdateRestaurantResponse {
  data: Restaurant;
  message: string;
}
