/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Waiter } from "./waiter";

/**
 * Update waiter response object.
 */
export interface UpdateWaiterResponse {
  data: Waiter;
  message: string;
}
