/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type UpdateFamilyMemberRequestRelation =
  (typeof UpdateFamilyMemberRequestRelation)[keyof typeof UpdateFamilyMemberRequestRelation];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateFamilyMemberRequestRelation = {
  child: "child",
  parent: "parent",
  grandparent: "grandparent",
  partner: "partner",
} as const;
