/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * @nullable
 */
export type UpdateProductRequestHotness =
  | (typeof UpdateProductRequestHotness)[keyof typeof UpdateProductRequestHotness]
  | null;

export const UpdateProductRequestHotness = {
  Unknown: "Unknown",
  Low: "Low",
  Medium: "Medium",
  High: "High",
  Ultra: "Ultra",
} as const;
