/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * @nullable
 */
export type UpdateNotificationRequestPayload = {
  [key: string]: unknown;
} | null;
