/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { UpdateBanquetRequestAdvanceAmountPaymentMethod } from "./updateBanquetRequestAdvanceAmountPaymentMethod";
import type { AttachingComment } from "./attachingComment";
import type { AttachingDiscount } from "./attachingDiscount";

/**
 * Update banquet request
 */
export interface UpdateBanquetRequest {
  /**
   * If null, then title will be autogenerated as Banquet-ID.
   * @nullable
   */
  title?: string | null;
  description?: string;
  /** Banquet state available changes depends on current state.
           All states: `new`, `confirmed`, `postponed`, `cancelled`, `completed`. */
  state?: string;
  creator_id?: number;
  customer_id?: number;
  /** @nullable */
  restaurant_id?: number | null;
  advance_amount?: number;
  /** @nullable */
  actual_total?: number | null;
  /** @nullable */
  advance_amount_payment_method?: UpdateBanquetRequestAdvanceAmountPaymentMethod;
  /** @nullable */
  is_birthday_club?: boolean | null;
  /** @nullable */
  with_photographer?: boolean | null;
  /** @nullable */
  children_amount?: number | null;
  /** @nullable */
  child_ticket_price?: number | null;
  children_amounts?: number[];
  child_ticket_prices?: unknown[];
  /** @nullable */
  adults_amount?: number | null;
  /** @nullable */
  adult_ticket_price?: number | null;
  /** Date and time of when banquet should start. */
  start_at?: string;
  /** Date and time of when banquet should end. Must be after or equal to `start_at`. */
  end_at?: string;
  /**
   * Date and time of when banquet was fully paid for.
   * @nullable
   */
  paid_at?: string | null;
  comments?: AttachingComment[];
  discounts?: AttachingDiscount[];
}
