/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { UpdateFamilyMemberRequestRelation } from "./updateFamilyMemberRequestRelation";

/**
 * Update family member request
 */
export interface UpdateFamilyMemberRequest {
  name?: string;
  relation?: UpdateFamilyMemberRequestRelation;
  birthdate?: string;
  /** The id of the customer, who is related to this family member. */
  relative_id?: number;
}
