/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * Update waiter request.
 */
export interface UpdateWaiterRequest {
  /** @nullable */
  restaurant_id?: number | null;
  /** @nullable */
  uuid?: string | null;
  name?: string;
  surname?: string;
  /** @nullable */
  email?: string | null;
  /**
   * Phone number may start with a plus and must contain only digits 0-9.
   * @nullable
   */
  phone?: string | null;
  /** @nullable */
  birthdate?: string | null;
  /** @nullable */
  about?: string | null;
}
