/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { ScheduleForUpdateRestaurantRequest } from "./scheduleForUpdateRestaurantRequest";

/**
 * Request body for updating restaurant details
 */
export interface UpdateRestaurantRequest {
  /** The name of the restaurant. */
  name?: string;
  /**
   * The country where the restaurant is located.
   * @nullable
   */
  country?: string | null;
  /**
   * The city where the restaurant is located.
   * @nullable
   */
  city?: string | null;
  /**
   * Additional information about the restaurant's location.
   * @nullable
   */
  place?: string | null;
  /**
   * The contact phone number of the restaurant.
   * @nullable
   */
  phone?: string | null;
  schedules?: ScheduleForUpdateRestaurantRequest[];
}
