/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { User } from "./user";

/**
 * Update user response object.
 */
export interface UpdateUserResponse {
  data: User;
  message: string;
}
