/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { UpdateNotificationRequestPayload } from "./updateNotificationRequestPayload";

/**
 * Update notification request
 */
export interface UpdateNotificationRequest {
  subject?: string;
  body?: string;
  /** @nullable */
  payload?: UpdateNotificationRequestPayload;
  /** Date and time when notification should be sent. Only future values are acceptable. */
  send_at?: string;
}
