/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

export type UpdateDishRequestWeightUnit =
  (typeof UpdateDishRequestWeightUnit)[keyof typeof UpdateDishRequestWeightUnit];

export const UpdateDishRequestWeightUnit = {
  g: "g",
  kg: "kg",
  ml: "ml",
  l: "l",
  cm: "cm",
  pc: "pc",
} as const;
