/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { Customer } from "./customer";

/**
 * User resource object
 */
export interface User {
  id: number;
  type: string;
  /** @nullable */
  restaurant_id: number | null;
  /** @nullable */
  customer_id: number | null;
  name: string;
  /** @nullable */
  email: string | null;
  /** @nullable */
  email_verified_at: string | null;
  customer?: Customer;
}
