/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */

/**
 * User resource object
 */
export interface User {
  id: number;
  type: string;
  /** @nullable */
  restaurant_id: number | null;
  name: string;
  /** @nullable */
  email: string | null;
  /** @nullable */
  email_verified_at: string | null;
}
