/**
 * Generated by orval 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { User } from "./user";

/**
 * User and token response object.
 */
export interface UserAndTokenResponse {
  token: string;
  user: User;
}
