/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * imperia-api
 * OpenAPI spec version: 0.1
 */
import type { ValidationErrorsResponseErrors } from "./validationErrorsResponseErrors";

/**
 * Validation errors response object.
 */
export interface ValidationErrorsResponse {
  message: string;
  errors: ValidationErrorsResponseErrors;
}
