<?php

namespace Database\Seeders\Voyager;

use Illuminate\Database\Seeder;

class VoyagerDataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('data_rows')->delete();

        \DB::table('data_rows')->insert(array (
            0 =>
            array (
                'id' => 1,
                'data_type_id' => 1,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            1 =>
            array (
                'id' => 2,
                'data_type_id' => 1,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            2 =>
            array (
                'id' => 3,
                'data_type_id' => 1,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            3 =>
            array (
                'id' => 4,
                'data_type_id' => 1,
                'field' => 'password',
                'type' => 'password',
                'display_name' => 'Password',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            4 =>
            array (
                'id' => 5,
                'data_type_id' => 1,
                'field' => 'remember_token',
                'type' => 'text',
                'display_name' => 'Remember Token',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 5,
            ),
            5 =>
            array (
                'id' => 6,
                'data_type_id' => 1,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 6,
            ),
            6 =>
            array (
                'id' => 7,
                'data_type_id' => 1,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 7,
            ),
            7 =>
            array (
                'id' => 8,
                'data_type_id' => 1,
                'field' => 'avatar',
                'type' => 'image',
                'display_name' => 'Avatar',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 8,
            ),
            8 =>
            array (
                'id' => 9,
                'data_type_id' => 1,
                'field' => 'user_belongsto_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Role',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"roles","pivot":0}',
                'order' => 10,
            ),
            9 =>
            array (
                'id' => 10,
                'data_type_id' => 1,
                'field' => 'user_belongstomany_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Roles',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"0"}',
                'order' => 11,
            ),
            10 =>
            array (
                'id' => 11,
                'data_type_id' => 1,
                'field' => 'settings',
                'type' => 'hidden',
                'display_name' => 'Settings',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 12,
            ),
            11 =>
            array (
                'id' => 12,
                'data_type_id' => 2,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            12 =>
            array (
                'id' => 13,
                'data_type_id' => 2,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            13 =>
            array (
                'id' => 14,
                'data_type_id' => 2,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 3,
            ),
            14 =>
            array (
                'id' => 15,
                'data_type_id' => 2,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            15 =>
            array (
                'id' => 16,
                'data_type_id' => 3,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            16 =>
            array (
                'id' => 17,
                'data_type_id' => 3,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            17 =>
            array (
                'id' => 18,
                'data_type_id' => 3,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 3,
            ),
            18 =>
            array (
                'id' => 19,
                'data_type_id' => 3,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            19 =>
            array (
                'id' => 20,
                'data_type_id' => 3,
                'field' => 'display_name',
                'type' => 'text',
                'display_name' => 'Display Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 5,
            ),
            20 =>
            array (
                'id' => 21,
                'data_type_id' => 1,
                'field' => 'role_id',
                'type' => 'text',
                'display_name' => 'Role',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 9,
            ),
            21 =>
            array (
                'id' => 22,
                'data_type_id' => 7,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            22 =>
            array (
                'id' => 23,
                'data_type_id' => 7,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:2","max:50"],"messages":{"required":":attribute field is required.","min":":attribute field minimum length is :min characters.","max":":attribute field maximum length is :max characters."}}}',
                'order' => 2,
            ),
            23 =>
            array (
                'id' => 24,
                'data_type_id' => 7,
                'field' => 'description',
                'type' => 'text',
                'display_name' => 'Description',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["nullable","min:2","max:100"],"messages":{"min":":attribute field minimum length is :min characters.","max":":attribute field maximum length is :max characters."}}}',
                'order' => 3,
            ),
            24 =>
            array (
                'id' => 25,
                'data_type_id' => 8,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            25 =>
            array (
                'id' => 26,
                'data_type_id' => 8,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:2","max:50"]}}',
                'order' => 2,
            ),
            26 =>
            array (
                'id' => 27,
                'data_type_id' => 8,
                'field' => 'description',
                'type' => 'text',
                'display_name' => 'Description',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["nullable","min:2","max:100"]}}',
                'order' => 3,
            ),
            27 =>
            array (
                'id' => 28,
                'data_type_id' => 8,
                'field' => 'price',
                'type' => 'number',
                'display_name' => 'Price',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","numeric","min:0"]}}',
                'order' => 4,
            ),
            28 =>
            array (
                'id' => 29,
                'data_type_id' => 8,
                'field' => 'category_id',
                'type' => 'number',
                'display_name' => 'Category Id',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required"]}}',
                'order' => 10,
            ),
            29 =>
            array (
                'id' => 30,
                'data_type_id' => 8,
                'field' => 'period_id',
                'type' => 'number',
                'display_name' => 'Period Id',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 9,
            ),
            30 =>
            array (
                'id' => 31,
                'data_type_id' => 8,
                'field' => 'created_at',
                'type' => 'text',
                'display_name' => 'Created At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            31 =>
            array (
                'id' => 32,
                'data_type_id' => 8,
                'field' => 'updated_at',
                'type' => 'text',
                'display_name' => 'Updated At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            32 =>
            array (
                'id' => 34,
                'data_type_id' => 7,
                'field' => 'ticket_category_hasone_ticket_relationship',
                'type' => 'relationship',
                'display_name' => 'Tickets',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Ticket","table":"tickets","type":"hasMany","column":"category_id","key":"id","label":"name","pivot_table":"banquet_state_change_log","pivot":"0","taggable":"0"}',
                'order' => 4,
            ),
            33 =>
            array (
                'id' => 35,
                'data_type_id' => 8,
                'field' => 'ticket_belongsto_ticket_category_relationship',
                'type' => 'relationship',
                'display_name' => 'Category',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Categories\\\\TicketCategory","table":"ticket_categories","type":"belongsTo","column":"category_id","key":"id","label":"name","pivot_table":"banquet_state_change_log","pivot":"0","taggable":"0"}',
                'order' => 5,
            ),
            34 =>
            array (
                'id' => 36,
                'data_type_id' => 8,
                'field' => 'ticket_belongsto_period_relationship',
                'type' => 'relationship',
                'display_name' => 'Period',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Period","table":"periods","type":"belongsTo","column":"period_id","key":"id","label":"id","pivot_table":"banquet_state_change_log","pivot":"0","taggable":"0"}',
                'order' => 6,
            ),
            35 =>
            array (
                'id' => 37,
                'data_type_id' => 9,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            36 =>
            array (
                'id' => 38,
                'data_type_id' => 9,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            37 =>
            array (
                'id' => 39,
                'data_type_id' => 9,
                'field' => 'description',
                'type' => 'text',
                'display_name' => 'Description',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            38 =>
            array (
                'id' => 40,
                'data_type_id' => 9,
                'field' => 'once_paid_price',
                'type' => 'text',
                'display_name' => 'Once Paid Price',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["nullable","required_without:hourly_paid_price"]}}',
                'order' => 6,
            ),
            39 =>
            array (
                'id' => 41,
                'data_type_id' => 9,
                'field' => 'hourly_paid_price',
                'type' => 'text',
                'display_name' => 'Hourly Paid Price',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["nullable","required_without:once_paid_price"]}}',
                'order' => 7,
            ),
            40 =>
            array (
                'id' => 42,
                'data_type_id' => 9,
                'field' => 'category_id',
                'type' => 'number',
                'display_name' => 'Category Id',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required"]}}',
                'order' => 2,
            ),
            41 =>
            array (
                'id' => 43,
                'data_type_id' => 9,
                'field' => 'period_id',
                'type' => 'number',
                'display_name' => 'Period Id',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            42 =>
            array (
                'id' => 44,
                'data_type_id' => 9,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            43 =>
            array (
                'id' => 45,
                'data_type_id' => 9,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            44 =>
            array (
                'id' => 46,
                'data_type_id' => 9,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            45 =>
            array (
                'id' => 53,
                'data_type_id' => 13,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            46 =>
            array (
                'id' => 54,
                'data_type_id' => 13,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:2","max:50"],"messages":{"required":":attribute field is required.","min":":attribute field minimum length is :min characters.","max":":attribute field maximum length is :max characters."}}}',
                'order' => 2,
            ),
            47 =>
            array (
                'id' => 55,
                'data_type_id' => 13,
                'field' => 'description',
                'type' => 'text',
                'display_name' => 'Description',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["nullable","min:2","max:100"],"messages":{"min":":attribute field minimum length is :min characters.","max":":attribute field maximum length is :max characters."}}}',
                'order' => 3,
            ),
            48 =>
            array (
                'id' => 56,
                'data_type_id' => 13,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            49 =>
            array (
                'id' => 57,
                'data_type_id' => 13,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            50 =>
            array (
                'id' => 58,
                'data_type_id' => 13,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            51 =>
            array (
                'id' => 71,
                'data_type_id' => 16,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            52 =>
            array (
                'id' => 72,
                'data_type_id' => 16,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:2","max:50"],"messages":{"required":":attribute field is required.","min":":attribute field minimum length is :min characters.","max":":attribute field maximum length is :max characters."}}}',
                'order' => 2,
            ),
            53 =>
            array (
                'id' => 73,
                'data_type_id' => 16,
                'field' => 'description',
                'type' => 'text',
                'display_name' => 'Description',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["nullable","min:2","max:100"],"messages":{"min":":attribute field minimum length is :min characters.","max":":attribute field maximum length is :max characters."}}}',
                'order' => 3,
            ),
            54 =>
            array (
                'id' => 74,
                'data_type_id' => 16,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            55 =>
            array (
                'id' => 75,
                'data_type_id' => 16,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            56 =>
            array (
                'id' => 76,
                'data_type_id' => 16,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            57 =>
            array (
                'id' => 77,
                'data_type_id' => 17,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            58 =>
            array (
                'id' => 78,
                'data_type_id' => 17,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:2","max:50"],"messages":{"required":":attribute field is required.","min":":attribute field minimum length is :min characters.","max":":attribute field maximum length is :max characters."}}}',
                'order' => 2,
            ),
            59 =>
            array (
                'id' => 79,
                'data_type_id' => 17,
                'field' => 'description',
                'type' => 'text',
                'display_name' => 'Description',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["nullable","min:2","max:100"],"messages":{"min":":attribute field minimum length is :min characters.","max":":attribute field maximum length is :max characters."}}}',
                'order' => 3,
            ),
            60 =>
            array (
                'id' => 80,
                'data_type_id' => 17,
                'field' => 'created_at',
                'type' => 'text',
                'display_name' => 'Created At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            61 =>
            array (
                'id' => 81,
                'data_type_id' => 17,
                'field' => 'updated_at',
                'type' => 'text',
                'display_name' => 'Updated At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            62 =>
            array (
                'id' => 82,
                'data_type_id' => 17,
                'field' => 'deleted_at',
                'type' => 'text',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            63 =>
            array (
                'id' => 83,
                'data_type_id' => 18,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            64 =>
            array (
                'id' => 84,
                'data_type_id' => 18,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:2","max:50"]}}',
                'order' => 4,
            ),
            65 =>
            array (
                'id' => 85,
                'data_type_id' => 18,
                'field' => 'description',
                'type' => 'text',
                'display_name' => 'Description',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["nullable","min:2","max:100"]}}',
                'order' => 5,
            ),
            66 =>
            array (
                'id' => 86,
                'data_type_id' => 18,
                'field' => 'period_id',
                'type' => 'number',
                'display_name' => 'Period Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            67 =>
            array (
                'id' => 87,
                'data_type_id' => 18,
                'field' => 'category_id',
                'type' => 'number',
                'display_name' => 'Category Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required"]}}',
                'order' => 3,
            ),
            68 =>
            array (
                'id' => 88,
                'data_type_id' => 18,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            69 =>
            array (
                'id' => 89,
                'data_type_id' => 18,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            70 =>
            array (
                'id' => 90,
                'data_type_id' => 18,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            71 =>
            array (
                'id' => 91,
                'data_type_id' => 17,
                'field' => 'menu_category_hasmany_imperia_menu_relationship',
                'type' => 'relationship',
                'display_name' => 'Imperia Menus',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\ImperiaMenu","table":"imperia_menus","type":"hasMany","column":"category_id","key":"id","label":"name","pivot_table":"banquet_state_change_log","pivot":"0","taggable":"0"}',
                'order' => 4,
            ),
            72 =>
            array (
                'id' => 92,
                'data_type_id' => 18,
                'field' => 'imperia_menu_belongsto_menu_category_relationship',
                'type' => 'relationship',
                'display_name' => 'Category',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Categories\\\\MenuCategory","table":"menu_categories","type":"belongsTo","column":"category_id","key":"id","label":"name","pivot_table":"banquet_state_change_log","pivot":"0","taggable":"0"}',
                'order' => 6,
            ),
            73 =>
            array (
                'id' => 93,
                'data_type_id' => 19,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            74 =>
            array (
                'id' => 94,
                'data_type_id' => 19,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:2","max:50"]}}',
                'order' => 4,
            ),
            75 =>
            array (
                'id' => 95,
                'data_type_id' => 19,
                'field' => 'description',
                'type' => 'text',
                'display_name' => 'Description',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["nullable","min:2","max:100"]}}',
                'order' => 5,
            ),
            76 =>
            array (
                'id' => 96,
                'data_type_id' => 19,
                'field' => 'price',
                'type' => 'number',
                'display_name' => 'Price',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","numeric","min:0"]}}',
                'order' => 6,
            ),
            77 =>
            array (
                'id' => 97,
                'data_type_id' => 19,
                'field' => 'weight',
                'type' => 'number',
                'display_name' => 'Weight',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["nullable","min:0"]}}',
                'order' => 7,
            ),
            78 =>
            array (
                'id' => 98,
                'data_type_id' => 19,
                'field' => 'menu_id',
                'type' => 'number',
                'display_name' => 'Menu Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required"]}}',
                'order' => 2,
            ),
            79 =>
            array (
                'id' => 99,
                'data_type_id' => 19,
                'field' => 'category_id',
                'type' => 'number',
                'display_name' => 'Category Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required"]}}',
                'order' => 3,
            ),
            80 =>
            array (
                'id' => 100,
                'data_type_id' => 19,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            81 =>
            array (
                'id' => 101,
                'data_type_id' => 19,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            82 =>
            array (
                'id' => 102,
                'data_type_id' => 19,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            83 =>
            array (
                'id' => 103,
                'data_type_id' => 19,
                'field' => 'product_belongsto_product_category_relationship',
                'type' => 'relationship',
                'display_name' => 'Category',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Categories\\\\ProductCategory","table":"product_categories","type":"belongsTo","column":"category_id","key":"id","label":"name","pivot_table":"banquet_state_change_log","pivot":"0","taggable":"0"}',
                'order' => 8,
            ),
            84 =>
            array (
                'id' => 104,
                'data_type_id' => 19,
                'field' => 'product_belongsto_menu_category_relationship',
                'type' => 'relationship',
                'display_name' => 'Menu',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\ImperiaMenu","table":"imperia_menus","type":"belongsTo","column":"menu_id","key":"id","label":"name","pivot_table":"banquet_state_change_log","pivot":"0","taggable":"0"}',
                'order' => 9,
            ),
            85 =>
            array (
                'id' => 105,
                'data_type_id' => 8,
                'field' => 'deleted_at',
                'type' => 'text',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            86 =>
            array (
                'id' => 106,
                'data_type_id' => 21,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            87 =>
            array (
                'id' => 107,
                'data_type_id' => 21,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:2","max:50"],"messages":{"required":":attribute field is required.","min":":attribute field minimum length is :min characters.","max":":attribute field maximum length is :max characters."}}}',
                'order' => 2,
            ),
            88 =>
            array (
                'id' => 108,
                'data_type_id' => 21,
                'field' => 'description',
                'type' => 'text',
                'display_name' => 'Description',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["nullable","min:2","max:100"],"messages":{"min":":attribute field minimum length is :min characters.","max":":attribute field maximum length is :max characters."}}}',
                'order' => 3,
            ),
            89 =>
            array (
                'id' => 109,
                'data_type_id' => 21,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            90 =>
            array (
                'id' => 110,
                'data_type_id' => 21,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            91 =>
            array (
                'id' => 111,
                'data_type_id' => 21,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            92 =>
            array (
                'id' => 112,
                'data_type_id' => 22,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            93 =>
            array (
                'id' => 113,
                'data_type_id' => 22,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:2","max:50"]}}',
                'order' => 4,
            ),
            94 =>
            array (
                'id' => 114,
                'data_type_id' => 22,
                'field' => 'number',
                'type' => 'number',
                'display_name' => 'Number',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","numeric","min:0"]}}',
                'order' => 5,
            ),
            95 =>
            array (
                'id' => 115,
                'data_type_id' => 22,
                'field' => 'floor',
                'type' => 'number',
                'display_name' => 'Floor',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","numeric"]}}',
                'order' => 6,
            ),
            96 =>
            array (
                'id' => 116,
                'data_type_id' => 22,
                'field' => 'description',
                'type' => 'text',
                'display_name' => 'Description',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["nullable","min:2","max:100"]}}',
                'order' => 7,
            ),
            97 =>
            array (
                'id' => 117,
                'data_type_id' => 22,
                'field' => 'price',
                'type' => 'number',
                'display_name' => 'Price',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["min:0"]}}',
                'order' => 8,
            ),
            98 =>
            array (
                'id' => 118,
                'data_type_id' => 22,
                'field' => 'category_id',
                'type' => 'number',
                'display_name' => 'Category Id',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required"]}}',
                'order' => 2,
            ),
            99 =>
            array (
                'id' => 119,
                'data_type_id' => 22,
                'field' => 'period_id',
                'type' => 'number',
                'display_name' => 'Period Id',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            100 =>
            array (
                'id' => 120,
                'data_type_id' => 22,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            101 =>
            array (
                'id' => 121,
                'data_type_id' => 22,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            102 =>
            array (
                'id' => 122,
                'data_type_id' => 22,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 13,
            ),
            103 =>
            array (
                'id' => 123,
                'data_type_id' => 21,
                'field' => 'space_category_hasmany_space_relationship',
                'type' => 'relationship',
                'display_name' => 'Spaces',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\Models\\\\Space","table":"spaces","type":"hasMany","column":"category_id","key":"id","label":"name","pivot_table":"banquet_state_change_log","pivot":"0","taggable":"0"}',
                'order' => 4,
            ),
            104 =>
            array (
                'id' => 124,
                'data_type_id' => 22,
                'field' => 'space_belongsto_space_category_relationship',
                'type' => 'relationship',
                'display_name' => 'Category',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Categories\\\\SpaceCategory","table":"space_categories","type":"belongsTo","column":"category_id","key":"id","label":"name","pivot_table":"banquet_state_change_log","pivot":"0","taggable":"0"}',
                'order' => 9,
            ),
            105 =>
            array (
                'id' => 125,
                'data_type_id' => 22,
                'field' => 'space_belongsto_period_relationship',
                'type' => 'relationship',
                'display_name' => 'Period',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Period","table":"periods","type":"belongsTo","column":"period_id","key":"id","label":"id","pivot_table":"banquet_state_change_log","pivot":"0","taggable":"0"}',
                'order' => 10,
            ),
            106 =>
            array (
                'id' => 126,
                'data_type_id' => 7,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            107 =>
            array (
                'id' => 127,
                'data_type_id' => 7,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            108 =>
            array (
                'id' => 128,
                'data_type_id' => 7,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            109 =>
            array (
                'id' => 129,
                'data_type_id' => 9,
                'field' => 'service_belongsto_service_category_relationship',
                'type' => 'relationship',
                'display_name' => 'Category',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Categories\\\\ServiceCategory","table":"service_categories","type":"belongsTo","column":"id","key":"id","label":"name","pivot_table":"banquet_state_change_log","pivot":"0","taggable":"0"}',
                'order' => 8,
            ),
            110 =>
            array (
                'id' => 130,
                'data_type_id' => 23,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            111 =>
            array (
                'id' => 131,
                'data_type_id' => 23,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:2","max:50"]}}',
                'order' => 2,
            ),
            112 =>
            array (
                'id' => 132,
                'data_type_id' => 23,
                'field' => 'description',
                'type' => 'text',
                'display_name' => 'Description',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["nullable","min:2","max:100"]}}',
                'order' => 3,
            ),
            113 =>
            array (
                'id' => 133,
                'data_type_id' => 23,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            114 =>
            array (
                'id' => 134,
                'data_type_id' => 23,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            115 =>
            array (
                'id' => 135,
                'data_type_id' => 23,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            116 =>
            array (
                'id' => 136,
                'data_type_id' => 23,
                'field' => 'discount_category_hasmany_discount_relationship',
                'type' => 'relationship',
                'display_name' => 'Discounts',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Discount","table":"discounts","type":"hasMany","column":"category_id","key":"id","label":"name","pivot_table":"banquet_state_change_log","pivot":"0","taggable":"0"}',
                'order' => 4,
            ),
            117 =>
            array (
                'id' => 137,
                'data_type_id' => 24,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            118 =>
            array (
                'id' => 138,
                'data_type_id' => 24,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:2","max:50"]}}',
                'order' => 4,
            ),
            119 =>
            array (
                'id' => 139,
                'data_type_id' => 24,
                'field' => 'description',
                'type' => 'text',
                'display_name' => 'Description',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["nullable","min:2","max:100"]}}',
                'order' => 5,
            ),
            120 =>
            array (
                'id' => 140,
                'data_type_id' => 24,
                'field' => 'amount',
                'type' => 'number',
                'display_name' => 'Amount',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required_if:percent,null","min:0"]}}',
                'order' => 6,
            ),
            121 =>
            array (
                'id' => 141,
                'data_type_id' => 24,
                'field' => 'percent',
                'type' => 'number',
                'display_name' => 'Percent',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required_if:amount,null","min:0","max:100"]}}',
                'order' => 7,
            ),
            122 =>
            array (
                'id' => 142,
                'data_type_id' => 24,
                'field' => 'category_id',
                'type' => 'number',
                'display_name' => 'Category Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required"]}}',
                'order' => 2,
            ),
            123 =>
            array (
                'id' => 143,
                'data_type_id' => 24,
                'field' => 'period_id',
                'type' => 'number',
                'display_name' => 'Period Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            124 =>
            array (
                'id' => 144,
                'data_type_id' => 24,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            125 =>
            array (
                'id' => 145,
                'data_type_id' => 24,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            126 =>
            array (
                'id' => 146,
                'data_type_id' => 24,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            127 =>
            array (
                'id' => 147,
                'data_type_id' => 24,
                'field' => 'discount_belongsto_discount_category_relationship',
                'type' => 'relationship',
                'display_name' => 'Category',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Categories\\\\DiscountCategory","table":"discount_categories","type":"belongsTo","column":"category_id","key":"id","label":"name","pivot_table":"banquet_state_change_log","pivot":"0","taggable":"0"}',
                'order' => 8,
            ),
            128 =>
            array (
                'id' => 148,
                'data_type_id' => 24,
                'field' => 'discount_belongsto_period_relationship',
                'type' => 'relationship',
                'display_name' => 'Period',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\Models\\\\Period","table":"periods","type":"belongsTo","column":"period_id","key":"id","label":"id","pivot_table":"banquet_state_change_log","pivot":"0","taggable":"0"}',
                'order' => 9,
            ),
            129 =>
            array (
                'id' => 149,
                'data_type_id' => 25,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            130 =>
            array (
                'id' => 150,
                'data_type_id' => 25,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:2","max:50"]}}',
                'order' => 2,
            ),
            131 =>
            array (
                'id' => 151,
                'data_type_id' => 25,
                'field' => 'description',
                'type' => 'text',
                'display_name' => 'Description',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["nullable","min:2","max:100"]}}',
                'order' => 3,
            ),
            132 =>
            array (
                'id' => 152,
                'data_type_id' => 25,
                'field' => 'can_read',
                'type' => 'checkbox',
                'display_name' => 'Allowed To Read',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"on":"On","off":"Off","checked":true}',
                'order' => 5,
            ),
            133 =>
            array (
                'id' => 153,
                'data_type_id' => 25,
                'field' => 'can_insert',
                'type' => 'checkbox',
                'display_name' => 'Allowed To Insert',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"on":"On","off":"Off","checked":false}',
                'order' => 6,
            ),
            134 =>
            array (
                'id' => 154,
                'data_type_id' => 25,
                'field' => 'can_modify',
                'type' => 'checkbox',
                'display_name' => 'Allowed To Modify',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"on":"On","off":"Off","checked":false}',
                'order' => 7,
            ),
            135 =>
            array (
                'id' => 155,
                'data_type_id' => 25,
                'field' => 'is_owner',
                'type' => 'checkbox',
                'display_name' => 'Is Owner',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"on":"On","off":"Off","checked":false}',
                'order' => 8,
            ),
            136 =>
            array (
                'id' => 156,
                'data_type_id' => 25,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            137 =>
            array (
                'id' => 157,
                'data_type_id' => 25,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            138 =>
            array (
                'id' => 158,
                'data_type_id' => 25,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            139 =>
            array (
                'id' => 159,
                'data_type_id' => 26,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            140 =>
            array (
                'id' => 160,
                'data_type_id' => 26,
                'field' => 'role_id',
                'type' => 'number',
                'display_name' => 'Role Id',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            141 =>
            array (
                'id' => 161,
                'data_type_id' => 26,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:2","max:50"]}}',
                'order' => 3,
            ),
            142 =>
            array (
                'id' => 162,
                'data_type_id' => 26,
                'field' => 'password',
                'type' => 'text',
                'display_name' => 'Password',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":["required","min:8","max:50"]}}',
                'order' => 4,
            ),
            143 =>
            array (
                'id' => 163,
                'data_type_id' => 26,
                'field' => 'api_token',
                'type' => 'text',
                'display_name' => 'Api Token',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            144 =>
            array (
                'id' => 164,
                'data_type_id' => 26,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            145 =>
            array (
                'id' => 165,
                'data_type_id' => 26,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            146 =>
            array (
                'id' => 166,
                'data_type_id' => 26,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            147 =>
            array (
                'id' => 167,
                'data_type_id' => 26,
                'field' => 'imperia_user_belongsto_imperia_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Role',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\ImperiaRole","table":"imperia_roles","type":"belongsTo","column":"role_id","key":"id","label":"name","pivot_table":"banquet_state_change_log","pivot":"0","taggable":"0"}',
                'order' => 6,
            ),
            148 =>
            array (
                'id' => 168,
                'data_type_id' => 25,
                'field' => 'imperia_role_hasmany_imperia_user_relationship',
                'type' => 'relationship',
                'display_name' => 'Users',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\Models\\\\ImperiaUser","table":"imperia_users","type":"hasMany","column":"role_id","key":"id","label":"name","pivot_table":"banquet_state_change_log","pivot":"0","taggable":"0"}',
                'order' => 4,
            ),
        ));
    }
}
