<?php

namespace Database\Seeders\Voyager;

use Illuminate\Database\Seeder;

class VoyagerDataTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('data_types')->delete();

        \DB::table('data_types')->insert(array (
            0 =>
            array (
                'id' => 1,
                'name' => 'users',
                'slug' => 'users',
                'display_name_singular' => 'User',
                'display_name_plural' => 'Users',
                'icon' => 'voyager-person',
                'model_name' => 'TCG\\Voyager\\Models\\User',
                'policy_name' => 'TCG\\Voyager\\Policies\\UserPolicy',
                'controller' => 'TCG\\Voyager\\Http\\Controllers\\VoyagerUserController',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2021-05-27 11:51:32',
                'updated_at' => '2021-05-27 11:51:32',
            ),
            1 =>
            array (
                'id' => 2,
                'name' => 'menus',
                'slug' => 'menus',
                'display_name_singular' => 'Menu',
                'display_name_plural' => 'Menus',
                'icon' => 'voyager-list',
                'model_name' => 'TCG\\Voyager\\Models\\Menu',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2021-05-27 11:51:32',
                'updated_at' => '2021-05-27 11:51:32',
            ),
            2 =>
            array (
                'id' => 3,
                'name' => 'roles',
                'slug' => 'roles',
                'display_name_singular' => 'Role',
                'display_name_plural' => 'Roles',
                'icon' => 'voyager-lock',
                'model_name' => 'TCG\\Voyager\\Models\\Role',
                'policy_name' => NULL,
                'controller' => 'TCG\\Voyager\\Http\\Controllers\\VoyagerRoleController',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2021-05-27 11:51:32',
                'updated_at' => '2021-05-27 11:51:32',
            ),
            3 =>
            array (
                'id' => 7,
                'name' => 'ticket_categories',
                'slug' => 'ticket-categories',
                'display_name_singular' => 'Ticket Category',
                'display_name_plural' => 'Ticket Categories',
                'icon' => 'voyager-ticket',
                'model_name' => 'App\\Models\\Categories\\TicketCategory',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":"id","order_display_column":"id","order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2021-05-27 12:47:59',
                'updated_at' => '2021-05-31 07:33:08',
            ),
            4 =>
            array (
                'id' => 8,
                'name' => 'tickets',
                'slug' => 'tickets',
                'display_name_singular' => 'Ticket',
                'display_name_plural' => 'Tickets',
                'icon' => 'voyager-ticket',
                'model_name' => 'App\\Models\\Ticket',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":"category_id","order_display_column":"name","order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2021-05-27 12:53:05',
                'updated_at' => '2021-06-06 17:46:55',
            ),
            5 =>
            array (
                'id' => 9,
                'name' => 'services',
                'slug' => 'services',
                'display_name_singular' => 'Service',
                'display_name_plural' => 'Services',
                'icon' => 'voyager-pirate',
                'model_name' => 'App\\Models\\Service',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":"id","order_display_column":"name","order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2021-05-30 06:04:50',
                'updated_at' => '2021-06-06 17:48:39',
            ),
            6 =>
            array (
                'id' => 13,
                'name' => 'service_categories',
                'slug' => 'service-categories',
                'display_name_singular' => 'Service Category',
                'display_name_plural' => 'Service Categories',
                'icon' => 'voyager-pirate',
                'model_name' => 'App\\Models\\Categories\\ServiceCategory',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2021-05-30 06:09:37',
                'updated_at' => '2021-05-30 06:09:37',
            ),
            7 =>
            array (
                'id' => 16,
                'name' => 'product_categories',
                'slug' => 'product-categories',
                'display_name_singular' => 'Product Category',
                'display_name_plural' => 'Product Categories',
                'icon' => 'voyager-pizza',
                'model_name' => 'App\\Models\\Categories\\ProductCategory',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":"id","order_display_column":"id","order_direction":"asc","default_search_key":null}',
                'created_at' => '2021-05-30 06:19:59',
                'updated_at' => '2021-05-30 06:19:59',
            ),
            8 =>
            array (
                'id' => 17,
                'name' => 'menu_categories',
                'slug' => 'menu-categories',
                'display_name_singular' => 'Menu Category',
                'display_name_plural' => 'Menu Categories',
                'icon' => 'voyager-documentation',
                'model_name' => 'App\\Models\\Categories\\MenuCategory',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":"id","order_display_column":"id","order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2021-05-30 06:21:46',
                'updated_at' => '2021-05-31 07:32:20',
            ),
            9 =>
            array (
                'id' => 18,
                'name' => 'imperia_menus',
                'slug' => 'imperia-menus',
                'display_name_singular' => 'Imperia Menu',
                'display_name_plural' => 'Imperia Menus',
                'icon' => 'voyager-documentation',
                'model_name' => 'App\\Models\\ImperiaMenu',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":"id","order_display_column":"id","order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2021-05-30 06:23:39',
                'updated_at' => '2021-06-06 17:40:39',
            ),
            10 =>
            array (
                'id' => 19,
                'name' => 'products',
                'slug' => 'products',
                'display_name_singular' => 'Product',
                'display_name_plural' => 'Products',
                'icon' => 'voyager-pizza',
                'model_name' => 'App\\Models\\Product',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":"id","order_display_column":"name","order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2021-05-30 06:31:05',
                'updated_at' => '2021-06-06 17:44:46',
            ),
            11 =>
            array (
                'id' => 21,
                'name' => 'space_categories',
                'slug' => 'space-categories',
                'display_name_singular' => 'Space Category',
                'display_name_plural' => 'Space Categories',
                'icon' => 'voyager-lighthouse',
                'model_name' => 'App\\Models\\Categories\\SpaceCategory',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":"id","order_display_column":"name","order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2021-05-31 07:18:25',
                'updated_at' => '2021-05-31 07:30:35',
            ),
            12 =>
            array (
                'id' => 22,
                'name' => 'spaces',
                'slug' => 'spaces',
                'display_name_singular' => 'Space',
                'display_name_plural' => 'Spaces',
                'icon' => 'voyager-lighthouse',
                'model_name' => 'App\\Models\\Space',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":"id","order_display_column":"name","order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2021-05-31 07:22:29',
                'updated_at' => '2021-06-06 17:46:24',
            ),
            13 =>
            array (
                'id' => 23,
                'name' => 'discount_categories',
                'slug' => 'discount-categories',
                'display_name_singular' => 'Discount Category',
                'display_name_plural' => 'Discount Categories',
                'icon' => 'voyager-tag',
                'model_name' => 'App\\Models\\Categories\\DiscountCategory',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":"id","order_display_column":"name","order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2021-05-31 07:39:09',
                'updated_at' => '2021-06-06 17:32:20',
            ),
            14 =>
            array (
                'id' => 24,
                'name' => 'discounts',
                'slug' => 'discounts',
                'display_name_singular' => 'Discount',
                'display_name_plural' => 'Discounts',
                'icon' => 'voyager-tag',
                'model_name' => 'App\\Models\\Discount',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":"id","order_display_column":"name","order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2021-05-31 07:42:26',
                'updated_at' => '2021-06-06 17:45:05',
            ),
            15 =>
            array (
                'id' => 25,
                'name' => 'imperia_roles',
                'slug' => 'imperia-roles',
                'display_name_singular' => 'Imperia Role',
                'display_name_plural' => 'Imperia Roles',
                'icon' => 'voyager-group',
                'model_name' => 'App\\Models\\ImperiaRole',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":"id","order_display_column":"name","order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2021-06-04 18:50:23',
                'updated_at' => '2021-06-06 17:30:56',
            ),
            16 =>
            array (
                'id' => 26,
                'name' => 'imperia_users',
                'slug' => 'imperia-users',
                'display_name_singular' => 'Imperia User',
                'display_name_plural' => 'Imperia Users',
                'icon' => 'voyager-people',
                'model_name' => 'App\\Models\\ImperiaUser',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":"id","order_display_column":"name","order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2021-06-04 18:52:04',
                'updated_at' => '2021-06-06 17:31:11',
            ),
        ));
    }
}
