<?php

namespace Database\Seeders\Voyager;

use Illuminate\Database\Seeder;

class VoyagerMenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('menu_items')->delete();

        \DB::table('menu_items')->insert(array (
            0 =>
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Дошка',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2021-05-27 11:51:32',
                'updated_at' => '2021-06-06 18:29:17',
                'route' => 'voyager.dashboard',
                'parameters' => 'null',
            ),
            1 =>
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2021-05-27 11:51:32',
                'updated_at' => '2021-06-04 19:16:13',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2021-05-27 11:51:32',
                'updated_at' => '2021-06-04 19:16:13',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2021-05-27 11:51:32',
                'updated_at' => '2021-06-06 18:28:43',
                'route' => 'voyager.roles.index',
                'parameters' => 'null',
            ),
            4 =>
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2021-05-27 11:51:32',
                'updated_at' => '2021-06-04 19:16:13',
                'route' => NULL,
                'parameters' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2021-05-27 11:51:32',
                'updated_at' => '2021-05-31 07:12:36',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2021-05-27 11:51:32',
                'updated_at' => '2021-05-31 07:12:36',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2021-05-27 11:51:32',
                'updated_at' => '2021-05-31 07:12:36',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2021-05-27 11:51:32',
                'updated_at' => '2021-05-31 07:12:36',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 =>
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2021-05-27 11:51:32',
                'updated_at' => '2021-06-06 18:29:03',
                'route' => 'voyager.settings.index',
                'parameters' => 'null',
            ),
            10 =>
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Hooks',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-hook',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 5,
                'created_at' => '2021-05-27 11:51:33',
                'updated_at' => '2021-06-06 18:29:04',
                'route' => 'voyager.hooks',
                'parameters' => NULL,
            ),
            11 =>
            array (
                'id' => 12,
                'menu_id' => 1,
                'title' => 'Категорії Квитків',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-ticket',
                'color' => '#000000',
                'parent_id' => 23,
                'order' => 1,
                'created_at' => '2021-05-27 12:47:59',
                'updated_at' => '2021-06-06 18:26:07',
                'route' => 'voyager.ticket-categories.index',
                'parameters' => 'null',
            ),
            12 =>
            array (
                'id' => 13,
                'menu_id' => 1,
                'title' => 'Квитки',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-ticket',
                'color' => '#000000',
                'parent_id' => 24,
                'order' => 1,
                'created_at' => '2021-05-27 12:53:05',
                'updated_at' => '2021-06-06 18:23:42',
                'route' => 'voyager.tickets.index',
                'parameters' => 'null',
            ),
            13 =>
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Послуги',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-pirate',
                'color' => '#000000',
                'parent_id' => 24,
                'order' => 3,
                'created_at' => '2021-05-30 06:04:50',
                'updated_at' => '2021-06-06 18:24:31',
                'route' => 'voyager.services.index',
                'parameters' => 'null',
            ),
            14 =>
            array (
                'id' => 16,
                'menu_id' => 1,
                'title' => 'Категорії Послуг',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-pirate',
                'color' => '#000000',
                'parent_id' => 23,
                'order' => 3,
                'created_at' => '2021-05-30 06:09:37',
                'updated_at' => '2021-06-06 18:26:27',
                'route' => 'voyager.service-categories.index',
                'parameters' => 'null',
            ),
            15 =>
            array (
                'id' => 19,
                'menu_id' => 1,
                'title' => 'Категорії Страв / Напоїв',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-pizza',
                'color' => '#000000',
                'parent_id' => 23,
                'order' => 4,
                'created_at' => '2021-05-30 06:19:59',
                'updated_at' => '2021-06-06 18:26:39',
                'route' => 'voyager.product-categories.index',
                'parameters' => 'null',
            ),
            16 =>
            array (
                'id' => 20,
                'menu_id' => 1,
                'title' => 'Категорії Меню',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-documentation',
                'color' => '#000000',
                'parent_id' => 23,
                'order' => 5,
                'created_at' => '2021-05-30 06:21:46',
                'updated_at' => '2021-06-06 18:27:03',
                'route' => 'voyager.menu-categories.index',
                'parameters' => 'null',
            ),
            17 =>
            array (
                'id' => 21,
                'menu_id' => 1,
                'title' => 'Меню',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-documentation',
                'color' => '#000000',
                'parent_id' => 24,
                'order' => 4,
                'created_at' => '2021-05-30 06:23:39',
                'updated_at' => '2021-06-06 18:24:38',
                'route' => 'voyager.imperia-menus.index',
                'parameters' => 'null',
            ),
            18 =>
            array (
                'id' => 22,
                'menu_id' => 1,
                'title' => 'Страви / Напої',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-pizza',
                'color' => '#000000',
                'parent_id' => 24,
                'order' => 5,
                'created_at' => '2021-05-30 06:31:05',
                'updated_at' => '2021-06-06 18:25:00',
                'route' => 'voyager.products.index',
                'parameters' => 'null',
            ),
            19 =>
            array (
                'id' => 23,
                'menu_id' => 1,
                'title' => 'Категорії',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2021-05-31 07:12:28',
                'updated_at' => '2021-06-06 18:25:22',
                'route' => NULL,
                'parameters' => '',
            ),
            20 =>
            array (
                'id' => 24,
                'menu_id' => 1,
                'title' => 'Пропозиції',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-buy',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2021-05-31 07:14:13',
                'updated_at' => '2021-06-06 18:23:32',
                'route' => NULL,
                'parameters' => '',
            ),
            21 =>
            array (
                'id' => 25,
                'menu_id' => 1,
                'title' => 'Категорії Столів / Кімнат',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lighthouse',
                'color' => '#000000',
                'parent_id' => 23,
                'order' => 2,
                'created_at' => '2021-05-31 07:18:26',
                'updated_at' => '2021-06-06 18:26:17',
                'route' => 'voyager.space-categories.index',
                'parameters' => 'null',
            ),
            22 =>
            array (
                'id' => 26,
                'menu_id' => 1,
                'title' => 'Столи / Кімнати',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lighthouse',
                'color' => '#000000',
                'parent_id' => 24,
                'order' => 2,
                'created_at' => '2021-05-31 07:22:29',
                'updated_at' => '2021-06-06 18:24:01',
                'route' => 'voyager.spaces.index',
                'parameters' => 'null',
            ),
            23 =>
            array (
                'id' => 27,
                'menu_id' => 1,
                'title' => 'Категорії Знижок',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tag',
                'color' => '#000000',
                'parent_id' => 23,
                'order' => 6,
                'created_at' => '2021-05-31 07:39:09',
                'updated_at' => '2021-06-06 18:27:15',
                'route' => 'voyager.discount-categories.index',
                'parameters' => 'null',
            ),
            24 =>
            array (
                'id' => 28,
                'menu_id' => 1,
                'title' => 'Знижки',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tag',
                'color' => '#000000',
                'parent_id' => 24,
                'order' => 6,
                'created_at' => '2021-05-31 07:42:26',
                'updated_at' => '2021-06-06 18:25:09',
                'route' => 'voyager.discounts.index',
                'parameters' => 'null',
            ),
            25 =>
            array (
                'id' => 29,
                'menu_id' => 1,
                'title' => 'Ролі Користувачів',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-group',
                'color' => '#000000',
                'parent_id' => 31,
                'order' => 2,
                'created_at' => '2021-06-04 18:50:23',
                'updated_at' => '2021-06-06 18:28:06',
                'route' => 'voyager.imperia-roles.index',
                'parameters' => 'null',
            ),
            26 =>
            array (
                'id' => 30,
                'menu_id' => 1,
                'title' => 'Користувачі',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-people',
                'color' => '#000000',
                'parent_id' => 31,
                'order' => 1,
                'created_at' => '2021-06-04 18:52:04',
                'updated_at' => '2021-06-06 18:27:53',
                'route' => 'voyager.imperia-users.index',
                'parameters' => 'null',
            ),
            27 =>
            array (
                'id' => 31,
                'menu_id' => 1,
                'title' => 'Доступ',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2021-06-04 19:15:55',
                'updated_at' => '2021-06-06 18:27:26',
                'route' => NULL,
                'parameters' => '',
            ),
        ));


    }
}
